'use client';

/**
 * CompanySelector - Search or create companies (database-first via RPC)
 */

import { Building2, Plus, Search } from 'lucide-react';
import { useCallback, useEffect, useId, useState } from 'react';
import { Button } from '@/src/components/primitives/button';
import { Input } from '@/src/components/primitives/input';
import { Label } from '@/src/components/primitives/label';
import { Popover, PopoverContent, PopoverTrigger } from '@/src/components/primitives/popover';
import { createClient } from '@/src/lib/supabase/client';
import { UI_CLASSES } from '@/src/lib/ui-constants';
import type { Database } from '@/src/types/database.types';

type Company = Database['public']['Tables']['companies']['Row'];

interface CompanySelectorProps {
  value?: string | null; // company_id
  onChange: (companyId: string | null, companyName: string) => void;
  defaultCompanyName?: string | undefined; // For legacy text field migration
}

export function CompanySelector({ value, onChange, defaultCompanyName }: CompanySelectorProps) {
  const buttonId = useId();
  const nameInputId = useId();
  const websiteInputId = useId();
  const [open, setOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [companies, setCompanies] = useState<Company[]>([]);
  const [selectedCompany, setSelectedCompany] = useState<Company | null>(null);
  const [isSearching, setIsSearching] = useState(false);
  const [showCreateForm, setShowCreateForm] = useState(false);

  const supabase = createClient();

  // Load selected company on mount
  useEffect(() => {
    if (value) {
      supabase
        .from('companies')
        .select('*')
        .eq('id', value)
        .single()
        .then(({ data }) => {
          if (data) setSelectedCompany(data);
        });
    }
  }, [value, supabase]);

  // Debounced search
  const searchCompanies = useCallback(
    async (query: string) => {
      if (!query.trim() || query.length < 2) {
        setCompanies([]);
        return;
      }

      setIsSearching(true);
      const { data } = await supabase
        .from('companies')
        .select('*')
        .ilike('name', `%${query}%`)
        .order('name')
        .limit(10);

      setCompanies(data || []);
      setIsSearching(false);
    },
    [supabase]
  );

  useEffect(() => {
    const timer = setTimeout(() => searchCompanies(searchQuery), 300);
    return () => clearTimeout(timer);
  }, [searchQuery, searchCompanies]);

  const handleSelect = (company: Company) => {
    setSelectedCompany(company);
    onChange(company.id, company.name);
    setOpen(false);
    setSearchQuery('');
  };

  const handleCreate = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const name = formData.get('name') as string;
    const website = formData.get('website') as string;

    if (!name.trim()) return;

    // Create company via database (slug auto-generated by trigger)
    const { data, error } = await supabase
      .from('companies')
      .insert({
        name: name.trim(),
        website: website.trim() || null,
        slug: name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, ''),
      })
      .select()
      .single();

    if (!error && data) {
      handleSelect(data);
      setShowCreateForm(false);
    }
  };

  return (
    <div className="space-y-2">
      <Label htmlFor={buttonId}>
        Company <span className="text-destructive">*</span>
      </Label>
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            id={buttonId}
            variant="outline"
            role="combobox"
            aria-expanded={open}
            className="w-full justify-between"
          >
            {selectedCompany ? (
              <span className="flex items-center gap-2">
                <Building2 className={UI_CLASSES.ICON_SM} />
                {selectedCompany.name}
              </span>
            ) : (
              <span className="text-muted-foreground">
                {defaultCompanyName || 'Select or create company...'}
              </span>
            )}
            <Search className={`${UI_CLASSES.ICON_SM} opacity-50`} />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-[400px] p-0" align="start">
          {showCreateForm ? (
            <form onSubmit={handleCreate} className="space-y-3 p-4">
              <div className="space-y-2">
                <Label htmlFor={nameInputId}>Company Name</Label>
                <Input
                  id={nameInputId}
                  name="name"
                  placeholder="e.g., Acme Corp"
                  required
                  defaultValue={searchQuery}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor={websiteInputId}>Website (Optional)</Label>
                <Input
                  id={websiteInputId}
                  name="website"
                  type="url"
                  placeholder="https://company.com"
                />
              </div>
              <div className="flex gap-2">
                <Button type="submit" size="sm" className="flex-1">
                  Create
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setShowCreateForm(false);
                    setSearchQuery('');
                  }}
                >
                  Cancel
                </Button>
              </div>
            </form>
          ) : (
            <div className="space-y-2 p-2">
              <Input
                placeholder="Search companies..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="h-9"
              />
              {isSearching ? (
                <p className={`${UI_CLASSES.TEXT_SM_MUTED} px-2 py-4`}>Searching...</p>
              ) : companies.length > 0 ? (
                <div className="max-h-[200px] space-y-1 overflow-y-auto">
                  {companies.map((company) => (
                    <button
                      key={company.id}
                      type="button"
                      onClick={() => handleSelect(company)}
                      className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm hover:bg-accent"
                    >
                      <Building2 className={UI_CLASSES.ICON_SM} />
                      <span>{company.name}</span>
                    </button>
                  ))}
                </div>
              ) : searchQuery.length >= 2 ? (
                <p className={`${UI_CLASSES.TEXT_SM_MUTED} px-2 py-4`}>No companies found</p>
              ) : null}
              <Button
                type="button"
                variant="outline"
                className="w-full"
                onClick={() => setShowCreateForm(true)}
              >
                <Plus className={UI_CLASSES.ICON_SM} />
                Create new company
              </Button>
            </div>
          )}
        </PopoverContent>
      </Popover>
      <input type="hidden" name="company_id" value={value || ''} />
      <input
        type="hidden"
        name="company"
        value={selectedCompany?.name || defaultCompanyName || ''}
      />
    </div>
  );
}
