/**
 * UI Constants - Category-Specific Configuration
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/build/generate-category-artifacts.ts
 * Source: UNIFIED_CATEGORY_REGISTRY in src/lib/config/category-config.ts
 *
 * Category-derived UI configuration including badge colors and card behaviors.
 * Split from main ui-constants.ts to enable tree-shaking and prevent server imports.
 *
 * **Why This File Exists:**
 * - Main ui-constants.ts cannot import from category-config (server code)
 * - This file is generated at build time from the registry
 * - Only category-specific configuration (badge colors, behaviors)
 * - Eliminates manual synchronization when adding categories
 *
 * **To Add a New Category:**
 * 1. Add to UNIFIED_CATEGORY_REGISTRY in category-config.ts
 * 2. Run: npm run generate:categories
 * 3. This file auto-updates!
 *
 * @module lib/ui-constants-categories
 */

// ============================================================================
// CARD BEHAVIORS - Category-Driven
// ============================================================================

// Default behavior template for config-based categories
const DEFAULT_CONFIG_BEHAVIOR = {
  showCopyButton: true,
  showViewCount: true,
  showCopyCount: true,
  showRating: true,
  showFeaturedBadge: true,
} as const;

// Default behavior template for guide-like categories
const DEFAULT_GUIDE_BEHAVIOR = {
  showCopyButton: false,
  showViewCount: true,
  showCopyCount: false,
  showRating: true,
  showFeaturedBadge: true,
} as const;

/**
 * Card Behavior Configuration
 *
 * Auto-generated from UNIFIED_CATEGORY_REGISTRY with overrides for special cases.
 * Controls which UI elements appear on content cards (copy button, ratings, etc.).
 *
 * Current categories (11): agents, mcp, commands, rules, hooks, statuslines, collections, skills, guides, jobs, changelog
 */
export const CARD_BEHAVIORS = {
  // Default for unknown categories
  default: DEFAULT_CONFIG_BEHAVIOR,

  // Registry categories (auto-generated)
  agents: DEFAULT_CONFIG_BEHAVIOR,
  mcp: DEFAULT_CONFIG_BEHAVIOR,
  commands: DEFAULT_CONFIG_BEHAVIOR,
  rules: DEFAULT_CONFIG_BEHAVIOR,
  hooks: DEFAULT_CONFIG_BEHAVIOR,
  statuslines: DEFAULT_CONFIG_BEHAVIOR,
  skills: DEFAULT_CONFIG_BEHAVIOR,

  // Guide-like categories (educational content - not copyable)
  guides: DEFAULT_GUIDE_BEHAVIOR,

  // Special case overrides
  collections: {
    showCopyButton: true,
    showViewCount: true,
    showCopyCount: true,
    showRating: false, // Collections don't have ratings (yet)
    showFeaturedBadge: false, // Collections have their own type badges
  },

  jobs: DEFAULT_CONFIG_BEHAVIOR,
  changelog: DEFAULT_GUIDE_BEHAVIOR,
} as const;

/**
 * Type-safe card behavior keys
 */
export type CardBehaviorKey = keyof typeof CARD_BEHAVIORS;

// ============================================================================
// BADGE COLORS - Category-Driven
// ============================================================================

/**
 * Category Badge Colors
 *
 * Auto-generated from UNIFIED_CATEGORY_REGISTRY colorScheme values.
 * Used in DetailSidebar, category badges, and UI components.
 *
 * Color mapping:
 * - agents: purple-500
 * - mcp: green-500
 * - commands: orange-500
 * - rules: blue-500
 * - hooks: blue-500
 * - statuslines: cyan-500
 * - collections: indigo-500
 * - skills: emerald-500
 * - guides: blue-500
 * - jobs: indigo-500
 * - changelog: slate-500
 */
export const CATEGORY_BADGE_COLORS = {
  default: 'bg-primary/20 text-primary border-primary/30',

  // Category-specific colors (from UNIFIED_CATEGORY_REGISTRY)
  agents: 'bg-purple-500/20 text-purple-500 border-purple-500/30',
  mcp: 'bg-green-500/20 text-green-500 border-green-500/30',
  commands: 'bg-orange-500/20 text-orange-500 border-orange-500/30',
  rules: 'bg-blue-500/20 text-blue-500 border-blue-500/30',
  hooks: 'bg-blue-500/20 text-blue-500 border-blue-500/30',
  statuslines: 'bg-cyan-500/20 text-cyan-500 border-cyan-500/30',
  collections: 'bg-indigo-500/20 text-indigo-500 border-indigo-500/30',
  skills: 'bg-emerald-500/20 text-emerald-500 border-emerald-500/30',
  guides: 'bg-blue-500/20 text-blue-500 border-blue-500/30',
  jobs: 'bg-indigo-500/20 text-indigo-500 border-indigo-500/30',
  changelog: 'bg-slate-500/20 text-slate-500 border-slate-500/30',
} as const;

/**
 * Type-safe category badge color keys
 */
export type CategoryBadgeColorKey = keyof typeof CATEGORY_BADGE_COLORS;
