name: 'Setup'
description: 'Setup repository with pnpm and Node.js'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      shell: bash
      
    - uses: pnpm/action-setup@v3
      with:
        version: 10.23.0
      shell: bash
          
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
