# CodeRabbit Configuration - Optimized for Solo Developer
# This file limits which files CodeRabbit reviews to stay under the 100 file limit

language: en-US
early_access: true
enable_free_tier: true

reviews:
  # Chill profile = less strict, faster reviews, less noise
  profile: chill
  
  # Don't block merges on suggestions
  request_changes_workflow: false
  
  # Quick overview of changes
  high_level_summary: true
  
  # Show review status but don't block commits (lefthook handles this)
  review_status: true
  commit_status: false
  fail_commit_status: false
  
  # Reduce noise
  collapse_walkthrough: false
  changed_files_summary: true
  poem: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  
  # Auto-review PRs
  auto_review:
    enabled: true
    drafts: false
  
  # PATH FILTERS - Critical for staying under file limit (now 200 with Pro)
  # Only include source code files that should be reviewed
  # Exclude everything else (generated files, binaries, docs, etc.)
  #
  # ⚠️ IMPORTANT: CodeRabbit CLI discovers ALL files first, then applies filters
  # If >25% are excluded, it fails. For full directory reviews, use PR reviews instead.
  # For CLI, use --type committed/uncommitted to review only changed files.
  path_filters:
    # ============================================
    # INCLUDE PATHS (whitelist - ONLY these will be reviewed)
    # ============================================
    # When you have include paths, CodeRabbit ONLY reviews files matching these
    # NOTE: For CLI with --type all, this still discovers all files first
    # Use --type committed/uncommitted for CLI, or PR reviews for full directory reviews
    
    - "apps/web/src/**/*.{ts,tsx}"
    - "apps/edge/functions/**/*.{ts,tsx}"
    - "packages/**/src/**/*.{ts,tsx}"
    
    # ============================================
    # EXCLUDE PATHS (further filtering within included paths)
    # ============================================
    # These exclude files from the included paths above
    
    # Exclude build/cache directories
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/dist/**"
    - "!**/out/**"
    - "!**/.turbo/**"
    - "!**/.build-cache/**"
    - "!**/coverage/**"
    - "!**/.nyc_output/**"
    
    # Exclude file types
    - "!**/*.json"                 # Exclude JSON (except what we include)
    - "!**/*.md"                    # Exclude markdown
    - "!**/*.yml"                   # Exclude YAML
    - "!**/*.yaml"                  # Exclude YAML
    - "!**/*.toml"                  # Exclude TOML
    - "!**/*.css"                   # Exclude CSS
    - "!**/*.scss"                  # Exclude SCSS
    - "!**/*.html"                  # Exclude HTML
    
    # Exclude generated files
    - "!**/*.generated.ts"
    - "!**/*.generated.tsx"
    - "!packages/database-types/src/index.ts"
    - "!packages/web-runtime/src/config/generated-config.ts"
    - "!packages/web-runtime/src/data/config/category/category-config.generated.ts"
    - "!apps/web/next-env.d.ts"
    
    # Exclude test files
    - "!**/*.test.ts"
    - "!**/*.test.tsx"
    - "!**/*.spec.ts"
    - "!**/*.spec.tsx"
    - "!**/__tests__/**"
    - "!**/tests/**"
    
    # Exclude binary files
    - "!**/*.zip"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.woff"
    - "!**/*.woff2"
    - "!**/*.ttf"
    - "!**/*.eot"
    - "!**/*.ico"
    
    # Exclude other files
    - "!**/*.lock"
    - "!**/*.log"
    - "!**/*.cache"
    - "!**/.env*"
    - "!**/LICENSE"
    - "!**/README.md"
    - "!**/CHANGELOG.md"
  
  # Tool configuration - enable only what's relevant
  tools:
    # TypeScript/JavaScript tools
    eslint:
      enabled: true
    biome:
      enabled: true
    
    # Security tools
    gitleaks:
      enabled: true
    
    # Configuration file validation
    actionlint:
      enabled: true
    yamllint:
      enabled: true
    
    # GitHub integration
    github-checks:
      enabled: true
      timeout_ms: 90000
    
    # Disable unused tools (reduces noise and improves speed)
    ruff:
      enabled: false
    rubocop:
      enabled: false
    swiftlint:
      enabled: false
    golangci-lint:
      enabled: false
    phpstan:
      enabled: false
    detekt:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    pmd:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    cppcheck:
      enabled: false
    circleci:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    prismaLint:
      enabled: false
    pylint:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    dotenvLint:
      enabled: false
    htmlhint:
      enabled: false
    checkmake:
      enabled: false
    hadolint:
      enabled: false
    semgrep:
      enabled: false
    checkov:
      enabled: false
    markdownlint:
      enabled: false
    languagetool:
      enabled: false
    shellcheck:
      enabled: false
    ast-grep:
      essential_rules: false
      rule_dirs: []
      util_dirs: []
      packages: []

chat:
  # Don't auto-reply (solo dev)
  auto_reply: false

knowledge_base:
  # Keep learning enabled to improve over time
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto

# ============================================================================
# Unit Test Generation Configuration
# ============================================================================
# CodeRabbit can automatically generate unit tests for your code changes.
# Use: Comment "@coderabbitai generate unit tests" in any PR, or check the
# "Generate unit tests" checkbox in CodeRabbit Walkthrough.
#
# Test files are co-located with source files using *.test.ts naming.
# Example: content.ts → content.test.ts (same directory)
# ============================================================================
code_generation:
  unit_tests:
    path_instructions:
      # Data Layer Services - RPC-focused testing
      - path: "packages/data-layer/src/services/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Mock SupabaseClient using vi.mock().
          Test RPC error handling, input validation, and return types.
          Use @heyclaude/database-types for type assertions.
          Test edge cases: empty results, null values, database errors.
          Follow the pattern from packages/edge-runtime/src/utils/integrations/resend.test.ts for mocking structure.
          Co-locate tests: content.ts → content.test.ts (same directory).
      
      # Server Actions - Schema validation and auth
      - path: "packages/web-runtime/src/actions/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Test Zod schema validation (invalid inputs should fail).
          Mock authentication context (authedAction vs optionalAuthAction).
          Test rate limiting behavior.
          Mock data layer services (don't call real RPCs).
          Test error handling and logging.
          Verify action metadata is correct.
          Mock next/headers and next/cache (already set up in vitest.setup.ts).
          Co-locate tests: content.ts → content.test.ts (same directory).
      
      # RPC Utilities - Error handling and logging
      - path: "packages/web-runtime/src/rpc/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Mock SupabaseClient and test error scenarios.
          Verify error normalization and logging context.
          Test timeout handling if applicable.
          Co-locate tests: run-rpc.ts → run-rpc.test.ts (same directory).
      
      # Cache Utilities - Cache behavior
      - path: "packages/web-runtime/src/cache/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Mock Next.js unstable_cache (already set up in vitest.setup.ts).
          Test cache key generation, TTL, and tag invalidation.
          Test fallback values and cache miss scenarios.
          Co-locate tests: fetch-cached.ts → fetch-cached.test.ts (same directory).
      
      # Validation Scripts - Pattern matching
      - path: "packages/web-runtime/src/utils/validate-*.ts"
        instructions: |
          Use vitest for testing framework.
          Test with valid and invalid config files.
          Test pattern matching accuracy.
          Test error message clarity.
          Use file system mocks (vi.mock('fs')).
          Co-locate tests: validate-next-config.ts → validate-next-config.test.ts (same directory).
      
      # Error Handling - Normalization
      - path: "packages/web-runtime/src/errors.ts"
        instructions: |
          Use vitest for testing framework.
          Test error normalization with various error types.
          Test context preservation.
          Test logging integration.
          Co-locate tests: errors.ts → errors.test.ts (same directory).
      
      # Data Access Functions - Server-side data fetching
      - path: "packages/web-runtime/src/data/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Mock SupabaseClient and data layer services.
          Test caching behavior (fetchCached wrapper).
          Test error handling and fallback values.
          Test input validation and type safety.
          Co-locate tests: content.ts → content.test.ts (same directory).
      
      # Generator Commands - CLI utilities
      - path: "packages/generators/src/commands/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Test command-line argument parsing.
          Mock file system operations (vi.mock('fs')).
          Test error handling and user feedback.
          Mock external API calls and database operations.
          Co-locate tests: mcp-login.ts → mcp-login.test.ts (same directory).
      
      # Edge Runtime Utilities - Deno-compatible code
      - path: "packages/edge-runtime/src/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Test Deno-compatible code (no Node.js-specific APIs).
          Mock Supabase and external services.
          Test error handling and logging.
          Follow existing test patterns from packages/edge-runtime/src/utils/integrations/resend.test.ts.
          Co-locate tests: resend.ts → resend.test.ts (same directory).
      
      # Shared Runtime - Cross-platform utilities
      - path: "packages/shared-runtime/src/**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Test isomorphic code (works in both Node.js and Deno).
          Mock external dependencies.
          Test error handling, validation, and utility functions.
          Co-locate tests: error-handling.ts → error-handling.test.ts (same directory).
      
      # General TypeScript files (fallback)
      - path: "**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Generate comprehensive test cases including edge cases and error conditions.
          Include proper TypeScript types in test expectations.
          Follow existing test patterns from packages/edge-runtime/src/utils/integrations/resend.test.ts.
          Mock external dependencies (Supabase, Next.js APIs, etc.).
          Co-locate tests with source files: source.ts → source.test.ts (same directory).
          Use describe blocks for organization, it blocks for individual test cases.
          Exclude generated files (*.generated.ts) and test files (*.test.ts, *.spec.ts).
