name: 'Setup Node.js with Dependencies'
description: 'Setup Node.js with optimized caching and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  install-args:
    description: 'Additional arguments for pnpm install'
    required: false
    default: ''
  production-only:
    description: 'Install only production dependencies (--prod)'
    required: false
    default: 'false'

outputs:
  cache-hit:
    description: 'Whether dependencies cache was hit'
    value: 'true'  # Always true - setup-node handles caching

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.20.0

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    # Cache is handled by actions/setup-node@v6 above (cache: 'pnpm')
    # No need for duplicate caching - setup-node handles pnpm store automatically

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.production-only }}" = "true" ]; then
          echo "Installing production dependencies only..."
          pnpm install --frozen-lockfile --prod ${{ inputs.install-args }}
        else
          echo "Installing all dependencies..."
          pnpm install --frozen-lockfile ${{ inputs.install-args }}
        fi
