/**
 * Application Routes Configuration
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/build/generate-routes.ts
 *
 * Single source of truth for all internal routes
 * Type-safe navigation with proper TypeScript support
 *
 * @example
 * ```typescript
 * import { ROUTES } from '@/src/lib/constants/routes';
 *
 * // Static routes
 * router.push(ROUTES.HOME);
 *
 * // Dynamic routes with helpers
 * router.push(ROUTES.CATEGORY_DETAIL({ category: 'agents', slug: 'example' }));
 * ```
 */

// ============================================================================
// Static Routes
// ============================================================================

export const ROUTES = {
  HOME: '/',
  BOARD: '/board',
  BOARD_NEW: '/board/new',
  COMMUNITY: '/community',
  COMPANIES: '/companies',
  COMPARE: '/compare',
  FOR_YOU: '/for-you',
  LLMS_TXT: '/llms.txt',
  LOGIN: '/login',
  MANIFEST: '/manifest',
  PARTNER: '/partner',
  SEARCH: '/search',
  SUBMIT: '/submit',
  TRENDING: '/trending',
  AGENTS: '/agents', // content
  CHANGELOG: '/changelog', // content
  COLLECTIONS: '/collections', // content
  COMMANDS: '/commands', // content
  GUIDES: '/guides', // content
  HOOKS: '/hooks', // content
  JOBS: '/jobs', // content
  MCP: '/mcp', // content
  RULES: '/rules', // content
  SKILLS: '/skills', // content
  STATUSLINES: '/statuslines', // content
  ACCOUNT: '/account', // account
  ACCOUNT_ACTIVITY: '/account/activity', // account
  ACCOUNT_BOOKMARKS: '/account/bookmarks', // account
  ACCOUNT_COMPANIES: '/account/companies', // account
  ACCOUNT_JOBS: '/account/jobs', // account
  ACCOUNT_JOBS_NEW: '/account/jobs/new', // account
  ACCOUNT_LIBRARY: '/account/library', // account
  ACCOUNT_LIBRARY_NEW: '/account/library/new', // account
  ACCOUNT_SETTINGS: '/account/settings', // account
  ACCOUNT_SPONSORSHIPS: '/account/sponsorships', // account
  ACCOUNT_SUBMISSIONS: '/account/submissions', // account
  TOOLS_CONFIG_RECOMMENDER: '/tools/config-recommender', // tools
  AUTH_AUTH_CODE_ERROR: '/auth/auth-code-error', // auth
} as const;

// ============================================================================
// Dynamic Route Helpers
// ============================================================================

/**
 * /[category]
 */
export const CATEGORY = (params: { category: string }) => {
  const { category } = params;
  return `/${category}`;
};

/**
 * /[category]/[slug]
 */
export const CATEGORY_SLUG = (params: { category: string; slug: string }) => {
  const { category, slug } = params;
  return `/${category}/${slug}`;
};

/**
 * /guides/[category]/[slug]
 */
export const GUIDES_CATEGORY_SLUG = (params: { category: string; slug: string }) => {
  const { category, slug } = params;
  return `/guides/${category}/${slug}`;
};

/**
 * /changelog/[slug]
 */
export const CHANGELOG_SLUG = (params: { slug: string }) => {
  const { slug } = params;
  return `/changelog/${slug}`;
};

/**
 * /compare/[slug]
 */
export const COMPARE_SLUG = (params: { slug: string }) => {
  const { slug } = params;
  return `/compare/${slug}`;
};

/**
 * /jobs/[slug]
 */
export const JOBS_SLUG = (params: { slug: string }) => {
  const { slug } = params;
  return `/jobs/${slug}`;
};

/**
 * /u/[slug]
 */
export const U_SLUG = (params: { slug: string }) => {
  const { slug } = params;
  return `/u/${slug}`;
};

/**
 * /u/[slug]/collections/[collectionSlug]
 */
export const U_SLUG_COLLECTIONS_COLLECTIONSLUG = (params: {
  slug: string;
  collectionSlug: string;
}) => {
  const { slug, collectionSlug } = params;
  return `/u/${slug}/collections/${collectionSlug}`;
};

/**
 * /account/jobs/[id]/analytics
 */
export const ACCOUNT_JOBS_ID_ANALYTICS = (params: { id: string }) => {
  const { id } = params;
  return `/account/jobs/${id}/analytics`;
};

/**
 * /account/jobs/[id]/edit
 */
export const ACCOUNT_JOBS_ID_EDIT = (params: { id: string }) => {
  const { id } = params;
  return `/account/jobs/${id}/edit`;
};

/**
 * /account/library/[slug]
 */
export const ACCOUNT_LIBRARY_SLUG = (params: { slug: string }) => {
  const { slug } = params;
  return `/account/library/${slug}`;
};

/**
 * /account/library/[slug]/edit
 */
export const ACCOUNT_LIBRARY_SLUG_EDIT = (params: { slug: string }) => {
  const { slug } = params;
  return `/account/library/${slug}/edit`;
};

/**
 * /account/sponsorships/[id]/analytics
 */
export const ACCOUNT_SPONSORSHIPS_ID_ANALYTICS = (params: { id: string }) => {
  const { id } = params;
  return `/account/sponsorships/${id}/analytics`;
};

/**
 * /tools/config-recommender/results/[id]
 */
export const TOOLS_CONFIG_RECOMMENDER_RESULTS_ID = (params: { id: string }) => {
  const { id } = params;
  return `/tools/config-recommender/results/${id}`;
};

// ============================================================================
// All Routes (for validation/testing)
// ============================================================================

export const ALL_STATIC_ROUTES = [
  '/',
  '/board',
  '/board/new',
  '/community',
  '/companies',
  '/compare',
  '/for-you',
  '/llms.txt',
  '/login',
  '/manifest',
  '/partner',
  '/search',
  '/submit',
  '/trending',
  '/agents',
  '/changelog',
  '/collections',
  '/commands',
  '/guides',
  '/hooks',
  '/jobs',
  '/mcp',
  '/rules',
  '/skills',
  '/statuslines',
  '/account',
  '/account/activity',
  '/account/bookmarks',
  '/account/companies',
  '/account/jobs',
  '/account/jobs/new',
  '/account/library',
  '/account/library/new',
  '/account/settings',
  '/account/sponsorships',
  '/account/submissions',
  '/tools/config-recommender',
  '/auth/auth-code-error',
] as const;

export const ALL_DYNAMIC_ROUTE_PATTERNS = [
  '/[category]',
  '/[category]/[slug]',
  '/guides/[category]/[slug]',
  '/changelog/[slug]',
  '/compare/[slug]',
  '/jobs/[slug]',
  '/u/[slug]',
  '/u/[slug]/collections/[collectionSlug]',
  '/account/jobs/[id]/analytics',
  '/account/jobs/[id]/edit',
  '/account/library/[slug]',
  '/account/library/[slug]/edit',
  '/account/sponsorships/[id]/analytics',
  '/tools/config-recommender/results/[id]',
] as const;
