/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

import { logRpcError } from '../utils/rpc-error-logging.ts';

export class ChangelogService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: get_changelog_overview
   */
  async getChangelogOverview(args: Database['public']['Functions']['get_changelog_overview']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_changelog_overview', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_changelog_overview',
          operation: 'ChangelogService.getChangelogOverview',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_changelog_detail
   */
  async getChangelogDetail(args: Database['public']['Functions']['get_changelog_detail']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_changelog_detail', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_changelog_detail',
          operation: 'ChangelogService.getChangelogDetail',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_changelog_with_category_stats
   */
  async getChangelogWithCategoryStats(args: Database['public']['Functions']['get_changelog_with_category_stats']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_changelog_with_category_stats', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_changelog_with_category_stats',
          operation: 'ChangelogService.getChangelogWithCategoryStats',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }
}
