/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

import { logRpcError } from '../utils/rpc-error-logging.ts';

export interface ContentFilterOptions {
  author?: string;
  categories?: Database['public']['Enums']['content_category'][] | undefined;
  limit?: number;
  offset?: number;
  orderBy?: 'created_at' | 'slug' | 'title' | 'updated_at';
  orderDirection?: 'asc' | 'desc';
  search?: string;
  tags?: string[] | undefined;
}

export interface ReviewsFilterOptions {
  contentSlug: string;
  contentType: Database['public']['Enums']['content_category'];
  limit?: number;
  offset?: number;
  sortBy?: string;
  userId?: string;
}

export interface RelatedContentOptions {
  category: Database['public']['Enums']['content_category'];
  excludeSlugs?: string[];
  limit?: number;
  slug: string;
  tags?: string[] | undefined;
}

export interface SimilarContentOptions {
  contentSlug: string;
  contentType: Database['public']['Enums']['content_category'];
  limit?: number;
}

export class ContentService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: generate_readme_data
   */
  async getSitewideReadme() {
    try {
      const { data, error } = await this.supabase.rpc('generate_readme_data');
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_readme_data',
          operation: 'ContentService.getSitewideReadme',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_sitewide_content_list
   */
  async getSitewideContentList(
    args?: Database['public']['Functions']['get_sitewide_content_list']['Args']
  ) {
    try {
      const { data, error } = await this.supabase.rpc('get_sitewide_content_list', args ?? {});
      if (error) {
        logRpcError(error, {
          rpcName: 'get_sitewide_content_list',
          operation: 'ContentService.getSitewideContentList',
          args: args ?? {},
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_sitewide_llms_txt
   */
  async getSitewideLlmsTxt() {
    try {
      const { data, error } = await this.supabase.rpc('generate_sitewide_llms_txt');
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_sitewide_llms_txt',
          operation: 'ContentService.getSitewideLlmsTxt',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_changelog_llms_txt
   */
  async getChangelogLlmsTxt() {
    try {
      const { data, error } = await this.supabase.rpc('generate_changelog_llms_txt');
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_changelog_llms_txt',
          operation: 'ContentService.getChangelogLlmsTxt',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_category_llms_txt
   */
  async getCategoryLlmsTxt(args: Database['public']['Functions']['generate_category_llms_txt']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('generate_category_llms_txt', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_category_llms_txt',
          operation: 'ContentService.getCategoryLlmsTxt',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_changelog_entry_llms_txt
   */
  async getChangelogEntryLlmsTxt(args: Database['public']['Functions']['generate_changelog_entry_llms_txt']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('generate_changelog_entry_llms_txt', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_changelog_entry_llms_txt',
          operation: 'ContentService.getChangelogEntryLlmsTxt',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_tool_llms_txt
   */
  async getToolLlmsTxt(args: Database['public']['Functions']['generate_tool_llms_txt']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('generate_tool_llms_txt', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_tool_llms_txt',
          operation: 'ContentService.getToolLlmsTxt',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_category_configs_with_features
   */
  async getCategoryConfigs() {
    try {
      const { data, error } = await this.supabase.rpc('get_category_configs_with_features');
      if (error) {
        logRpcError(error, {
          rpcName: 'get_category_configs_with_features',
          operation: 'ContentService.getCategoryConfigs',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_api_content_full
   */
  async getApiContentFull(args: Database['public']['Functions']['get_api_content_full']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_api_content_full', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_api_content_full',
          operation: 'ContentService.getApiContentFull',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_markdown_export
   */
  async generateMarkdownExport(
    args: Database['public']['Functions']['generate_markdown_export']['Args']
  ) {
    try {
      const { data, error } = await this.supabase.rpc('generate_markdown_export', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_markdown_export',
          operation: 'ContentService.generateMarkdownExport',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: generate_item_llms_txt
   */
  async getItemLlmsTxt(args: Database['public']['Functions']['generate_item_llms_txt']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('generate_item_llms_txt', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'generate_item_llms_txt',
          operation: 'ContentService.getItemLlmsTxt',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_skill_storage_path
   */
  async getSkillStoragePath(
    args: Database['public']['Functions']['get_skill_storage_path']['Args']
  ) {
    try {
      const { data, error } = await this.supabase.rpc('get_skill_storage_path', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_skill_storage_path',
          operation: 'ContentService.getSkillStoragePath',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_mcpb_storage_path
   */
  async getMcpbStoragePath(
    args: Database['public']['Functions']['get_mcpb_storage_path']['Args']
  ) {
    try {
      const { data, error } = await this.supabase.rpc('get_mcpb_storage_path', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_mcpb_storage_path',
          operation: 'ContentService.getMcpbStoragePath',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_detail_complete
   */
  async getContentDetailComplete(args: Database['public']['Functions']['get_content_detail_complete']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_detail_complete', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_detail_complete',
          operation: 'ContentService.getContentDetailComplete',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_enriched_content_list
   */
  async getEnrichedContentList(args: Database['public']['Functions']['get_enriched_content_list']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_enriched_content_list', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_enriched_content_list',
          operation: 'ContentService.getEnrichedContentList',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_paginated
   */
  async getContentPaginated(args: Database['public']['Functions']['get_content_paginated']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_paginated', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_paginated',
          operation: 'ContentService.getContentPaginated',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_homepage_complete
   */
  async getHomepageComplete(args: Database['public']['Functions']['get_homepage_complete']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_homepage_complete', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_homepage_complete',
          operation: 'ContentService.getHomepageComplete',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_reviews_with_stats
   */
  async getReviewsWithStats(args: Database['public']['Functions']['get_reviews_with_stats']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_reviews_with_stats', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_reviews_with_stats',
          operation: 'ContentService.getReviewsWithStats',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_related_content
   */
  async getRelatedContent(args: Database['public']['Functions']['get_related_content']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_related_content', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_related_content',
          operation: 'ContentService.getRelatedContent',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_similar_content
   */
  async getSimilarContent(args: Database['public']['Functions']['get_similar_content']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_similar_content', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_similar_content',
          operation: 'ContentService.getSimilarContent',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_templates
   */
  async getContentTemplates(args: Database['public']['Functions']['get_content_templates']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_templates', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_templates',
          operation: 'ContentService.getContentTemplates',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_paginated_slim
   */
  async getContentPaginatedSlim(args: Database['public']['Functions']['get_content_paginated_slim']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_paginated_slim', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_paginated_slim',
          operation: 'ContentService.getContentPaginatedSlim',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_detail_core
   */
  async getContentDetailCore(args: Database['public']['Functions']['get_content_detail_core']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_detail_core', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_detail_core',
          operation: 'ContentService.getContentDetailCore',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_content_analytics
   */
  async getContentAnalytics(args: Database['public']['Functions']['get_content_analytics']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_content_analytics', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_content_analytics',
          operation: 'ContentService.getContentAnalytics',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_homepage_optimized
   * 
   * CRITICAL: Supabase RPCs returning composite types (RETURNS, not RETURNS SETOF)
   * return the data in a specific format. We need to handle this correctly.
   * 
   * NOTE: This method uses a different error-handling pattern (direct call with explicit
   * validation) compared to other RPC methods in this class. This is intentional because:
   * 1. Composite types require explicit type validation (null/array/object checks)
   * 2. The validation logic provides better error messages for schema mismatches
   * 3. Removes redundant try-catch wrapper while maintaining proper error logging
   * 
   * This pattern should be applied to other methods in a future refactor for consistency.
   */
  async getHomepageOptimized(args: Database['public']['Functions']['get_homepage_optimized']['Args']) {
    const { data, error } = await this.supabase.rpc('get_homepage_optimized', args);
    
    if (error) {
      // Log RPC error with business context
      logRpcError(error, {
        rpcName: 'get_homepage_optimized',
        operation: 'ContentService.getHomepageOptimized',
        args: args,
      });
      throw error;
    }
    
    // Null/undefined is expected when no rows returned
    if (data === null || data === undefined) {
      return null;
    }
    
    // Array format indicates schema mismatch - fail fast with descriptive error
    if (Array.isArray(data)) {
      const schemaError = new Error('Unexpected array format from get_homepage_optimized (expected single object) - possible schema/RPC misconfiguration');
      logRpcError(schemaError, {
        rpcName: 'get_homepage_optimized',
        operation: 'ContentService.getHomepageOptimized',
        args: args,
      });
      throw schemaError;
    }
    
    // Invalid data type - fail fast with descriptive error
    if (typeof data !== 'object') {
      const typeError = new Error(`Invalid data type from get_homepage_optimized: expected object, got ${typeof data}`);
      logRpcError(typeError, {
        rpcName: 'get_homepage_optimized',
        operation: 'ContentService.getHomepageOptimized',
        args: args,
      });
      throw typeError;
    }
    
    return data;
  }
}
