/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import type { Database } from '@heyclaude/database-types';
import type { SupabaseClient } from '@supabase/supabase-js';

export interface ContentFilterOptions {
  categories?: Database['public']['Enums']['content_category'][] | undefined;
  tags?: string[] | undefined;
  search?: string;
  author?: string;
  orderBy?: 'slug' | 'created_at' | 'updated_at' | 'title';
  orderDirection?: 'asc' | 'desc';
  limit?: number;
  offset?: number;
}

export interface ReviewsFilterOptions {
  contentType: Database['public']['Enums']['content_category'];
  contentSlug: string;
  sortBy?: string;
  limit?: number;
  offset?: number;
  userId?: string;
}

export interface RelatedContentOptions {
  category: Database['public']['Enums']['content_category'];
  slug: string;
  tags?: string[] | undefined;
  limit?: number;
  excludeSlugs?: string[];
}

export interface SimilarContentOptions {
  contentType: Database['public']['Enums']['content_category'];
  contentSlug: string;
  limit?: number;
}

export class ContentService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: generate_readme_data
   */
  async getSitewideReadme() {
    const { data, error } = await this.supabase.rpc('generate_readme_data');
    if (error) throw error;
    return data as Database['public']['Functions']['generate_readme_data']['Returns'];
  }

  /**
   * Calls the database RPC: generate_sitewide_llms_txt
   */
  async getSitewideLlmsTxt() {
    const { data, error } = await this.supabase.rpc('generate_sitewide_llms_txt');
    if (error) throw error;
    return data as Database['public']['Functions']['generate_sitewide_llms_txt']['Returns'];
  }

  /**
   * Calls the database RPC: generate_changelog_llms_txt
   */
  async getChangelogLlmsTxt() {
    const { data, error } = await this.supabase.rpc('generate_changelog_llms_txt');
    if (error) throw error;
    return data as Database['public']['Functions']['generate_changelog_llms_txt']['Returns'];
  }

  /**
   * Calls the database RPC: generate_category_llms_txt
   */
  async getCategoryLlmsTxt(args: Database['public']['Functions']['generate_category_llms_txt']['Args']) {
    const { data, error } = await this.supabase.rpc('generate_category_llms_txt', args);
    if (error) throw error;
    return data as Database['public']['Functions']['generate_category_llms_txt']['Returns'];
  }

  /**
   * Calls the database RPC: generate_changelog_entry_llms_txt
   */
  async getChangelogEntryLlmsTxt(args: Database['public']['Functions']['generate_changelog_entry_llms_txt']['Args']) {
    const { data, error } = await this.supabase.rpc('generate_changelog_entry_llms_txt', args);
    if (error) throw error;
    return data as Database['public']['Functions']['generate_changelog_entry_llms_txt']['Returns'];
  }

  /**
   * Calls the database RPC: generate_tool_llms_txt
   */
  async getToolLlmsTxt(args: Database['public']['Functions']['generate_tool_llms_txt']['Args']) {
    const { data, error } = await this.supabase.rpc('generate_tool_llms_txt', args);
    if (error) throw error;
    return data as Database['public']['Functions']['generate_tool_llms_txt']['Returns'];
  }

  /**
   * Calls the database RPC: get_category_configs_with_features
   */
  async getCategoryConfigs() {
    const { data, error } = await this.supabase.rpc('get_category_configs_with_features');
    if (error) throw error;
    return data as Database['public']['Functions']['get_category_configs_with_features']['Returns'];
  }

  /**
   * Calls the database RPC: get_api_content_full
   */
  async getApiContentFull(args: Database['public']['Functions']['get_api_content_full']['Args']) {
    const { data, error } = await this.supabase.rpc('get_api_content_full', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_api_content_full']['Returns'];
  }

  /**
   * Calls the database RPC: get_content_detail_complete
   */
  async getContentDetailComplete(args: Database['public']['Functions']['get_content_detail_complete']['Args']) {
    const { data, error } = await this.supabase.rpc('get_content_detail_complete', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_content_detail_complete']['Returns'];
  }

  /**
   * Calls the database RPC: get_enriched_content_list
   */
  async getEnrichedContentList(args: Database['public']['Functions']['get_enriched_content_list']['Args']) {
    const { data, error } = await this.supabase.rpc('get_enriched_content_list', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_enriched_content_list']['Returns'];
  }

  /**
   * Calls the database RPC: get_content_paginated
   */
  async getContentPaginated(args: Database['public']['Functions']['get_content_paginated']['Args']) {
    const { data, error } = await this.supabase.rpc('get_content_paginated', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_content_paginated']['Returns'];
  }

  /**
   * Calls the database RPC: get_homepage_complete
   */
  async getHomepageComplete(args: Database['public']['Functions']['get_homepage_complete']['Args']) {
    const { data, error } = await this.supabase.rpc('get_homepage_complete', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_homepage_complete']['Returns'];
  }

  /**
   * Calls the database RPC: get_reviews_with_stats
   */
  async getReviewsWithStats(args: Database['public']['Functions']['get_reviews_with_stats']['Args']) {
    const { data, error } = await this.supabase.rpc('get_reviews_with_stats', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_reviews_with_stats']['Returns'];
  }

  /**
   * Calls the database RPC: get_related_content
   */
  async getRelatedContent(args: Database['public']['Functions']['get_related_content']['Args']) {
    const { data, error } = await this.supabase.rpc('get_related_content', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_related_content']['Returns'];
  }

  /**
   * Calls the database RPC: get_similar_content
   */
  async getSimilarContent(args: Database['public']['Functions']['get_similar_content']['Args']) {
    const { data, error } = await this.supabase.rpc('get_similar_content', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_similar_content']['Returns'];
  }

  /**
   * Calls the database RPC: get_content_templates
   */
  async getContentTemplates(args: Database['public']['Functions']['get_content_templates']['Args']) {
    const { data, error } = await this.supabase.rpc('get_content_templates', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_content_templates']['Returns'];
  }

  /**
   * Calls the database RPC: get_content_paginated_slim
   */
  async getContentPaginatedSlim(args: Database['public']['Functions']['get_content_paginated_slim']['Args']) {
    const { data, error } = await this.supabase.rpc('get_content_paginated_slim', args);
    if (error) throw error;
    return data as Database['public']['Functions']['get_content_paginated_slim']['Returns'];
  }
}
