/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

import { logRpcError } from '../utils/rpc-error-logging.ts';

export class JobsService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: get_jobs_list
   */
  async getJobs() {
    try {
      const { data, error } = await this.supabase.rpc('get_jobs_list');
      if (error) {
        logRpcError(error, {
          rpcName: 'get_jobs_list',
          operation: 'JobsService.getJobs',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_job_detail
   */
  async getJobBySlug(args: Database['public']['Functions']['get_job_detail']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_job_detail', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_job_detail',
          operation: 'JobsService.getJobBySlug',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_featured_jobs
   */
  async getFeaturedJobs() {
    try {
      const { data, error } = await this.supabase.rpc('get_featured_jobs');
      if (error) {
        logRpcError(error, {
          rpcName: 'get_featured_jobs',
          operation: 'JobsService.getFeaturedJobs',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_jobs_by_category
   */
  async getJobsByCategory(args: Database['public']['Functions']['get_jobs_by_category']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('get_jobs_by_category', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'get_jobs_by_category',
          operation: 'JobsService.getJobsByCategory',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: get_jobs_count
   */
  async getJobsCount() {
    try {
      const { data, error } = await this.supabase.rpc('get_jobs_count');
      if (error) {
        logRpcError(error, {
          rpcName: 'get_jobs_count',
          operation: 'JobsService.getJobsCount',
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }
}
