/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

export class MiscService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: get_active_notifications
   */
  async getActiveNotifications(args: Database['public']['Functions']['get_active_notifications']['Args']) {
    const { data, error } = await this.supabase.rpc('get_active_notifications', args);
    if (error) throw error;
    return data;
  }

  /**
   * Calls the database RPC: get_active_announcement
   */
  async getActiveAnnouncement(args: Database['public']['Functions']['get_active_announcement']['Args']) {
    const { data, error } = await this.supabase.rpc('get_active_announcement', args);
    if (error) throw error;
    return data;
  }

  /**
   * Calls the database RPC: get_navigation_menu
   */
  async getNavigationMenu(args: Database['public']['Functions']['get_navigation_menu']['Args']) {
    const { data, error } = await this.supabase.rpc('get_navigation_menu', args);
    if (error) throw error;
    return data;
  }

  /**
   * Calls the database RPC: get_contact_commands
   */
  async getContactCommands(args: Database['public']['Functions']['get_contact_commands']['Args']) {
    const { data, error } = await this.supabase.rpc('get_contact_commands', args);
    if (error) throw error;
    return data;
  }

  /**
   * Calls the database RPC: get_form_field_config
   */
  async getFormFieldConfig(args: Database['public']['Functions']['get_form_field_config']['Args']) {
    const { data, error } = await this.supabase.rpc('get_form_field_config', args);
    if (error) throw error;
    return data;
  }
}
