/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

import { logRpcError } from '../utils/rpc-error-logging.ts';

export class SearchService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: search_unified
   */
  async searchUnified(args: Database['public']['Functions']['search_unified']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('search_unified', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'search_unified',
          operation: 'SearchService.searchUnified',
          args: args,
        });
        throw error;
      }
      // RPC can return null if no results or on error - normalize to empty array
      const rows = Array.isArray(data) ? data : (data === null || data === undefined ? [] : [data]);
      return { data: rows, total_count: rows.length };
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: search_content_optimized
   */
  async searchContent(args: Database['public']['Functions']['search_content_optimized']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('search_content_optimized', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'search_content_optimized',
          operation: 'SearchService.searchContent',
          args: args,
        });
        throw error;
      }
      const rows = data;
      return { data: rows, total_count: rows?.length ?? 0 };
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }

  /**
   * Calls the database RPC: filter_jobs
   */
  async filterJobs(args: Database['public']['Functions']['filter_jobs']['Args']) {
    try {
      const { data, error } = await this.supabase.rpc('filter_jobs', args);
      if (error) {
        logRpcError(error, {
          rpcName: 'filter_jobs',
          operation: 'SearchService.filterJobs',
          args: args,
        });
        throw error;
      }
      return data;
    } catch (error) {
      // Error already logged above
      throw error;
    }
  }
}
