/**
 * 🔒 AUTO-GENERATED SERVICE - DO NOT EDIT DIRECTLY
 * 
 * This file is generated by the "Hollow Core" architecture generator.
 * To update this service, update the database schema and re-run the generator.
 */

import  { type Database } from '@heyclaude/database-types';
import  { type SupabaseClient } from '@supabase/supabase-js';

export class SeoService {
  constructor(private supabase: SupabaseClient<Database>) {}

  /**
   * Calls the database RPC: generate_metadata_complete
   */
  async generateMetadata(args: Database['public']['Functions']['generate_metadata_complete']['Args']) {
    const { data, error } = await this.supabase.rpc('generate_metadata_complete', args);
    if (error) throw error;
    return data;
  }
}
