'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import type { Database } from '@heyclaude/database-types';

const addBookmarkSchema = z.object({
  content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  content_slug: z.string(),
  notes: z.string().optional()
});
export type AddBookmarkInput = z.infer<typeof addBookmarkSchema>;

export const addBookmark = authedAction
  .metadata({ actionName: 'addBookmark', category: 'user' })
  .inputSchema(addBookmarkSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['add_bookmark']['Returns']>(
        'add_bookmark',
        {
          'p_user_id': ctx.userId,
          'p_content_type': parsedInput.content_type,
          'p_content_slug': parsedInput.content_slug,
          'p_notes': parsedInput.notes
        },
        {
          action: 'addBookmark.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      // const { logActionFailure } = await import('../errors');
      const { revalidatePath, revalidateTag } = await import('next/cache');
      
      const { nextInvalidateByKeys } = await import('../cache-tags');
      const { getCacheConfigSnapshot } = await import('../cache-config');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/account`);
      revalidatePath(`/account/library`);
      revalidateTag(`user-bookmarks`, 'default');
      revalidateTag(`user-${ctx.userId}`, 'default');
      revalidateTag(`content-${parsedInput.content_slug}`, 'default');
      
      await nextInvalidateByKeys({
        cacheConfigPromise: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.bookmark_create']
      });

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('addBookmark', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
