'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import type { Database } from '@heyclaude/database-types';

const createCollectionSchema = z.object({
  name: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  is_public: z.boolean().nullable().optional()
});
export type CreateCollectionInput = z.infer<typeof createCollectionSchema>;

export const createCollection = authedAction
  .metadata({ actionName: 'createCollection', category: 'user' })
  .inputSchema(createCollectionSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['manage_collection']['Returns']>(
        'manage_collection',
        {
          'p_action': 'create',
          'p_user_id': ctx.userId,
          'p_create_data': {
            'name': parsedInput.name,
            'slug': parsedInput.slug,
            'description': parsedInput.description,
            'is_public': parsedInput.is_public
          },
          'p_update_data': null,
          'p_delete_id': null,
          'p_add_item_data': null,
          'p_remove_item_id': null
        },
        {
          action: 'createCollection.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      const { revalidatePath } = await import('next/cache');
      
      const { nextInvalidateByKeys } = await import('../cache-tags');
      const { getCacheConfigSnapshot } = await import('../cache-config');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/account`);
      revalidatePath(`/account/library`);
      
      const cacheConfig = getCacheConfigSnapshot();
      await nextInvalidateByKeys({
        cacheConfig,
        invalidateKeys: ['collection_create']
      });

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('createCollection', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
