// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import { logActionFailure } from '../errors';
import type { Database } from '@heyclaude/database-types';
import { revalidatePath, revalidateTag } from 'next/cache';
import { nextInvalidateByKeys } from '../cache-tags';
import { getCacheConfigSnapshot } from '../cache-config';

export const deleteCompanySchema = z.object({
  company_id: z.string().uuid()
});
export type DeleteCompanyInput = z.infer<typeof deleteCompanySchema>;

export const deleteCompany = authedAction
  .metadata({ actionName: 'deleteCompany', category: 'content' })
  .inputSchema(deleteCompanySchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['delete_company']['Returns']>(
        'delete_company',
        {
          'p_company_id': parsedInput.company_id,
          'p_user_id': ctx.userId
        },
        {
          action: 'deleteCompany.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/companies`);
      revalidatePath(`/account/companies`);
      revalidateTag(`company-${parsedInput.company_id}`, 'default');
      revalidateTag(`company-id-${parsedInput.company_id}`, 'default');
      
      await nextInvalidateByKeys({
        cacheConfigPromise: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.company_delete']
      });

      

      return result;
    } catch (error) {
      throw logActionFailure('deleteCompany', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
