'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import type { Database } from '@heyclaude/database-types';

const deleteCollectionSchema = z.object({
  delete_id: z.string().uuid().optional()
});
export type DeleteCollectionInput = z.infer<typeof deleteCollectionSchema>;

export const deleteCollection = authedAction
  .metadata({ actionName: 'deleteCollection', category: 'user' })
  .inputSchema(deleteCollectionSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['manage_collection']['Returns']>(
        'manage_collection',
        {
          'p_action': 'delete',
          'p_user_id': ctx.userId,
          'p_create_data': null,
          'p_update_data': null,
          'p_delete_id': parsedInput.delete_id,
          'p_add_item_data': null,
          'p_remove_item_id': null
        },
        {
          action: 'deleteCollection.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      // const { logActionFailure } = await import('../errors');
      const { revalidatePath } = await import('next/cache');
      
      const { nextInvalidateByKeys } = await import('../cache-tags');
      const { getCacheConfigSnapshot } = await import('../cache-config');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/account`);
      revalidatePath(`/account/library`);
      
      await nextInvalidateByKeys({
        cacheConfig: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.collection_delete']
      });

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('deleteCollection', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
