'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import type { Database } from '@heyclaude/database-types';

const markReviewHelpfulSchema = z.object({
  review_id: z.string().uuid(),
  helpful: z.boolean()
});
export type MarkReviewHelpfulInput = z.infer<typeof markReviewHelpfulSchema>;

export const markReviewHelpful = authedAction
  .metadata({ actionName: 'markReviewHelpful', category: 'user' })
  .inputSchema(markReviewHelpfulSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['toggle_review_helpful']['Returns']>(
        'toggle_review_helpful',
        {
          'p_review_id': parsedInput.review_id,
          'p_user_id': ctx.userId,
          'p_helpful': parsedInput.helpful
        },
        {
          action: 'markReviewHelpful.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      // const { logActionFailure } = await import('../errors');
      const { revalidatePath, revalidateTag } = await import('next/cache');
      
      const { nextInvalidateByKeys } = await import('../cache-tags');
      const { getCacheConfigSnapshot } = await import('../cache-config');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/${result?.content_type}/${result?.content_slug}`);
      revalidateTag(`reviews:${result?.content_type}:${result?.content_slug}`, 'default');
      
      await nextInvalidateByKeys({
        cacheConfig: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.review_helpful']
      });

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('markReviewHelpful', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
