'use server';

/**
 * Pulse Server Actions
 * Consolidated event tracking and recommendations
 */

import type { JsonValue } from '@heyclaude/data-layer/prisma';
import type { user_interactionsCreateInput } from '@heyclaude/database-types/prisma';
// Enum value objects not needed - using Zod schemas directly
// Keep imports minimal - only import what's actually used
// Import Zod schemas from re-export helper (works around TypeScript rootDir restrictions)
// These are generated by prisma-zod-generator and provide runtime validation
import {
  content_categorySchema,
  experience_levelSchema,
  focusAreaTypeSchema,
  integrationTypeSchema,
  interaction_typeSchema,
  useCaseTypeSchema,
  contact_action_typeSchema,
  contact_categorySchema,
} from '../prisma-zod-schemas.ts';
import { z } from 'zod';
import { logger } from '../logger.ts';
import { normalizeError } from '../errors.ts';
import { optionalAuthAction, rateLimitedAction } from './safe-action.ts';

// Note: Enum values are no longer needed - we use Prisma-generated Zod schemas directly
// The enum value objects (ContentCategory, etc.) are still available if needed for runtime checks

// ============================================
// TYPES
// ============================================

export type TrackInteractionParams = Omit<
  user_interactionsCreateInput,
  'id' | 'created_at' | 'user_id'
>;

// Types moved to pulse-types.ts to avoid Next.js serialization issues
// Import for internal use, re-export for backward compatibility
import type { RecommendationItem, RecommendationsPayload } from './pulse-types.ts';
export type { ConfigRecommendationsResponse, RecommendationsPayload } from './pulse-types.ts';

// ============================================
// ZOD SCHEMAS
// ============================================

const trackInteractionSchema = z.object({
  content_type: content_categorySchema.nullable().optional(),
  content_slug: z.string().nullable().optional(),
  interaction_type: interaction_typeSchema,
  session_id: z
    .string()
    .refine(
      (val) => {
        if (val === null || val === undefined || val === '') return true;
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        return uuidRegex.test(val);
      },
      { message: 'Invalid UUID format' }
    )
    .optional()
    .nullable(),
  metadata: z.unknown().optional().nullable(),
});

const trackNewsletterEventSchema = z.object({
  eventType: z.string(),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

const trackTerminalCommandSchema = z.object({
  command_id: z.string(),
  action_type: contact_action_typeSchema,
  success: z.boolean(),
  error_reason: z.string().optional(),
  execution_time_ms: z.number().int().min(0).optional(),
});

const trackTerminalFormSubmissionSchema = z.object({
  category: contact_categorySchema,
  success: z.boolean(),
  error: z.string().optional(),
});

const trackUsageSchema = z.object({
  content_type: content_categorySchema,
  content_slug: z.string(),
  action_type: z.enum(['copy', 'download_zip', 'download_markdown', 'llmstxt', 'download_mcpb', 'download_code']),
});

// getSimilarConfigsSchema removed - embedding generation system has been deleted

const generateConfigRecommendationsSchema = z.object({
  useCase: useCaseTypeSchema,
  experienceLevel: experience_levelSchema,
  toolPreferences: z.array(z.string()),
  integrations: z.array(integrationTypeSchema).optional(),
  focusAreas: z.array(focusAreaTypeSchema).optional(),
});

// ============================================
// USER INTERACTION TRACKING
// ============================================

/**
 * Helper to create pulse tracking actions
 * All tracking actions follow the same pattern - call enqueuePulseEventServer
 */
// Factory function moved to action-factory.ts to avoid Next.js serialization issues
// Import it from there
// Factory removed - using direct chains so Next.js recognizes them as server actions

export const trackInteractionAction = optionalAuthAction
  .inputSchema(trackInteractionSchema)
  .metadata({ actionName: 'pulse.trackInteraction', category: 'analytics' })
  .action(async ({ parsedInput, ctx }) => {
    const { enqueuePulseEventServer } = await import('../pulse.ts');
    await enqueuePulseEventServer({
      user_id: ctx.userId ?? null,
      content_type: parsedInput.content_type ?? null,
      content_slug: parsedInput.content_slug ?? null,
      interaction_type: parsedInput.interaction_type,
      session_id: parsedInput.session_id ?? null,
      metadata: parsedInput.metadata ? (parsedInput.metadata as JsonValue) : null,
    });
  });

export const trackNewsletterEventAction = optionalAuthAction
  .inputSchema(trackNewsletterEventSchema)
  .metadata({ actionName: 'pulse.trackNewsletterEvent', category: 'analytics' })
  .action(async ({ parsedInput, ctx }) => {
    const { enqueuePulseEventServer } = await import('../pulse.ts');
    await enqueuePulseEventServer({
      user_id: ctx.userId ?? null,
      content_type: null,
      content_slug: 'newsletter_cta',
      interaction_type: 'click',
      session_id: null,
      metadata: {
        event_type: parsedInput.eventType,
        ...(parsedInput.metadata ?? {}),
      } as JsonValue,
    });
  });

export const trackTerminalCommandAction = optionalAuthAction
  .inputSchema(trackTerminalCommandSchema)
  .metadata({ actionName: 'pulse.trackTerminalCommand', category: 'analytics' })
  .action(async ({ parsedInput, ctx }) => {
    const { enqueuePulseEventServer } = await import('../pulse.ts');
    await enqueuePulseEventServer({
      user_id: ctx.userId ?? null,
      content_type: null,
      content_slug: 'contact-terminal',
      interaction_type: 'contact_interact',
      session_id: null,
      metadata: {
        command_id: parsedInput.command_id,
        action_type: parsedInput.action_type,
        success: parsedInput.success,
        ...(parsedInput.error_reason && { error_reason: parsedInput.error_reason }),
        ...(parsedInput.execution_time_ms && { execution_time_ms: parsedInput.execution_time_ms }),
      } as JsonValue,
    });
  });

export const trackTerminalFormSubmissionAction = optionalAuthAction
  .inputSchema(trackTerminalFormSubmissionSchema)
  .metadata({ actionName: 'pulse.trackTerminalFormSubmission', category: 'analytics' })
  .action(async ({ parsedInput, ctx }) => {
    const { enqueuePulseEventServer } = await import('../pulse.ts');
    await enqueuePulseEventServer({
      user_id: ctx.userId ?? null,
      content_type: null,
      content_slug: 'contact-form',
      interaction_type: 'contact_submit',
      session_id: null,
      metadata: {
        category: parsedInput.category,
        success: parsedInput.success,
        ...(parsedInput.error && { error: parsedInput.error }),
      } as JsonValue,
    });
  });

export const trackUsageAction = optionalAuthAction
  .inputSchema(trackUsageSchema)
  .metadata({ actionName: 'pulse.trackUsage', category: 'analytics' })
  .action(async ({ parsedInput, ctx }) => {
    const { enqueuePulseEventServer } = await import('../pulse.ts');
    await enqueuePulseEventServer({
      user_id: ctx.userId ?? null,
      content_type: parsedInput.content_type,
      content_slug: parsedInput.content_slug,
      interaction_type: parsedInput.action_type === 'copy' ? 'copy' : 'download',
      session_id: null,
      metadata: {
        action_type: parsedInput.action_type,
      } as JsonValue,
    });
  });

// ============================================
// SPONSORED CONTENT TRACKING
// ============================================
// Moved to pulse-sponsored.ts to avoid phantom module errors

// ============================================
// CONTENT RECOMMENDATIONS
// ============================================

// getSimilarConfigsAction removed - embedding generation system has been deleted
// This action was never used in the UI (getSimilarConfigs function exists but is never called)

export const generateConfigRecommendationsAction = rateLimitedAction
  .inputSchema(generateConfigRecommendationsSchema)
  .metadata({ actionName: 'pulse.generateConfigRecommendations', category: 'analytics' })
  .action(async ({ parsedInput }) => {
    try {
      const { getConfigRecommendations } = await import('../data/tools/recommendations.ts');
      const data = await getConfigRecommendations({
        useCase: parsedInput.useCase,
        experienceLevel: parsedInput.experienceLevel,
        toolPreferences: parsedInput.toolPreferences,
        integrations: parsedInput.integrations ?? [],
        focusAreas: parsedInput.focusAreas ?? [],
      });

      const responseId = `rec_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
      const fallback: RecommendationsPayload = {
        results: [],
        total_matches: 0,
        algorithm: 'unknown',
        summary: {
          top_category: null,
          avg_match_score: 0,
          diversity_score: 0,
        },
      };

      const source = data ?? fallback;

      // Wrap transformation in try-catch
      let normalizedResults: RecommendationItem[];
      try {
        normalizedResults = (source.results ?? []).map((item) => {
          const tags: string[] = Array.isArray(item.tags) ? item.tags : [];
          const reasons = Array.isArray(item.reasons)
            ? (item.reasons as Array<{ type: string; message: string }>)
            : [];
          return {
            slug: item.slug,
            title: item.title,
            description: item.description,
            category: item.category,
            tags,
            author: item.author ?? 'Unknown',
            match_score: item.match_score ?? 0,
            match_percentage: item.match_percentage ?? 0,
            primary_reason: item.primary_reason ?? 'Recommendation',
            rank: item.rank ?? 0,
            reasons,
          };
        });
      } catch (transformError) {
        const normalized = normalizeError(transformError, 'Failed to transform recommendations');
        logger.error(
          {
            err: normalized,
            quizInput: {
              // Grouped quiz input values - better for structured logging
              useCase: parsedInput.useCase,
              experienceLevel: parsedInput.experienceLevel,
            },
          },
          'generateConfigRecommendationsAction: transformation failed'
        );
        normalizedResults = [];
      }

      const payload: RecommendationsPayload = {
        results: normalizedResults,
        total_matches: source.total_matches ?? 0,
        algorithm: source.algorithm ?? 'unknown',
        summary: source.summary ?? {
          top_category: null,
          avg_match_score: 0,
          diversity_score: 0,
        },
      };

      return {
        success: true,
        recommendations: {
          ...payload,
          answers: {
            useCase: parsedInput.useCase,
            experienceLevel: parsedInput.experienceLevel,
            toolPreferences: parsedInput.toolPreferences,
            integrations: parsedInput.integrations ?? [],
            focusAreas: parsedInput.focusAreas ?? [],
          },
          id: responseId,
          generatedAt: new Date().toISOString(),
        },
      };
    } catch (error) {
      // If getConfigRecommendations throws, return error response
      const normalized = normalizeError(error, 'Failed to generate recommendations');
      logger.error({ err: normalized, useCase: parsedInput.useCase,
          experienceLevel: parsedInput.experienceLevel, }, 'generateConfigRecommendationsAction: getConfigRecommendations threw');

      // Return error response instead of throwing (graceful degradation)
      // Match the RecommendationsPayload type structure (snake_case)
      return {
        success: false,
        recommendations: {
          results: null,
          total_matches: 0,
          algorithm: 'unknown',
          summary: {
            top_category: null,
            avg_match_score: 0,
            diversity_score: 0,
          },
          answers: {
            useCase: parsedInput.useCase,
            experienceLevel: parsedInput.experienceLevel,
            toolPreferences: parsedInput.toolPreferences,
            integrations: parsedInput.integrations ?? [],
            focusAreas: parsedInput.focusAreas ?? [],
          },
          id: `error_${Date.now()}`,
          generatedAt: new Date().toISOString(),
        },
      };
    }
  });
