'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import type { ReorderCollectionItemsReturns } from '@heyclaude/database-types/postgres-types';
import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';

const reorderCollectionItemsSchema = z.object({
  collection_id: z.string().uuid(),
  items: z.array(z.any())
});

export const reorderCollectionItems = authedAction
  .metadata({ actionName: 'reorderCollectionItems', category: 'user' })
  .inputSchema(reorderCollectionItemsSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<ReorderCollectionItemsReturns>(
        'reorder_collection_items',
        {
          'p_collection_id': parsedInput.collection_id,
          'p_user_id': ctx.userId,
          'p_items': parsedInput.items
        },
        {
          action: 'reorderCollectionItems.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      const { revalidatePath, revalidateTag } = await import('next/cache');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/account/library`);
      revalidateTag(`collections`, 'default');
      revalidateTag(`users`, 'default');

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('reorderCollectionItems', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
