// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import { logActionFailure } from '../errors';
import type { Database } from '@heyclaude/database-types';
import { revalidatePath, revalidateTag } from 'next/cache';
import { nextInvalidateByKeys } from '../cache-tags';
import { getCacheConfigSnapshot } from '../cache-config';
import { onContactSubmission } from './hooks/contact-hooks.ts';

export const submitContactFormSchema = z.object({
  name: z.string(),
  email: z.string(),
  category: z.enum(['bug', 'feature', 'partnership', 'general', 'other']),
  message: z.string(),
  metadata: z.any()
});
export type SubmitContactFormInput = z.infer<typeof submitContactFormSchema>;

export const submitContactForm = authedAction
  .metadata({ actionName: 'submitContactForm', category: 'form' })
  .inputSchema(submitContactFormSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['insert_contact_submission']['Returns']>(
        'insert_contact_submission',
        {
          'p_name': parsedInput.name,
          'p_email': parsedInput.email,
          'p_category': parsedInput.category,
          'p_message': parsedInput.message,
          'p_metadata': parsedInput.metadata
        },
        {
          action: 'submitContactForm.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = (Array.isArray(rawResult) ? rawResult[0] : rawResult) as Database['public']['Functions']['insert_contact_submission']['Returns'] extends (infer U)[] ? U : Database['public']['Functions']['insert_contact_submission']['Returns'];
      

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/admin/contact-submissions`);
      revalidateTag(`contact-submission-${result?.submission_id}`, 'default');
      
      await nextInvalidateByKeys({
        cacheConfigPromise: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.contact_submission']
      });

      
      const hookResult = await onContactSubmission(result, ctx, parsedInput);
      if (hookResult) {
        return hookResult;
      }
    

      return result;
    } catch (error) {
      throw logActionFailure('submitContactForm', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
