// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import { z } from 'zod';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';
import { logActionFailure } from '../errors';
import type { Database } from '@heyclaude/database-types';
import { revalidatePath, revalidateTag } from 'next/cache';
import { nextInvalidateByKeys } from '../cache-tags';
import { getCacheConfigSnapshot } from '../cache-config';

export const toggleJobStatusSchema = z.object({
  job_id: z.string().uuid(),
  new_status: z.enum(['draft', 'pending_payment', 'pending_review', 'active', 'expired', 'rejected', 'deleted'])
});
export type ToggleJobStatusInput = z.infer<typeof toggleJobStatusSchema>;

export const toggleJobStatus = authedAction
  .metadata({ actionName: 'toggleJobStatus', category: 'content' })
  .inputSchema(toggleJobStatusSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<Database['public']['Functions']['toggle_job_status']['Returns']>(
        'toggle_job_status',
        {
          'p_job_id': parsedInput.job_id,
          'p_user_id': ctx.userId,
          'p_new_status': parsedInput.new_status
        },
        {
          action: 'toggleJobStatus.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/jobs`);
      revalidatePath(`/account/jobs`);
      revalidateTag(`job-${parsedInput.job_id}`, 'default');
      
      await nextInvalidateByKeys({
        cacheConfigPromise: getCacheConfigSnapshot(),
        invalidateKeys: ['cache.invalidate.job_status']
      });

      

      return result;
    } catch (error) {
      throw logActionFailure('toggleJobStatus', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
