'use server';

// -----------------------------------------------------------------------------
// 🔒 AUTO-GENERATED - DO NOT EDIT
// Generated by packages/generators/src/commands/generate-server-actions.ts
// -----------------------------------------------------------------------------

import type { UnlinkOauthProviderReturns } from '@heyclaude/database-types/postgres-types';
import { z } from 'zod';
import { oauth_providerSchema } from '@heyclaude/web-runtime/prisma-zod-schemas';
import { authedAction } from './safe-action';
import { runRpc } from './run-rpc-instance';

const unlinkOAuthProviderSchema = z.object({
  provider: oauth_providerSchema
});

export const unlinkOAuthProvider = authedAction
  .metadata({ actionName: 'unlinkOAuthProvider', category: 'user' })
  .inputSchema(unlinkOAuthProviderSchema)
  .action(async ({ parsedInput, ctx }) => {
    try {
      const rawResult = await runRpc<UnlinkOauthProviderReturns>(
        'unlink_oauth_provider',
        {
          'p_provider': parsedInput.provider
        },
        {
          action: 'unlinkOAuthProvider.rpc',
          userId: ctx.userId,
        }
      );

      
      const result = rawResult;
      
      
      // Lazy import server-only dependencies
      const { revalidatePath, revalidateTag } = await import('next/cache');

      // Simple success check?
      // Some RPCs return void, some return { success: boolean }?
      // We assume implicit success if no error thrown by runRpc.
      
      revalidatePath(`/account/settings`);
      revalidateTag(`users`, 'default');

      

      return result;
    } catch (error) {
      // Lazy import logActionFailure
      const { logActionFailure } = await import('../errors');
      throw logActionFailure('unlinkOAuthProvider', error, {
        userId: ctx.userId,
        input: parsedInput
      });
    }
  });
