# Lefthook Configuration - Claude Pro Directory
# Version: 1.13.0+ (Oct 2025)
# Balance: Protective but not overly strict - maintains development velocity

# ============================================================================
# OUTPUT CONTROL: Modern output configuration (cleaner than deprecated skip_output)
# ============================================================================
output:
  - execution      # Show what's running
  - execution_out  # Show command output
  - skips         # Show skipped commands
  - failure       # Always show failures

# ============================================================================
# PRE-COMMIT: Fast checks on staged files only
# Runs in parallel for speed, fails fast on critical issues
# ============================================================================
pre-commit:
  parallel: true
  follow: true  # Follow symlinks when processing files
  commands:
    # 1. Code Formatting & Linting (auto-fixes when possible)
    lint:
      glob: "*.{ts,tsx,js,jsx,mjs}"
      run: npm run lint
      stage_fixed: true # Auto-stage fixed files
      fail_text: "❌ Linting failed. Run 'npm run format' to auto-fix."

    # 2. Type Safety (fast, catches most issues early)
    type-check:
      glob: "*.{ts,tsx}"
      run: npm run type-check
      fail_text: "❌ TypeScript errors found. Fix them before committing."

    # 3. Content Validation (only when content files change)
    content-validation:
      glob: "content/**/*.json"
      run: npm run validate:content
      fail_text: "❌ Content validation failed. Check your JSON files."

    # 4. SEO Validation (only when MDX content changes)
    seo-validation:
      glob: "content/**/*.mdx"
      run: npm run validate:seo
      fail_text: "❌ SEO validation failed. Fix H1 tags, titles, and descriptions."

    # 5. Run tests ONLY for changed files (smart, not strict)
    # Uses lefthook 1.13+ file filtering for better performance
    test-changed:
      glob: "{src,tests}/**/*.{ts,tsx}"
      exclude: "*.test.{ts,tsx}|*.spec.{ts,tsx}"
      run: |
        # Smart test runner: only tests that correspond to changed files
        CHANGED=$(git diff --cached --name-only --diff-filter=ACMR -- 'src/**/*.{ts,tsx}' 'tests/**/*.{ts,tsx}')

        if [ -z "$CHANGED" ]; then
          echo "ℹ️  No source files changed, skipping tests"
          exit 0
        fi

        # Find related test files efficiently
        TEST_FILES=$(echo "$CHANGED" | while read file; do
          # Map src/ files to tests/
          if [[ $file == src/* ]]; then
            test_file="tests/unit/${file#src/}"
            [ -f "${test_file%.tsx}.test.tsx" ] && echo "${test_file%.tsx}.test.tsx"
            [ -f "${test_file%.ts}.test.ts" ] && echo "${test_file%.ts}.test.ts"
          # If test file itself changed, run it
          elif [[ $file == tests/* ]]; then
            echo "$file"
          fi
        done | sort -u)

        if [ -n "$TEST_FILES" ]; then
          echo "🧪 Running tests for changed files..."
          npm run test:unit -- $TEST_FILES --run --reporter=dot
        else
          echo "⚠️  No tests found for changed files. Consider adding tests."
        fi
      fail_text: "❌ Tests failed. Fix them before committing."

# ============================================================================
# PRE-PUSH: Comprehensive checks before code reaches remote
# Runs sequentially to catch integration issues
# ============================================================================
pre-push:
  parallel: false
  commands:
    # 1. Full test suite with coverage (ensures nothing broke)
    test-suite:
      run: |
        echo "🧪 Running full test suite..."
        npm run test:unit -- --run --reporter=dot
      fail_text: "❌ Test suite failed. Fix failing tests before pushing."

    # 2. Build verification (catches build-time issues)
    build:
      run: |
        echo "🏗️  Verifying production build..."
        npm run build
      fail_text: "❌ Build failed. Fix errors before pushing."

    # 3. Security audit (moderate+ severity only, not overly strict)
    security:
      run: |
        echo "🔒 Running security audit..."
        npm audit --audit-level=moderate --production || true
      fail_text: "⚠️  Security vulnerabilities found (not blocking)."

# ============================================================================
# COMMIT-MSG: Enforce conventional commits (optional but recommended)
# Can be disabled by setting LEFTHOOK_EXCLUDE=commit-msg
# ============================================================================
commit-msg:
  commands:
    conventional-commits:
      use_stdin: true  # Properly receive commit message via stdin
      run: |
        MSG=$(cat {1})

        # Skip merge commits
        if echo "$MSG" | grep -qE "^Merge (branch|pull request)"; then
          exit 0
        fi

        # Skip fixup/squash commits
        if echo "$MSG" | grep -qE "^(fixup|squash)!"; then
          exit 0
        fi

        # Validate conventional commit format (lenient)
        if ! echo "$MSG" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|wip)(\(.+\))?: .{1,}"; then
          echo "⚠️  Commit message doesn't follow Conventional Commits format"
          echo ""
          echo "Format: type(scope): description"
          echo "Types: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|wip"
          echo ""
          echo "Examples:"
          echo "  feat(auth): add Google OAuth"
          echo "  fix(api): resolve race condition"
          echo "  wip: experimenting with new feature"
          echo ""
          echo "💡 Tip: Set LEFTHOOK_EXCLUDE=commit-msg to skip this check"
          exit 1
        fi

# ============================================================================
# POST-MERGE: Auto-install dependencies when package.json changes
# Runs after successful git merge/pull operations
# ============================================================================
post-merge:
  piped: true  # Sequential execution
  commands:
    deps-install:
      files: git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD
      glob: "package*.json"
      run: |
        echo "📦 Dependencies changed. Installing updates..."
        npm install
      fail_text: "⚠️  Dependency installation failed. Run 'npm install' manually."

# ============================================================================
# CONFIGURATION
# ============================================================================
colors: true
no_tty: false  # Allow interactive prompts
min_version: 1.13.0

# ============================================================================
# USAGE TIPS
# ============================================================================
# Skip specific commands:
#   LEFTHOOK_EXCLUDE=test-changed,type-check git commit
#
# Skip all commit-msg validation:
#   LEFTHOOK_EXCLUDE=commit-msg git commit
#
# Verbose output for debugging:
#   LEFTHOOK_VERBOSE=1 git commit
#
# Skip all hooks (use sparingly):
#   git commit --no-verify
# ============================================================================
