/**
 * PostgreSQL Composite Type: announcement_dismissals
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: announcement_dismissals
 */
export type AnnouncementDismissals = {
  /** Attribute: user_id (uuid) */
  user_id: string;
  /** Attribute: announcement_id (text) */
  announcement_id: string;
  /** Attribute: dismissed_at (timestamptz) */
  dismissed_at: string;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for announcement_dismissals composite type
 */
export const announcementDismissalsSchema = z.object({
  /** Attribute: user_id */
  user_id: z.string().uuid(),
  /** Attribute: announcement_id */
  announcement_id: z.string(),
  /** Attribute: dismissed_at */
  dismissed_at: z.string(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type AnnouncementDismissalsFromZod = z.infer<typeof announcementDismissalsSchema>;
