/**
 * PostgreSQL Composite Type: command_installation_paths
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: command_installation_paths
 */
export type CommandInstallationPaths = {
  /** Attribute: project_commands (text, nullable) */
  project_commands: string | null;
  /** Attribute: personal_commands (text, nullable) */
  personal_commands: string | null;
};

/**
 * Zod schema for command_installation_paths composite type
 */
export const commandInstallationPathsSchema = z.object({
  /** Attribute: project_commands */
  project_commands: z.string().nullable(),
  /** Attribute: personal_commands */
  personal_commands: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type CommandInstallationPathsFromZod = z.infer<typeof commandInstallationPathsSchema>;
