/**
 * PostgreSQL Composite Type: community_directory_user
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: community_directory_user
 */
export type CommunityDirectoryUser = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: name (text, nullable) */
  name: string | null;
  /** Attribute: image (text, nullable) */
  image: string | null;
  /** Attribute: bio (text, nullable) */
  bio: string | null;
  /** Attribute: work (text, nullable) */
  work: string | null;
  /** Attribute: tier (user_tier, nullable) */
  tier: 'free' | 'pro' | 'enterprise' | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
};

/**
 * Zod schema for community_directory_user composite type
 */
export const communityDirectoryUserSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: name */
  name: z.string().nullable(),
  /** Attribute: image */
  image: z.string().nullable(),
  /** Attribute: bio */
  bio: z.string().nullable(),
  /** Attribute: work */
  work: z.string().nullable(),
  /** Attribute: tier */
  tier: z.enum(['free', 'pro', 'enterprise']).nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type CommunityDirectoryUserFromZod = z.infer<typeof communityDirectoryUserSchema>;
