/**
 * PostgreSQL Composite Type: company_profile_job_item
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: company_profile_job_item
 */
export type CompanyProfileJobItem = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: title (text, nullable) */
  title: string | null;
  /** Attribute: company (text, nullable) */
  company: string | null;
  /** Attribute: company_logo (text, nullable) */
  company_logo: string | null;
  /** Attribute: location (text, nullable) */
  location: string | null;
  /** Attribute: description (text, nullable) */
  description: string | null;
  /** Attribute: salary (text, nullable) */
  salary: string | null;
  /** Attribute: remote (bool, nullable) */
  remote: boolean | null;
  /** Attribute: type (job_type, nullable) */
  type: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship' | null;
  /** Attribute: workplace (workplace_type, nullable) */
  workplace: 'Remote' | 'On site' | 'Hybrid' | null;
  /** Attribute: experience (experience_level, nullable) */
  experience: 'beginner' | 'intermediate' | 'advanced' | null;
  /** Attribute: category (job_category, nullable) */
  category: 'engineering' | 'design' | 'product' | 'marketing' | 'sales' | 'support' | 'research' | 'data' | 'operations' | 'leadership' | 'consulting' | 'education' | 'other' | null;
  /** Attribute: tags (_text, nullable) */
  tags: string[] | null;
  /** Attribute: plan (job_plan, nullable) */
  plan: 'one-time' | 'subscription' | null;
  /** Attribute: tier (job_tier, nullable) */
  tier: 'standard' | 'featured' | null;
  /** Attribute: posted_at (timestamptz, nullable) */
  posted_at: string | null;
  /** Attribute: expires_at (timestamptz, nullable) */
  expires_at: string | null;
  /** Attribute: view_count (int4, nullable) */
  view_count: number | null;
  /** Attribute: click_count (int4, nullable) */
  click_count: number | null;
  /** Attribute: link (text, nullable) */
  link: string | null;
};

/**
 * Zod schema for company_profile_job_item composite type
 */
export const companyProfileJobItemSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: title */
  title: z.string().nullable(),
  /** Attribute: company */
  company: z.string().nullable(),
  /** Attribute: company_logo */
  company_logo: z.string().nullable(),
  /** Attribute: location */
  location: z.string().nullable(),
  /** Attribute: description */
  description: z.string().nullable(),
  /** Attribute: salary */
  salary: z.string().nullable(),
  /** Attribute: remote */
  remote: z.boolean().nullable(),
  /** Attribute: type */
  type: z.enum(['full-time', 'part-time', 'contract', 'freelance', 'internship']).nullable(),
  /** Attribute: workplace */
  workplace: z.enum(['Remote', 'On site', 'Hybrid']).nullable(),
  /** Attribute: experience */
  experience: z.enum(['beginner', 'intermediate', 'advanced']).nullable(),
  /** Attribute: category */
  category: z.enum(['engineering', 'design', 'product', 'marketing', 'sales', 'support', 'research', 'data', 'operations', 'leadership', 'consulting', 'education', 'other']).nullable(),
  /** Attribute: tags */
  tags: z.array(z.string()).nullable(),
  /** Attribute: plan */
  plan: z.enum(['one-time', 'subscription']).nullable(),
  /** Attribute: tier */
  tier: z.enum(['standard', 'featured']).nullable(),
  /** Attribute: posted_at */
  posted_at: z.string().nullable(),
  /** Attribute: expires_at */
  expires_at: z.string().nullable(),
  /** Attribute: view_count */
  view_count: z.number().nullable(),
  /** Attribute: click_count */
  click_count: z.number().nullable(),
  /** Attribute: link */
  link: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type CompanyProfileJobItemFromZod = z.infer<typeof companyProfileJobItemSchema>;
