/**
 * PostgreSQL Composite Type: content_similarities
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: content_similarities
 */
export type ContentSimilarities = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: content_a_slug (text) */
  content_a_slug: string;
  /** Attribute: content_b_slug (text) */
  content_b_slug: string;
  /** Attribute: similarity_score (numeric) */
  similarity_score: number;
  /** Attribute: similarity_factors (jsonb, nullable) */
  similarity_factors: Record<string, unknown> | null;
  /** Attribute: calculated_at (timestamptz) */
  calculated_at: string;
  /** Attribute: content_a_type (content_category, nullable) */
  content_a_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
  /** Attribute: content_b_type (content_category, nullable) */
  content_b_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
};

/**
 * Zod schema for content_similarities composite type
 */
export const contentSimilaritiesSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: content_a_slug */
  content_a_slug: z.string(),
  /** Attribute: content_b_slug */
  content_b_slug: z.string(),
  /** Attribute: similarity_score */
  similarity_score: z.number(),
  /** Attribute: similarity_factors */
  similarity_factors: z.any().nullable(),
  /** Attribute: calculated_at */
  calculated_at: z.string(),
  /** Attribute: content_a_type */
  content_a_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
  /** Attribute: content_b_type */
  content_b_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ContentSimilaritiesFromZod = z.infer<typeof contentSimilaritiesSchema>;
