/**
 * PostgreSQL Composite Type: contact_submissions
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: contact_submissions
 */
export type ContactSubmissions = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: name (text) */
  name: string;
  /** Attribute: email (text) */
  email: string;
  /** Attribute: category (contact_category) */
  category: 'bug' | 'feature' | 'partnership' | 'general' | 'other';
  /** Attribute: message (text) */
  message: string;
  /** Attribute: status (submission_status) */
  status: 'pending' | 'approved' | 'rejected' | 'spam' | 'merged';
  /** Attribute: user_id (uuid, nullable) */
  user_id: string | null;
  /** Attribute: session_id (text, nullable) */
  session_id: string | null;
  /** Attribute: metadata (jsonb, nullable) */
  metadata: Record<string, unknown> | null;
  /** Attribute: response_sent_at (timestamptz, nullable) */
  response_sent_at: string | null;
  /** Attribute: responded_by (uuid, nullable) */
  responded_by: string | null;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for contact_submissions composite type
 */
export const contactSubmissionsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: name */
  name: z.string(),
  /** Attribute: email */
  email: z.string(),
  /** Attribute: category */
  category: z.enum(['bug', 'feature', 'partnership', 'general', 'other']),
  /** Attribute: message */
  message: z.string(),
  /** Attribute: status */
  status: z.enum(['pending', 'approved', 'rejected', 'spam', 'merged']),
  /** Attribute: user_id */
  user_id: z.string().uuid().nullable(),
  /** Attribute: session_id */
  session_id: z.string().nullable(),
  /** Attribute: metadata */
  metadata: z.any().nullable(),
  /** Attribute: response_sent_at */
  response_sent_at: z.string().nullable(),
  /** Attribute: responded_by */
  responded_by: z.string().uuid().nullable(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ContactSubmissionsFromZod = z.infer<typeof contactSubmissionsSchema>;
