/**
 * PostgreSQL Composite Type: contact_commands
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: contact_commands
 */
export type ContactCommands = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: command_id (text) */
  command_id: string;
  /** Attribute: command_text (text) */
  command_text: string;
  /** Attribute: description (text, nullable) */
  description: string | null;
  /** Attribute: category (contact_command_category) */
  category: 'hidden' | 'info' | 'social' | 'support' | 'utility';
  /** Attribute: icon_name (contact_command_icon, nullable) */
  icon_name: 'Bug' | 'Clock' | 'HelpCircle' | 'Lightbulb' | 'Mail' | 'MessageSquare' | 'Sparkles' | 'Trash' | null;
  /** Attribute: display_order (int4) */
  display_order: number;
  /** Attribute: requires_auth (bool, nullable) */
  requires_auth: boolean | null;
  /** Attribute: is_active (bool, nullable) */
  is_active: boolean | null;
  /** Attribute: action_type (contact_action_type) */
  action_type: 'internal' | 'external' | 'route' | 'sheet' | 'easter-egg';
  /** Attribute: action_value (text, nullable) */
  action_value: string | null;
  /** Attribute: confetti_variant (confetti_variant, nullable) */
  confetti_variant: 'success' | 'celebration' | 'milestone' | 'subtle' | null;
  /** Attribute: aliases (_text, nullable) */
  aliases: string[] | null;
  /** Attribute: metadata (jsonb, nullable) */
  metadata: Record<string, unknown> | null;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for contact_commands composite type
 */
export const contactCommandsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: command_id */
  command_id: z.string(),
  /** Attribute: command_text */
  command_text: z.string(),
  /** Attribute: description */
  description: z.string().nullable(),
  /** Attribute: category */
  category: z.enum(['hidden', 'info', 'social', 'support', 'utility']),
  /** Attribute: icon_name */
  icon_name: z.enum(['Bug', 'Clock', 'HelpCircle', 'Lightbulb', 'Mail', 'MessageSquare', 'Sparkles', 'Trash']).nullable(),
  /** Attribute: display_order */
  display_order: z.number(),
  /** Attribute: requires_auth */
  requires_auth: z.boolean().nullable(),
  /** Attribute: is_active */
  is_active: z.boolean().nullable(),
  /** Attribute: action_type */
  action_type: z.enum(['internal', 'external', 'route', 'sheet', 'easter-egg']),
  /** Attribute: action_value */
  action_value: z.string().nullable(),
  /** Attribute: confetti_variant */
  confetti_variant: z.enum(['success', 'celebration', 'milestone', 'subtle']).nullable(),
  /** Attribute: aliases */
  aliases: z.array(z.string()).nullable(),
  /** Attribute: metadata */
  metadata: z.any().nullable(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ContactCommandsFromZod = z.infer<typeof contactCommandsSchema>;
