/**
 * PostgreSQL Composite Type: content_paginated_item
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: content_paginated_item
 */
export type ContentPaginatedItem = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: title (text, nullable) */
  title: string | null;
  /** Attribute: display_title (text, nullable) */
  display_title: string | null;
  /** Attribute: seo_title (text, nullable) */
  seo_title: string | null;
  /** Attribute: description (text, nullable) */
  description: string | null;
  /** Attribute: author (text, nullable) */
  author: string | null;
  /** Attribute: author_profile_url (text, nullable) */
  author_profile_url: string | null;
  /** Attribute: category (text, nullable) */
  category: string | null;
  /** Attribute: tags (_text, nullable) */
  tags: string[] | null;
  /** Attribute: source_table (text, nullable) */
  source_table: string | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
  /** Attribute: updated_at (timestamptz, nullable) */
  updated_at: string | null;
  /** Attribute: date_added (date, nullable) */
  date_added: string | null;
  /** Attribute: features (_text, nullable) */
  features: string[] | null;
  /** Attribute: use_cases (_text, nullable) */
  use_cases: string[] | null;
  /** Attribute: source (text, nullable) */
  source: string | null;
  /** Attribute: documentation_url (text, nullable) */
  documentation_url: string | null;
  /** Attribute: view_count (int4, nullable) */
  view_count: number | null;
  /** Attribute: copy_count (int4, nullable) */
  copy_count: number | null;
  /** Attribute: bookmark_count (int4, nullable) */
  bookmark_count: number | null;
  /** Attribute: popularity_score (numeric, nullable) */
  popularity_score: number | null;
  /** Attribute: trending_score (int4, nullable) */
  trending_score: number | null;
  /** Attribute: sponsored_content_id (uuid, nullable) */
  sponsored_content_id: string | null;
  /** Attribute: sponsorship_tier (text, nullable) */
  sponsorship_tier: string | null;
  /** Attribute: is_sponsored (bool, nullable) */
  is_sponsored: boolean | null;
};

/**
 * Zod schema for content_paginated_item composite type
 */
export const contentPaginatedItemSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: title */
  title: z.string().nullable(),
  /** Attribute: display_title */
  display_title: z.string().nullable(),
  /** Attribute: seo_title */
  seo_title: z.string().nullable(),
  /** Attribute: description */
  description: z.string().nullable(),
  /** Attribute: author */
  author: z.string().nullable(),
  /** Attribute: author_profile_url */
  author_profile_url: z.string().nullable(),
  /** Attribute: category */
  category: z.string().nullable(),
  /** Attribute: tags */
  tags: z.array(z.string()).nullable(),
  /** Attribute: source_table */
  source_table: z.string().nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
  /** Attribute: updated_at */
  updated_at: z.string().nullable(),
  /** Attribute: date_added */
  date_added: z.string().nullable(),
  /** Attribute: features */
  features: z.array(z.string()).nullable(),
  /** Attribute: use_cases */
  use_cases: z.array(z.string()).nullable(),
  /** Attribute: source */
  source: z.string().nullable(),
  /** Attribute: documentation_url */
  documentation_url: z.string().nullable(),
  /** Attribute: view_count */
  view_count: z.number().nullable(),
  /** Attribute: copy_count */
  copy_count: z.number().nullable(),
  /** Attribute: bookmark_count */
  bookmark_count: z.number().nullable(),
  /** Attribute: popularity_score */
  popularity_score: z.number().nullable(),
  /** Attribute: trending_score */
  trending_score: z.number().nullable(),
  /** Attribute: sponsored_content_id */
  sponsored_content_id: z.string().uuid().nullable(),
  /** Attribute: sponsorship_tier */
  sponsorship_tier: z.string().nullable(),
  /** Attribute: is_sponsored */
  is_sponsored: z.boolean().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ContentPaginatedItemFromZod = z.infer<typeof contentPaginatedItemSchema>;
