/**
 * PostgreSQL Composite Type: email_blocklist
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: email_blocklist
 */
export type EmailBlocklist = {
  /** Attribute: email (text) */
  email: string;
  /** Attribute: reason (email_blocklist_reason) */
  reason: 'spam_complaint' | 'hard_bounce' | 'repeated_soft_bounce' | 'manual';
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: notes (text, nullable) */
  notes: string | null;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for email_blocklist composite type
 */
export const emailBlocklistSchema = z.object({
  /** Attribute: email */
  email: z.string(),
  /** Attribute: reason */
  reason: z.enum(['spam_complaint', 'hard_bounce', 'repeated_soft_bounce', 'manual']),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: notes */
  notes: z.string().nullable(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type EmailBlocklistFromZod = z.infer<typeof emailBlocklistSchema>;
