/**
 * PostgreSQL Composite Type: followers
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: followers
 */
export type Followers = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: follower_id (uuid) */
  follower_id: string;
  /** Attribute: following_id (uuid) */
  following_id: string;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for followers composite type
 */
export const followersSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: follower_id */
  follower_id: z.string().uuid(),
  /** Attribute: following_id */
  following_id: z.string().uuid(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type FollowersFromZod = z.infer<typeof followersSchema>;
