/**
 * PostgreSQL Composite Type: form_field_configs
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: form_field_configs
 */
export type FormFieldConfigs = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: form_type (text) */
  form_type: string;
  /** Attribute: field_group (text) */
  field_group: string;
  /** Attribute: display_order (int4) */
  display_order: number;
  /** Attribute: field_name (text) */
  field_name: string;
  /** Attribute: field_label (text) */
  field_label: string;
  /** Attribute: field_type (form_field_type) */
  field_type: 'text' | 'textarea' | 'number' | 'select';
  /** Attribute: required (bool) */
  required: boolean;
  /** Attribute: placeholder (text, nullable) */
  placeholder: string | null;
  /** Attribute: help_text (text, nullable) */
  help_text: string | null;
  /** Attribute: default_value (text, nullable) */
  default_value: string | null;
  /** Attribute: grid_column (form_grid_column) */
  grid_column: 'full' | 'half' | 'third' | 'two-thirds';
  /** Attribute: icon_name (form_field_icon, nullable) */
  icon_name: 'Github' | null;
  /** Attribute: icon_position (form_icon_position, nullable) */
  icon_position: 'left' | 'right' | null;
  /** Attribute: config (jsonb, nullable) */
  config: Record<string, unknown> | null;
  /** Attribute: enabled (bool) */
  enabled: boolean;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for form_field_configs composite type
 */
export const formFieldConfigsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: form_type */
  form_type: z.string(),
  /** Attribute: field_group */
  field_group: z.string(),
  /** Attribute: display_order */
  display_order: z.number(),
  /** Attribute: field_name */
  field_name: z.string(),
  /** Attribute: field_label */
  field_label: z.string(),
  /** Attribute: field_type */
  field_type: z.enum(['text', 'textarea', 'number', 'select']),
  /** Attribute: required */
  required: z.boolean(),
  /** Attribute: placeholder */
  placeholder: z.string().nullable(),
  /** Attribute: help_text */
  help_text: z.string().nullable(),
  /** Attribute: default_value */
  default_value: z.string().nullable(),
  /** Attribute: grid_column */
  grid_column: z.enum(['full', 'half', 'third', 'two-thirds']),
  /** Attribute: icon_name */
  icon_name: z.enum(['Github']).nullable(),
  /** Attribute: icon_position */
  icon_position: z.enum(['left', 'right']).nullable(),
  /** Attribute: config */
  config: z.any().nullable(),
  /** Attribute: enabled */
  enabled: z.boolean(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type FormFieldConfigsFromZod = z.infer<typeof formFieldConfigsSchema>;
