/**
 * PostgreSQL Composite Type: job_billing_summary
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: job_billing_summary
 */
export type JobBillingSummary = {
  /** Attribute: job_id (uuid, nullable) */
  job_id: string | null;
  /** Attribute: plan (job_plan, nullable) */
  plan: 'one-time' | 'subscription' | null;
  /** Attribute: tier (job_tier, nullable) */
  tier: 'standard' | 'featured' | null;
  /** Attribute: price_cents (int4, nullable) */
  price_cents: number | null;
  /** Attribute: is_subscription (bool, nullable) */
  is_subscription: boolean | null;
  /** Attribute: billing_cycle_days (int4, nullable) */
  billing_cycle_days: number | null;
  /** Attribute: job_expiry_days (int4, nullable) */
  job_expiry_days: number | null;
  /** Attribute: last_payment_status (payment_transaction_status, nullable) */
  last_payment_status: 'pending' | 'completed' | 'failed' | 'refunded' | null;
  /** Attribute: last_payment_amount (int4, nullable) */
  last_payment_amount: number | null;
  /** Attribute: last_payment_at (timestamptz, nullable) */
  last_payment_at: string | null;
  /** Attribute: subscription_status (subscription_status, nullable) */
  subscription_status: 'active' | 'cancelled' | 'past_due' | 'paused' | 'revoked' | null;
  /** Attribute: subscription_renews_at (timestamptz, nullable) */
  subscription_renews_at: string | null;
};

/**
 * Zod schema for job_billing_summary composite type
 */
export const jobBillingSummarySchema = z.object({
  /** Attribute: job_id */
  job_id: z.string().uuid().nullable(),
  /** Attribute: plan */
  plan: z.enum(['one-time', 'subscription']).nullable(),
  /** Attribute: tier */
  tier: z.enum(['standard', 'featured']).nullable(),
  /** Attribute: price_cents */
  price_cents: z.number().nullable(),
  /** Attribute: is_subscription */
  is_subscription: z.boolean().nullable(),
  /** Attribute: billing_cycle_days */
  billing_cycle_days: z.number().nullable(),
  /** Attribute: job_expiry_days */
  job_expiry_days: z.number().nullable(),
  /** Attribute: last_payment_status */
  last_payment_status: z.enum(['pending', 'completed', 'failed', 'refunded']).nullable(),
  /** Attribute: last_payment_amount */
  last_payment_amount: z.number().nullable(),
  /** Attribute: last_payment_at */
  last_payment_at: z.string().nullable(),
  /** Attribute: subscription_status */
  subscription_status: z.enum(['active', 'cancelled', 'past_due', 'paused', 'revoked']).nullable(),
  /** Attribute: subscription_renews_at */
  subscription_renews_at: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type JobBillingSummaryFromZod = z.infer<typeof jobBillingSummarySchema>;
