/**
 * PostgreSQL Composite Type: newsletter_subscriptions
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: newsletter_subscriptions
 */
export type NewsletterSubscriptions = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: email (text) */
  email: string;
  /** Attribute: referrer (text, nullable) */
  referrer: string | null;
  /** Attribute: copy_type (copy_type, nullable) */
  copy_type: 'llmstxt' | 'markdown' | 'code' | 'link' | null;
  /** Attribute: copy_category (content_category, nullable) */
  copy_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
  /** Attribute: copy_slug (text, nullable) */
  copy_slug: string | null;
  /** Attribute: status (newsletter_subscription_status) */
  status: 'active' | 'unsubscribed' | 'bounced' | 'complained';
  /** Attribute: confirmed (bool, nullable) */
  confirmed: boolean | null;
  /** Attribute: confirmation_token (text, nullable) */
  confirmation_token: string | null;
  /** Attribute: confirmed_at (timestamptz, nullable) */
  confirmed_at: string | null;
  /** Attribute: ip_address (inet, nullable) */
  ip_address: string | null;
  /** Attribute: user_agent (text, nullable) */
  user_agent: string | null;
  /** Attribute: consent_given (bool, nullable) */
  consent_given: boolean | null;
  /** Attribute: subscribed_at (timestamptz, nullable) */
  subscribed_at: string | null;
  /** Attribute: unsubscribed_at (timestamptz, nullable) */
  unsubscribed_at: string | null;
  /** Attribute: last_email_sent_at (timestamptz, nullable) */
  last_email_sent_at: string | null;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
  /** Attribute: source (newsletter_source, nullable) */
  source: 'footer' | 'homepage' | 'modal' | 'content_page' | 'inline' | 'post_copy' | 'resend_import' | 'oauth_signup' | null;
  /** Attribute: resend_contact_id (text, nullable) */
  resend_contact_id: string | null;
  /** Attribute: last_sync_at (timestamptz, nullable) */
  last_sync_at: string | null;
  /** Attribute: sync_error (text, nullable) */
  sync_error: string | null;
  /** Attribute: engagement_score (int4, nullable) */
  engagement_score: number | null;
  /** Attribute: primary_interest (newsletter_interest, nullable) */
  primary_interest: 'general' | 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
  /** Attribute: categories_visited (_text, nullable) */
  categories_visited: string[] | null;
  /** Attribute: total_copies (int4, nullable) */
  total_copies: number | null;
  /** Attribute: last_active_at (timestamptz, nullable) */
  last_active_at: string | null;
  /** Attribute: preferred_email_frequency (email_frequency, nullable) */
  preferred_email_frequency: 'weekly' | 'biweekly' | 'monthly' | 'paused' | null;
  /** Attribute: resend_topics (_text, nullable) */
  resend_topics: string[] | null;
  /** Attribute: sync_status (newsletter_sync_status) */
  sync_status: 'pending' | 'synced' | 'failed' | 'skipped';
};

/**
 * Zod schema for newsletter_subscriptions composite type
 */
export const newsletterSubscriptionsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: email */
  email: z.string(),
  /** Attribute: referrer */
  referrer: z.string().nullable(),
  /** Attribute: copy_type */
  copy_type: z.enum(['llmstxt', 'markdown', 'code', 'link']).nullable(),
  /** Attribute: copy_category */
  copy_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
  /** Attribute: copy_slug */
  copy_slug: z.string().nullable(),
  /** Attribute: status */
  status: z.enum(['active', 'unsubscribed', 'bounced', 'complained']),
  /** Attribute: confirmed */
  confirmed: z.boolean().nullable(),
  /** Attribute: confirmation_token */
  confirmation_token: z.string().nullable(),
  /** Attribute: confirmed_at */
  confirmed_at: z.string().nullable(),
  /** Attribute: ip_address */
  ip_address: z.any().nullable(),
  /** Attribute: user_agent */
  user_agent: z.string().nullable(),
  /** Attribute: consent_given */
  consent_given: z.boolean().nullable(),
  /** Attribute: subscribed_at */
  subscribed_at: z.string().nullable(),
  /** Attribute: unsubscribed_at */
  unsubscribed_at: z.string().nullable(),
  /** Attribute: last_email_sent_at */
  last_email_sent_at: z.string().nullable(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
  /** Attribute: source */
  source: z.enum(['footer', 'homepage', 'modal', 'content_page', 'inline', 'post_copy', 'resend_import', 'oauth_signup']).nullable(),
  /** Attribute: resend_contact_id */
  resend_contact_id: z.string().nullable(),
  /** Attribute: last_sync_at */
  last_sync_at: z.string().nullable(),
  /** Attribute: sync_error */
  sync_error: z.string().nullable(),
  /** Attribute: engagement_score */
  engagement_score: z.number().nullable(),
  /** Attribute: primary_interest */
  primary_interest: z.enum(['general', 'agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
  /** Attribute: categories_visited */
  categories_visited: z.array(z.string()).nullable(),
  /** Attribute: total_copies */
  total_copies: z.number().nullable(),
  /** Attribute: last_active_at */
  last_active_at: z.string().nullable(),
  /** Attribute: preferred_email_frequency */
  preferred_email_frequency: z.enum(['weekly', 'biweekly', 'monthly', 'paused']).nullable(),
  /** Attribute: resend_topics */
  resend_topics: z.array(z.string()).nullable(),
  /** Attribute: sync_status */
  sync_status: z.enum(['pending', 'synced', 'failed', 'skipped']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type NewsletterSubscriptionsFromZod = z.infer<typeof newsletterSubscriptionsSchema>;
