/**
 * PostgreSQL Composite Type: review_rating_distribution
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: review_rating_distribution
 */
export type ReviewRatingDistribution = {
  /** Attribute: rating_1 (int4, nullable) */
  rating_1: number | null;
  /** Attribute: rating_2 (int4, nullable) */
  rating_2: number | null;
  /** Attribute: rating_3 (int4, nullable) */
  rating_3: number | null;
  /** Attribute: rating_4 (int4, nullable) */
  rating_4: number | null;
  /** Attribute: rating_5 (int4, nullable) */
  rating_5: number | null;
};

/**
 * Zod schema for review_rating_distribution composite type
 */
export const reviewRatingDistributionSchema = z.object({
  /** Attribute: rating_1 */
  rating_1: z.number().nullable(),
  /** Attribute: rating_2 */
  rating_2: z.number().nullable(),
  /** Attribute: rating_3 */
  rating_3: z.number().nullable(),
  /** Attribute: rating_4 */
  rating_4: z.number().nullable(),
  /** Attribute: rating_5 */
  rating_5: z.number().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ReviewRatingDistributionFromZod = z.infer<typeof reviewRatingDistributionSchema>;
