/**
 * PostgreSQL Composite Type: seo_metadata
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { SeoMetadataDebug } from './seo_metadata_debug';
import { seoMetadataDebugSchema } from './seo_metadata_debug';
import type { SeoMetadataRobots } from './seo_metadata_robots';
import { seoMetadataRobotsSchema } from './seo_metadata_robots';

/**
 * PostgreSQL composite type: seo_metadata
 */
export type SeoMetadata = {
  /** Attribute: title (text, nullable) */
  title: string | null;
  /** Attribute: description (text, nullable) */
  description: string | null;
  /** Attribute: keywords (_text, nullable) */
  keywords: string[] | null;
  /** Attribute: open_graph_type (open_graph_type, nullable) */
  open_graph_type: 'profile' | 'website' | null;
  /** Attribute: twitter_card (twitter_card_type, nullable) */
  twitter_card: 'summary_large_image' | 'summary' | 'app' | 'player' | null;
  /** Attribute: robots (seo_metadata_robots, nullable) */
  robots: SeoMetadataRobots | null;
  /** Attribute: debug (seo_metadata_debug, nullable) */
  debug: SeoMetadataDebug | null;
};

/**
 * Zod schema for seo_metadata composite type
 */
export const seoMetadataSchema = z.object({
  /** Attribute: title */
  title: z.string().nullable(),
  /** Attribute: description */
  description: z.string().nullable(),
  /** Attribute: keywords */
  keywords: z.array(z.string()).nullable(),
  /** Attribute: open_graph_type */
  open_graph_type: z.enum(['profile', 'website']).nullable(),
  /** Attribute: twitter_card */
  twitter_card: z.enum(['summary_large_image', 'summary', 'app', 'player']).nullable(),
  /** Attribute: robots */
  robots: seoMetadataRobotsSchema.nullable(),
  /** Attribute: debug */
  debug: seoMetadataDebugSchema.nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SeoMetadataFromZod = z.infer<typeof seoMetadataSchema>;
