/**
 * PostgreSQL Composite Type: sponsored_content
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: sponsored_content
 */
export type SponsoredContent = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: user_id (uuid) */
  user_id: string;
  /** Attribute: content_type (content_category) */
  content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Attribute: content_id (uuid) */
  content_id: string;
  /** Attribute: active (bool, nullable) */
  active: boolean | null;
  /** Attribute: start_date (timestamptz) */
  start_date: string;
  /** Attribute: end_date (timestamptz) */
  end_date: string;
  /** Attribute: impression_limit (int4, nullable) */
  impression_limit: number | null;
  /** Attribute: impression_count (int4, nullable) */
  impression_count: number | null;
  /** Attribute: click_count (int4, nullable) */
  click_count: number | null;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
  /** Attribute: tier (sponsorship_tier) */
  tier: 'featured' | 'promoted' | 'spotlight' | 'sponsored';
};

/**
 * Zod schema for sponsored_content composite type
 */
export const sponsoredContentSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: user_id */
  user_id: z.string().uuid(),
  /** Attribute: content_type */
  content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Attribute: content_id */
  content_id: z.string().uuid(),
  /** Attribute: active */
  active: z.boolean().nullable(),
  /** Attribute: start_date */
  start_date: z.string(),
  /** Attribute: end_date */
  end_date: z.string(),
  /** Attribute: impression_limit */
  impression_limit: z.number().nullable(),
  /** Attribute: impression_count */
  impression_count: z.number().nullable(),
  /** Attribute: click_count */
  click_count: z.number().nullable(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
  /** Attribute: tier */
  tier: z.enum(['featured', 'promoted', 'spotlight', 'sponsored']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SponsoredContentFromZod = z.infer<typeof sponsoredContentSchema>;
