/**
 * PostgreSQL Composite Type: structured_data_schema_types
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: structured_data_schema_types
 */
export type StructuredDataSchemaTypes = {
  /** Attribute: application (bool, nullable) */
  application: boolean | null;
  /** Attribute: source_code (bool, nullable) */
  source_code: boolean | null;
  /** Attribute: how_to (bool, nullable) */
  how_to: boolean | null;
  /** Attribute: creative_work (bool, nullable) */
  creative_work: boolean | null;
  /** Attribute: faq (bool, nullable) */
  faq: boolean | null;
  /** Attribute: breadcrumb (bool, nullable) */
  breadcrumb: boolean | null;
  /** Attribute: speakable (bool, nullable) */
  speakable: boolean | null;
  /** Attribute: review (bool, nullable) */
  review: boolean | null;
  /** Attribute: aggregate_rating (bool, nullable) */
  aggregate_rating: boolean | null;
  /** Attribute: video_object (bool, nullable) */
  video_object: boolean | null;
  /** Attribute: course (bool, nullable) */
  course: boolean | null;
  /** Attribute: job_posting (bool, nullable) */
  job_posting: boolean | null;
  /** Attribute: collection_page (bool, nullable) */
  collection_page: boolean | null;
  /** Attribute: learning_resource (bool, nullable) */
  learning_resource: boolean | null;
  /** Attribute: item_list (bool, nullable) */
  item_list: boolean | null;
};

/**
 * Zod schema for structured_data_schema_types composite type
 */
export const structuredDataSchemaTypesSchema = z.object({
  /** Attribute: application */
  application: z.boolean().nullable(),
  /** Attribute: source_code */
  source_code: z.boolean().nullable(),
  /** Attribute: how_to */
  how_to: z.boolean().nullable(),
  /** Attribute: creative_work */
  creative_work: z.boolean().nullable(),
  /** Attribute: faq */
  faq: z.boolean().nullable(),
  /** Attribute: breadcrumb */
  breadcrumb: z.boolean().nullable(),
  /** Attribute: speakable */
  speakable: z.boolean().nullable(),
  /** Attribute: review */
  review: z.boolean().nullable(),
  /** Attribute: aggregate_rating */
  aggregate_rating: z.boolean().nullable(),
  /** Attribute: video_object */
  video_object: z.boolean().nullable(),
  /** Attribute: course */
  course: z.boolean().nullable(),
  /** Attribute: job_posting */
  job_posting: z.boolean().nullable(),
  /** Attribute: collection_page */
  collection_page: z.boolean().nullable(),
  /** Attribute: learning_resource */
  learning_resource: z.boolean().nullable(),
  /** Attribute: item_list */
  item_list: z.boolean().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type StructuredDataSchemaTypesFromZod = z.infer<typeof structuredDataSchemaTypesSchema>;
