/**
 * PostgreSQL Composite Type: submission_dashboard_stats
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: submission_dashboard_stats
 */
export type SubmissionDashboardStats = {
  /** Attribute: total (int4, nullable) */
  total: number | null;
  /** Attribute: pending (int4, nullable) */
  pending: number | null;
  /** Attribute: merged_this_week (int4, nullable) */
  merged_this_week: number | null;
};

/**
 * Zod schema for submission_dashboard_stats composite type
 */
export const submissionDashboardStatsSchema = z.object({
  /** Attribute: total */
  total: z.number().nullable(),
  /** Attribute: pending */
  pending: z.number().nullable(),
  /** Attribute: merged_this_week */
  merged_this_week: z.number().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SubmissionDashboardStatsFromZod = z.infer<typeof submissionDashboardStatsSchema>;
