/**
 * PostgreSQL Composite Type: submission_dashboard_recent_item
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { SubmissionDashboardRecentUser } from './submission_dashboard_recent_user';
import { submissionDashboardRecentUserSchema } from './submission_dashboard_recent_user';

/**
 * PostgreSQL composite type: submission_dashboard_recent_item
 */
export type SubmissionDashboardRecentItem = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: content_name (text, nullable) */
  content_name: string | null;
  /** Attribute: content_type (submission_type, nullable) */
  content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | null;
  /** Attribute: merged_at (timestamptz, nullable) */
  merged_at: string | null;
  /** Attribute: user (submission_dashboard_recent_user, nullable) */
  user: SubmissionDashboardRecentUser;
};

/**
 * Zod schema for submission_dashboard_recent_item composite type
 */
export const submissionDashboardRecentItemSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: content_name */
  content_name: z.string().nullable(),
  /** Attribute: content_type */
  content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills']).nullable(),
  /** Attribute: merged_at */
  merged_at: z.string().nullable(),
  /** Attribute: user */
  user: submissionDashboardRecentUserSchema.nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SubmissionDashboardRecentItemFromZod = z.infer<typeof submissionDashboardRecentItemSchema>;
