/**
 * PostgreSQL Composite Type: trending_metrics_cache
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: trending_metrics_cache
 */
export type TrendingMetricsCache = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: category (content_category, nullable) */
  category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
  /** Attribute: title (text, nullable) */
  title: string | null;
  /** Attribute: description (text, nullable) */
  description: string | null;
  /** Attribute: author (text, nullable) */
  author: string | null;
  /** Attribute: tags (_text, nullable) */
  tags: string[] | null;
  /** Attribute: source (content_source, nullable) */
  source: 'claudepro' | 'community' | 'official' | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
  /** Attribute: date_added (date, nullable) */
  date_added: string | null;
  /** Attribute: views_total (int4, nullable) */
  views_total: number | null;
  /** Attribute: copies_total (int4, nullable) */
  copies_total: number | null;
  /** Attribute: bookmarks_total (int4, nullable) */
  bookmarks_total: number | null;
  /** Attribute: review_count (int4, nullable) */
  review_count: number | null;
  /** Attribute: views_7d (int4, nullable) */
  views_7d: number | null;
  /** Attribute: copies_7d (int4, nullable) */
  copies_7d: number | null;
  /** Attribute: bookmarks_7d (int4, nullable) */
  bookmarks_7d: number | null;
  /** Attribute: views_30d (int4, nullable) */
  views_30d: number | null;
  /** Attribute: copies_30d (int4, nullable) */
  copies_30d: number | null;
  /** Attribute: bookmarks_30d (int4, nullable) */
  bookmarks_30d: number | null;
  /** Attribute: velocity_7d (numeric, nullable) */
  velocity_7d: number | null;
  /** Attribute: popularity_score (int4, nullable) */
  popularity_score: number | null;
  /** Attribute: all_time_popularity_score (int4, nullable) */
  all_time_popularity_score: number | null;
  /** Attribute: trending_score (numeric, nullable) */
  trending_score: number | null;
  /** Attribute: engagement_score (int4, nullable) */
  engagement_score: number | null;
  /** Attribute: freshness_score (int4, nullable) */
  freshness_score: number | null;
};

/**
 * Zod schema for trending_metrics_cache composite type
 */
export const trendingMetricsCacheSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: category */
  category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
  /** Attribute: title */
  title: z.string().nullable(),
  /** Attribute: description */
  description: z.string().nullable(),
  /** Attribute: author */
  author: z.string().nullable(),
  /** Attribute: tags */
  tags: z.array(z.string()).nullable(),
  /** Attribute: source */
  source: z.enum(['claudepro', 'community', 'official']).nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
  /** Attribute: date_added */
  date_added: z.string().nullable(),
  /** Attribute: views_total */
  views_total: z.number().nullable(),
  /** Attribute: copies_total */
  copies_total: z.number().nullable(),
  /** Attribute: bookmarks_total */
  bookmarks_total: z.number().nullable(),
  /** Attribute: review_count */
  review_count: z.number().nullable(),
  /** Attribute: views_7d */
  views_7d: z.number().nullable(),
  /** Attribute: copies_7d */
  copies_7d: z.number().nullable(),
  /** Attribute: bookmarks_7d */
  bookmarks_7d: z.number().nullable(),
  /** Attribute: views_30d */
  views_30d: z.number().nullable(),
  /** Attribute: copies_30d */
  copies_30d: z.number().nullable(),
  /** Attribute: bookmarks_30d */
  bookmarks_30d: z.number().nullable(),
  /** Attribute: velocity_7d */
  velocity_7d: z.number().nullable(),
  /** Attribute: popularity_score */
  popularity_score: z.number().nullable(),
  /** Attribute: all_time_popularity_score */
  all_time_popularity_score: z.number().nullable(),
  /** Attribute: trending_score */
  trending_score: z.number().nullable(),
  /** Attribute: engagement_score */
  engagement_score: z.number().nullable(),
  /** Attribute: freshness_score */
  freshness_score: z.number().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type TrendingMetricsCacheFromZod = z.infer<typeof trendingMetricsCacheSchema>;
