/**
 * PostgreSQL Composite Type: user_dashboard_submission
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: user_dashboard_submission
 */
export type UserDashboardSubmission = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: user_id (uuid, nullable) */
  user_id: string | null;
  /** Attribute: content_type (text, nullable) */
  content_type: string | null;
  /** Attribute: content_slug (text, nullable) */
  content_slug: string | null;
  /** Attribute: content_name (text, nullable) */
  content_name: string | null;
  /** Attribute: pr_number (text, nullable) */
  pr_number: string | null;
  /** Attribute: pr_url (text, nullable) */
  pr_url: string | null;
  /** Attribute: branch_name (text, nullable) */
  branch_name: string | null;
  /** Attribute: status (text, nullable) */
  status: string | null;
  /** Attribute: submission_data (jsonb, nullable) */
  submission_data: Record<string, unknown> | null;
  /** Attribute: rejection_reason (text, nullable) */
  rejection_reason: string | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
  /** Attribute: updated_at (timestamptz, nullable) */
  updated_at: string | null;
  /** Attribute: merged_at (timestamptz, nullable) */
  merged_at: string | null;
};

/**
 * Zod schema for user_dashboard_submission composite type
 */
export const userDashboardSubmissionSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: user_id */
  user_id: z.string().uuid().nullable(),
  /** Attribute: content_type */
  content_type: z.string().nullable(),
  /** Attribute: content_slug */
  content_slug: z.string().nullable(),
  /** Attribute: content_name */
  content_name: z.string().nullable(),
  /** Attribute: pr_number */
  pr_number: z.string().nullable(),
  /** Attribute: pr_url */
  pr_url: z.string().nullable(),
  /** Attribute: branch_name */
  branch_name: z.string().nullable(),
  /** Attribute: status */
  status: z.string().nullable(),
  /** Attribute: submission_data */
  submission_data: z.any().nullable(),
  /** Attribute: rejection_reason */
  rejection_reason: z.string().nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
  /** Attribute: updated_at */
  updated_at: z.string().nullable(),
  /** Attribute: merged_at */
  merged_at: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UserDashboardSubmissionFromZod = z.infer<typeof userDashboardSubmissionSchema>;
