/**
 * PostgreSQL Composite Type: user_profile_profile
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { UserProfileCompany } from './user_profile_company';
import { userProfileCompanySchema } from './user_profile_company';

/**
 * PostgreSQL composite type: user_profile_profile
 */
export type UserProfileProfile = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: name (text, nullable) */
  name: string | null;
  /** Attribute: image (text, nullable) */
  image: string | null;
  /** Attribute: bio (text, nullable) */
  bio: string | null;
  /** Attribute: website (text, nullable) */
  website: string | null;
  /** Attribute: tier (user_tier, nullable) */
  tier: 'free' | 'pro' | 'enterprise' | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
  /** Attribute: company (user_profile_company, nullable) */
  company: UserProfileCompany;
};

/**
 * Zod schema for user_profile_profile composite type
 */
export const userProfileProfileSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: name */
  name: z.string().nullable(),
  /** Attribute: image */
  image: z.string().nullable(),
  /** Attribute: bio */
  bio: z.string().nullable(),
  /** Attribute: website */
  website: z.string().nullable(),
  /** Attribute: tier */
  tier: z.enum(['free', 'pro', 'enterprise']).nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
  /** Attribute: company */
  company: userProfileCompanySchema.nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UserProfileProfileFromZod = z.infer<typeof userProfileProfileSchema>;
