/**
 * PostgreSQL Composite Type: user_settings_user_data
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: user_settings_user_data
 */
export type UserSettingsUserData = {
  /** Attribute: slug (text, nullable) */
  slug: string | null;
  /** Attribute: name (text, nullable) */
  name: string | null;
  /** Attribute: image (text, nullable) */
  image: string | null;
  /** Attribute: tier (user_tier, nullable) */
  tier: 'free' | 'pro' | 'enterprise' | null;
};

/**
 * Zod schema for user_settings_user_data composite type
 */
export const userSettingsUserDataSchema = z.object({
  /** Attribute: slug */
  slug: z.string().nullable(),
  /** Attribute: name */
  name: z.string().nullable(),
  /** Attribute: image */
  image: z.string().nullable(),
  /** Attribute: tier */
  tier: z.enum(['free', 'pro', 'enterprise']).nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UserSettingsUserDataFromZod = z.infer<typeof userSettingsUserDataSchema>;
