/**
 * PostgreSQL Composite Type: user_companies_stats
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: user_companies_stats
 */
export type UserCompaniesStats = {
  /** Attribute: total_jobs (int4, nullable) */
  total_jobs: number | null;
  /** Attribute: active_jobs (int4, nullable) */
  active_jobs: number | null;
  /** Attribute: total_views (int4, nullable) */
  total_views: number | null;
  /** Attribute: total_clicks (int4, nullable) */
  total_clicks: number | null;
  /** Attribute: latest_job_posted_at (timestamptz, nullable) */
  latest_job_posted_at: string | null;
};

/**
 * Zod schema for user_companies_stats composite type
 */
export const userCompaniesStatsSchema = z.object({
  /** Attribute: total_jobs */
  total_jobs: z.number().nullable(),
  /** Attribute: active_jobs */
  active_jobs: z.number().nullable(),
  /** Attribute: total_views */
  total_views: z.number().nullable(),
  /** Attribute: total_clicks */
  total_clicks: z.number().nullable(),
  /** Attribute: latest_job_posted_at */
  latest_job_posted_at: z.string().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UserCompaniesStatsFromZod = z.infer<typeof userCompaniesStatsSchema>;
