/**
 * PostgreSQL Composite Type: user_mcps
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: user_mcps
 */
export type UserMcps = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: user_id (uuid) */
  user_id: string;
  /** Attribute: company_id (uuid, nullable) */
  company_id: string | null;
  /** Attribute: slug (text) */
  slug: string;
  /** Attribute: name (text) */
  name: string;
  /** Attribute: description (text) */
  description: string;
  /** Attribute: logo (text, nullable) */
  logo: string | null;
  /** Attribute: link (text) */
  link: string;
  /** Attribute: mcp_link (text, nullable) */
  mcp_link: string | null;
  /** Attribute: plan (text) */
  plan: string;
  /** Attribute: active (bool, nullable) */
  active: boolean | null;
  /** Attribute: order (int4, nullable) */
  order: number | null;
  /** Attribute: view_count (int4, nullable) */
  view_count: number | null;
  /** Attribute: click_count (int4, nullable) */
  click_count: number | null;
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for user_mcps composite type
 */
export const userMcpsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: user_id */
  user_id: z.string().uuid(),
  /** Attribute: company_id */
  company_id: z.string().uuid().nullable(),
  /** Attribute: slug */
  slug: z.string(),
  /** Attribute: name */
  name: z.string(),
  /** Attribute: description */
  description: z.string(),
  /** Attribute: logo */
  logo: z.string().nullable(),
  /** Attribute: link */
  link: z.string(),
  /** Attribute: mcp_link */
  mcp_link: z.string().nullable(),
  /** Attribute: plan */
  plan: z.string(),
  /** Attribute: active */
  active: z.boolean().nullable(),
  /** Attribute: order */
  order: z.number().nullable(),
  /** Attribute: view_count */
  view_count: z.number().nullable(),
  /** Attribute: click_count */
  click_count: z.number().nullable(),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UserMcpsFromZod = z.infer<typeof userMcpsSchema>;
