/**
 * PostgreSQL Composite Type: webhook_events
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: webhook_events
 */
export type WebhookEvents = {
  /** Attribute: id (uuid) */
  id: string;
  /** Attribute: type (webhook_event_type) */
  type: 'changelog_announcement' | 'changelog_notification' | 'content_announcement_create' | 'content_announcement_update' | 'deployment.succeeded' | 'email.bounced' | 'email.clicked' | 'email.delivery_delayed' | 'job_deleted' | 'job_expired' | 'job_notification_create' | 'job_notification_update' | 'job_status_change' | 'job_submission_new' | 'jobs_expired' | 'submission_notification' | 'submission_notification_update' | 'email.complained' | 'content_announcement' | 'error_notification' | 'order.paid' | 'order.refunded' | 'subscription.canceled' | 'subscription.renewal' | 'subscription.revoked';
  /** Attribute: created_at (timestamptz) */
  created_at: string;
  /** Attribute: data (jsonb) */
  data: Record<string, unknown>;
  /** Attribute: processed (bool, nullable) */
  processed: boolean | null;
  /** Attribute: processed_at (timestamptz, nullable) */
  processed_at: string | null;
  /** Attribute: error (text, nullable) */
  error: string | null;
  /** Attribute: retry_count (int4, nullable) */
  retry_count: number | null;
  /** Attribute: next_retry_at (timestamptz, nullable) */
  next_retry_at: string | null;
  /** Attribute: received_at (timestamptz, nullable) */
  received_at: string | null;
  /** Attribute: svix_id (text, nullable) */
  svix_id: string | null;
  /** Attribute: source (webhook_source) */
  source: 'resend' | 'vercel' | 'discord' | 'supabase_db' | 'custom' | 'polar';
  /** Attribute: direction (webhook_direction) */
  direction: 'inbound' | 'outbound';
  /** Attribute: related_id (uuid, nullable) */
  related_id: string | null;
  /** Attribute: http_status_code (int4, nullable) */
  http_status_code: number | null;
  /** Attribute: response_payload (jsonb, nullable) */
  response_payload: Record<string, unknown> | null;
  /** Attribute: attempt_count (int4) */
  attempt_count: number;
  /** Attribute: last_error (text, nullable) */
  last_error: string | null;
  /** Attribute: updated_at (timestamptz) */
  updated_at: string;
};

/**
 * Zod schema for webhook_events composite type
 */
export const webhookEventsSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid(),
  /** Attribute: type */
  type: z.enum(['changelog_announcement', 'changelog_notification', 'content_announcement_create', 'content_announcement_update', 'deployment.succeeded', 'email.bounced', 'email.clicked', 'email.delivery_delayed', 'job_deleted', 'job_expired', 'job_notification_create', 'job_notification_update', 'job_status_change', 'job_submission_new', 'jobs_expired', 'submission_notification', 'submission_notification_update', 'email.complained', 'content_announcement', 'error_notification', 'order.paid', 'order.refunded', 'subscription.canceled', 'subscription.renewal', 'subscription.revoked']),
  /** Attribute: created_at */
  created_at: z.string(),
  /** Attribute: data */
  data: z.any(),
  /** Attribute: processed */
  processed: z.boolean().nullable(),
  /** Attribute: processed_at */
  processed_at: z.string().nullable(),
  /** Attribute: error */
  error: z.string().nullable(),
  /** Attribute: retry_count */
  retry_count: z.number().nullable(),
  /** Attribute: next_retry_at */
  next_retry_at: z.string().nullable(),
  /** Attribute: received_at */
  received_at: z.string().nullable(),
  /** Attribute: svix_id */
  svix_id: z.string().nullable(),
  /** Attribute: source */
  source: z.enum(['resend', 'vercel', 'discord', 'supabase_db', 'custom', 'polar']),
  /** Attribute: direction */
  direction: z.enum(['inbound', 'outbound']),
  /** Attribute: related_id */
  related_id: z.string().uuid().nullable(),
  /** Attribute: http_status_code */
  http_status_code: z.number().nullable(),
  /** Attribute: response_payload */
  response_payload: z.any().nullable(),
  /** Attribute: attempt_count */
  attempt_count: z.number(),
  /** Attribute: last_error */
  last_error: z.string().nullable(),
  /** Attribute: updated_at */
  updated_at: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type WebhookEventsFromZod = z.infer<typeof webhookEventsSchema>;
