/**
 * PostgreSQL Composite Type: webhook_events_backlog
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * PostgreSQL composite type: webhook_events_backlog
 */
export type WebhookEventsBacklog = {
  /** Attribute: id (uuid, nullable) */
  id: string | null;
  /** Attribute: source (webhook_source, nullable) */
  source: 'resend' | 'vercel' | 'discord' | 'supabase_db' | 'custom' | 'polar' | null;
  /** Attribute: type (webhook_event_type, nullable) */
  type: 'changelog_announcement' | 'changelog_notification' | 'content_announcement_create' | 'content_announcement_update' | 'deployment.succeeded' | 'email.bounced' | 'email.clicked' | 'email.delivery_delayed' | 'job_deleted' | 'job_expired' | 'job_notification_create' | 'job_notification_update' | 'job_status_change' | 'job_submission_new' | 'jobs_expired' | 'submission_notification' | 'submission_notification_update' | 'email.complained' | 'content_announcement' | 'error_notification' | 'order.paid' | 'order.refunded' | 'subscription.canceled' | 'subscription.renewal' | 'subscription.revoked' | null;
  /** Attribute: created_at (timestamptz, nullable) */
  created_at: string | null;
  /** Attribute: attempt_count (int4, nullable) */
  attempt_count: number | null;
  /** Attribute: processed (bool, nullable) */
  processed: boolean | null;
  /** Attribute: processed_at (timestamptz, nullable) */
  processed_at: string | null;
  /** Attribute: last_error (text, nullable) */
  last_error: string | null;
  /** Attribute: age (interval, nullable) */
  age: string | null;
  /** Attribute: attempted (bool, nullable) */
  attempted: boolean | null;
};

/**
 * Zod schema for webhook_events_backlog composite type
 */
export const webhookEventsBacklogSchema = z.object({
  /** Attribute: id */
  id: z.string().uuid().nullable(),
  /** Attribute: source */
  source: z.enum(['resend', 'vercel', 'discord', 'supabase_db', 'custom', 'polar']).nullable(),
  /** Attribute: type */
  type: z.enum(['changelog_announcement', 'changelog_notification', 'content_announcement_create', 'content_announcement_update', 'deployment.succeeded', 'email.bounced', 'email.clicked', 'email.delivery_delayed', 'job_deleted', 'job_expired', 'job_notification_create', 'job_notification_update', 'job_status_change', 'job_submission_new', 'jobs_expired', 'submission_notification', 'submission_notification_update', 'email.complained', 'content_announcement', 'error_notification', 'order.paid', 'order.refunded', 'subscription.canceled', 'subscription.renewal', 'subscription.revoked']).nullable(),
  /** Attribute: created_at */
  created_at: z.string().nullable(),
  /** Attribute: attempt_count */
  attempt_count: z.number().nullable(),
  /** Attribute: processed */
  processed: z.boolean().nullable(),
  /** Attribute: processed_at */
  processed_at: z.string().nullable(),
  /** Attribute: last_error */
  last_error: z.string().nullable(),
  /** Attribute: age */
  age: z.any().nullable(),
  /** Attribute: attempted */
  attempted: z.boolean().nullable(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type WebhookEventsBacklogFromZod = z.infer<typeof webhookEventsBacklogSchema>;
