name: Submit Agent
description: Share a Claude agent configuration
title: "[Agent]: "
labels: ["content-submission", "agent", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your agent! Just fill in the basics below. 🤖

        **Need help?** Copy our [simple template](https://github.com/JSONbored/claudepro-directory/blob/main/templates/content/agents-template-simple.json) or [full template](https://github.com/JSONbored/claudepro-directory/blob/main/templates/content/agents-template.json) to get started!

  - type: input
    id: name
    attributes:
      label: Agent Name
      placeholder: e.g., "Code Review Assistant"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What does it do?
      placeholder: Brief description (1-2 sentences)
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration (JSON or Markdown)
      description: Paste your agent configuration here
      render: json
      placeholder: |
        {
          "name": "code-review-assistant",
          "description": "Reviews code for best practices",
          "systemPrompt": "You are an expert code reviewer..."
        }
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags (optional)
      placeholder: e.g., coding, review, productivity

  - type: checkboxes
    id: checks
    attributes:
      label: Quick Check
      options:
        - label: I've tested this and it works
          required: true
        - label: This doesn't contain secrets or sensitive data
          required: true
