/**
 * TEST: Prismocker approach (our custom Prisma mock)
 * 
 * This mock replaces PrismaClient with PrismockerClient for all tests.
 * 
 * IMPORTANT: Jest automatically uses __mocks__ directory (no explicit registration needed).
 * 
 * Prismocker is our custom, standalone Prisma mock that:
 * - Works perfectly with pnpm (no module resolution issues)
 * - Supports all Prisma operations we use
 * - Is type-safe using Prisma's generated types
 * - Is simpler and faster than Prismock
 * 
 * TypeScript types still come from the real @prisma/client module for type checking.
 * 
 * This is the SINGLE mock file for Prisma.
 */

// Import from built dist files
// CRITICAL: Use require to load CommonJS dist file directly
// The dist/index.js file is pre-compiled and doesn't need transformation
// Using CommonJS for Jest compatibility (Jest doesn't fully support ESM in mocks)
const path = require('path');

// Use require() to load pre-compiled CommonJS dist file
// This file is already compiled and doesn't need transformation
const prismockerPath = path.resolve(__dirname, '../../packages/prismocker/dist/index.js');
const prismockerModule = require(prismockerPath);

const createPrismocker = prismockerModule.createPrismocker || prismockerModule.default;

// Create Prisma.Decimal fallback class
// NOTE: We do NOT try to require the real @prisma/client/runtime/library here
// because that would trigger loading the real Prisma client, which requires
// .prisma/client/default to exist (which doesn't in tests).
// Instead, we use a minimal Decimal class that matches Prisma's Decimal API.
class Decimal {
  value: any;
  constructor(value: any) {
    this.value = value;
  }
  toString() {
    return String(this.value);
  }
  toNumber() {
    return Number(this.value);
  }
  toFixed(decimalPlaces?: number) {
    return Number(this.value).toFixed(decimalPlaces);
  }
  toJSON() {
    return this.value;
  }
}
const PrismaDecimal = Decimal;

// Create Prisma namespace with Decimal
// This matches what the real @prisma/client exports
const Prisma = {
  Decimal: PrismaDecimal,
};

// Keep Prisma for export
const PrismaExport = Prisma;

// Export PrismaClient as a function constructor that returns a PrismockerClient instance
// When someone does `new PrismaClient()`, they get a PrismockerClient instance
// This matches the real PrismaClient's usage pattern
// Using a function instead of a class for compatibility
function PrismaClient() {
  const instance = createPrismocker();
  return instance;
}

// module.exports will be at the end of the file, after all enum constants are defined

// Prisma and PrismaExport are now defined above, before module.exports

// Export Prisma enum stubs to prevent Vitest from trying to load the actual @prisma/client module
// These are stub objects that match the structure of Prisma-generated enums
// When code imports `import { job_status } from '@prisma/client'`, Vitest will use these stubs
// instead of trying to load the actual module (which requires .prisma/client/default to exist)
//
// These enums are defined in prisma/schema.prisma and generated by Prisma
// The stub values match the enum keys from the schema
// NOTE: This section is auto-generated by packages/generators/src/scripts/generate-prismocker-enums.ts
// Run `pnpm generate:prismocker-enums` to regenerate after schema changes

const aal_level = {
  aal1: "aal1",
  aal2: "aal2",
  aal3: "aal3",
  schema: "schema",
  auth: "auth",
} as const;

const code_challenge_method = {
  s256: "s256",
  plain: "plain",
  schema: "schema",
  auth: "auth",
} as const;

const factor_status = {
  unverified: "unverified",
  verified: "verified",
  schema: "schema",
  auth: "auth",
} as const;

const factor_type = {
  totp: "totp",
  webauthn: "webauthn",
  phone: "phone",
  schema: "schema",
  auth: "auth",
} as const;

const oauth_authorization_status = {
  pending: "pending",
  approved: "approved",
  denied: "denied",
  expired: "expired",
  schema: "schema",
  auth: "auth",
} as const;

const oauth_client_type = {
  public: "public",
  confidential: "confidential",
  schema: "schema",
  auth: "auth",
} as const;

const oauth_registration_type = {
  dynamic: "dynamic",
  manual: "manual",
  schema: "schema",
  auth: "auth",
} as const;

const oauth_response_type = {
  code: "code",
  schema: "schema",
  auth: "auth",
} as const;

const one_time_token_type = {
  confirmation_token: "confirmation_token",
  reauthentication_token: "reauthentication_token",
  recovery_token: "recovery_token",
  email_change_token_new: "email_change_token_new",
  email_change_token_current: "email_change_token_current",
  phone_change_token: "phone_change_token",
  schema: "schema",
  auth: "auth",
} as const;

const announcement_icon = {
  ArrowUpRight: "ArrowUpRight",
  ArrowRight: "ArrowRight",
  AlertTriangle: "AlertTriangle",
  Calendar: "Calendar",
  BookOpen: "BookOpen",
  Sparkles: "Sparkles",
  schema: "schema",
  public: "public",
} as const;

const announcement_priority = {
  high: "high",
  medium: "medium",
  low: "low",
  schema: "schema",
  public: "public",
} as const;

const announcement_tag = {
  Feature: "Feature",
  New: "New",
  schema: "schema",
  public: "public",
} as const;

const announcement_variant = {
  default: "default",
  outline: "outline",
  secondary: "secondary",
  destructive: "destructive",
  schema: "schema",
  public: "public",
} as const;

const app_setting_category = {
  feature_flag: "feature_flag",
  config: "config",
  secret: "secret",
  experimental: "experimental",
  maintenance: "maintenance",
  schema: "schema",
  public: "public",
} as const;

const category_icon = {
  BookOpen: "BookOpen",
  Briefcase: "Briefcase",
  FileText: "FileText",
  Layers: "Layers",
  Server: "Server",
  Sparkles: "Sparkles",
  Terminal: "Terminal",
  Webhook: "Webhook",
  schema: "schema",
  public: "public",
} as const;

const changelog_category = {
  Added: "Added",
  Changed: "Changed",
  Fixed: "Fixed",
  Security: "Security",
  Deprecated: "Deprecated",
  Removed: "Removed",
  schema: "schema",
  public: "public",
} as const;

const changelog_source = {
  manual: "manual",
  jsonbored: "jsonbored",
  automation: "automation",
  schema: "schema",
  public: "public",
} as const;

const company_size = {
  just_me: "just_me",
  two_to_ten: "2-10",
  eleven_to_fifty: "11-50",
  fifty_one_to_two_hundred: "51-200",
  two_hundred_one_to_five_hundred: "201-500",
  five_hundred_plus: "500+",
  schema: "schema",
  public: "public",
} as const;

const confetti_variant = {
  success: "success",
  celebration: "celebration",
  milestone: "milestone",
  subtle: "subtle",
  schema: "schema",
  public: "public",
} as const;

const config_format = {
  json: "json",
  multi: "multi",
  hook: "hook",
  schema: "schema",
  public: "public",
} as const;

const contact_action_type = {
  internal: "internal",
  external: "external",
  route: "route",
  sheet: "sheet",
  easter_egg: "easter-egg",
  schema: "schema",
  public: "public",
} as const;

const contact_category = {
  bug: "bug",
  feature: "feature",
  partnership: "partnership",
  general: "general",
  other: "other",
  schema: "schema",
  public: "public",
} as const;

const contact_command_category = {
  hidden: "hidden",
  info: "info",
  social: "social",
  support: "support",
  utility: "utility",
  schema: "schema",
  public: "public",
} as const;

const contact_command_icon = {
  Bug: "Bug",
  Clock: "Clock",
  HelpCircle: "HelpCircle",
  Lightbulb: "Lightbulb",
  Mail: "Mail",
  MessageSquare: "MessageSquare",
  Sparkles: "Sparkles",
  Trash: "Trash",
  schema: "schema",
  public: "public",
} as const;

const content_category = {
  agents: "agents",
  mcp: "mcp",
  rules: "rules",
  commands: "commands",
  hooks: "hooks",
  statuslines: "statuslines",
  skills: "skills",
  collections: "collections",
  guides: "guides",
  jobs: "jobs",
  changelog: "changelog",
  schema: "schema",
  public: "public",
} as const;

const content_field_type = {
  installation: "installation",
  use_cases: "use_cases",
  troubleshooting: "troubleshooting",
  requirements: "requirements",
  schema: "schema",
  public: "public",
} as const;

const content_source = {
  claudepro: "claudepro",
  community: "community",
  official: "official",
  schema: "schema",
  public: "public",
} as const;

const copy_type = {
  llmstxt: "llmstxt",
  markdown: "markdown",
  code: "code",
  link: "link",
  schema: "schema",
  public: "public",
} as const;

const crud_action = {
  create: "create",
  update: "update",
  delete: "delete",
  add_item: "add_item",
  remove_item: "remove_item",
  schema: "schema",
  public: "public",
} as const;

const educational_level = {
  Beginner: "Beginner",
  Intermediate: "Intermediate",
  Advanced: "Advanced",
  schema: "schema",
  public: "public",
} as const;

const email_blocklist_reason = {
  spam_complaint: "spam_complaint",
  hard_bounce: "hard_bounce",
  repeated_soft_bounce: "repeated_soft_bounce",
  manual: "manual",
  schema: "schema",
  public: "public",
} as const;

const email_frequency = {
  weekly: "weekly",
  biweekly: "biweekly",
  monthly: "monthly",
  paused: "paused",
  schema: "schema",
  public: "public",
} as const;

const email_sequence_id = {
  onboarding: "onboarding",
  schema: "schema",
  public: "public",
} as const;

const email_sequence_status = {
  active: "active",
  completed: "completed",
  cancelled: "cancelled",
  schema: "schema",
  public: "public",
} as const;

const environment = {
  development: "development",
  preview: "preview",
  production: "production",
  schema: "schema",
  public: "public",
} as const;

const experience_level = {
  beginner: "beginner",
  intermediate: "intermediate",
  advanced: "advanced",
  schema: "schema",
  public: "public",
} as const;

const field_scope = {
  common: "common",
  type_specific: "type_specific",
  tags: "tags",
  schema: "schema",
  public: "public",
} as const;

const field_type = {
  text: "text",
  textarea: "textarea",
  number: "number",
  select: "select",
  schema: "schema",
  public: "public",
} as const;

const focus_area_type = {
  security: "security",
  performance: "performance",
  documentation: "documentation",
  testing: "testing",
  code_quality: "code-quality",
  automation: "automation",
  schema: "schema",
  public: "public",
} as const;

const follow_action = {
  follow: "follow",
  unfollow: "unfollow",
  schema: "schema",
  public: "public",
} as const;

const form_field_icon = {
  Github: "Github",
  schema: "schema",
  public: "public",
} as const;

const form_field_type = {
  text: "text",
  textarea: "textarea",
  number: "number",
  select: "select",
  schema: "schema",
  public: "public",
} as const;

const form_grid_column = {
  full: "full",
  half: "half",
  third: "third",
  two_thirds: "two-thirds",
  schema: "schema",
  public: "public",
} as const;

const form_icon_position = {
  left: "left",
  right: "right",
  schema: "schema",
  public: "public",
} as const;

const generation_source = {
  ai: "ai",
  manual: "manual",
  import: "import",
  migration: "migration",
  schema: "schema",
  public: "public",
} as const;

const grid_column = {
  full: "full",
  half: "half",
  third: "third",
  two_thirds: "two-thirds",
  schema: "schema",
  public: "public",
} as const;

const guide_subcategory = {
  tutorials: "tutorials",
  comparisons: "comparisons",
  workflows: "workflows",
  use_cases: "use-cases",
  troubleshooting: "troubleshooting",
  schema: "schema",
  public: "public",
} as const;

const icon_position = {
  left: "left",
  right: "right",
  schema: "schema",
  public: "public",
} as const;

const integration_type = {
  github: "github",
  database: "database",
  cloud_aws: "cloud-aws",
  cloud_gcp: "cloud-gcp",
  cloud_azure: "cloud-azure",
  communication: "communication",
  none: "none",
  schema: "schema",
  public: "public",
} as const;

const interaction_type = {
  view: "view",
  copy: "copy",
  bookmark: "bookmark",
  click: "click",
  time_spent: "time_spent",
  search: "search",
  filter: "filter",
  screenshot: "screenshot",
  share: "share",
  download: "download",
  pwa_installed: "pwa_installed",
  pwa_launched: "pwa_launched",
  newsletter_subscribe: "newsletter_subscribe",
  contact_interact: "contact_interact",
  contact_submit: "contact_submit",
  form_started: "form_started",
  form_step_completed: "form_step_completed",
  form_field_focused: "form_field_focused",
  form_template_selected: "form_template_selected",
  form_abandoned: "form_abandoned",
  form_submitted: "form_submitted",
  sponsored_impression: "sponsored_impression",
  sponsored_click: "sponsored_click",
  schema: "schema",
  public: "public",
} as const;

const job_category = {
  engineering: "engineering",
  design: "design",
  product: "product",
  marketing: "marketing",
  sales: "sales",
  support: "support",
  research: "research",
  data: "data",
  operations: "operations",
  leadership: "leadership",
  consulting: "consulting",
  education: "education",
  other: "other",
  schema: "schema",
  public: "public",
} as const;

const job_plan = {
  one_time: "one-time",
  subscription: "subscription",
  schema: "schema",
  public: "public",
} as const;

const job_run_status = {
  queued: "queued",
  running: "running",
  retrying: "retrying",
  succeeded: "succeeded",
  failed: "failed",
  cancelled: "cancelled",
  schema: "schema",
  public: "public",
} as const;

const job_status = {
  draft: "draft",
  pending_payment: "pending_payment",
  pending_review: "pending_review",
  active: "active",
  expired: "expired",
  rejected: "rejected",
  deleted: "deleted",
  schema: "schema",
  public: "public",
} as const;

const job_tier = {
  standard: "standard",
  featured: "featured",
  schema: "schema",
  public: "public",
} as const;

const job_type = {
  full_time: "full-time",
  part_time: "part-time",
  contract: "contract",
  freelance: "freelance",
  internship: "internship",
  schema: "schema",
  public: "public",
} as const;

const newsletter_interest = {
  general: "general",
  agents: "agents",
  mcp: "mcp",
  rules: "rules",
  commands: "commands",
  hooks: "hooks",
  statuslines: "statuslines",
  skills: "skills",
  collections: "collections",
  guides: "guides",
  jobs: "jobs",
  changelog: "changelog",
  schema: "schema",
  public: "public",
} as const;

const newsletter_source = {
  footer: "footer",
  homepage: "homepage",
  modal: "modal",
  content_page: "content_page",
  inline: "inline",
  post_copy: "post_copy",
  resend_import: "resend_import",
  oauth_signup: "oauth_signup",
  schema: "schema",
  public: "public",
} as const;

const newsletter_subscription_status = {
  active: "active",
  unsubscribed: "unsubscribed",
  bounced: "bounced",
  complained: "complained",
  schema: "schema",
  public: "public",
} as const;

const newsletter_sync_status = {
  pending: "pending",
  synced: "synced",
  failed: "failed",
  skipped: "skipped",
  schema: "schema",
  public: "public",
} as const;

const notification_priority = {
  high: "high",
  medium: "medium",
  low: "low",
  schema: "schema",
  public: "public",
} as const;

const notification_type = {
  announcement: "announcement",
  feedback: "feedback",
  schema: "schema",
  public: "public",
} as const;

const oauth_provider = {
  discord: "discord",
  github: "github",
  google: "google",
  schema: "schema",
  public: "public",
} as const;

const open_graph_type = {
  profile: "profile",
  website: "website",
  schema: "schema",
  public: "public",
} as const;

const payment_product_type = {
  job_listing: "job_listing",
  mcp_listing: "mcp_listing",
  user_content: "user_content",
  subscription: "subscription",
  premium_membership: "premium_membership",
  schema: "schema",
  public: "public",
} as const;

const payment_transaction_status = {
  pending: "pending",
  completed: "completed",
  failed: "failed",
  refunded: "refunded",
  schema: "schema",
  public: "public",
} as const;

const primary_action_type = {
  notification: "notification",
  copy_command: "copy_command",
  copy_script: "copy_script",
  scroll: "scroll",
  download: "download",
  github_link: "github_link",
  schema: "schema",
  public: "public",
} as const;

const route_group = {
  primary: "primary",
  secondary: "secondary",
  actions: "actions",
  schema: "schema",
  public: "public",
} as const;

const setting_type = {
  boolean: "boolean",
  string: "string",
  number: "number",
  json: "json",
  schema: "schema",
  public: "public",
} as const;

const sort_direction = {
  asc: "asc",
  desc: "desc",
  schema: "schema",
  public: "public",
} as const;

const sort_option = {
  relevance: "relevance",
  date: "date",
  popularity: "popularity",
  name: "name",
  updated: "updated",
  created: "created",
  views: "views",
  trending: "trending",
  schema: "schema",
  public: "public",
} as const;

const sponsorship_tier = {
  featured: "featured",
  promoted: "promoted",
  spotlight: "spotlight",
  sponsored: "sponsored",
  schema: "schema",
  public: "public",
} as const;

const static_route_icon = {
  Activity: "Activity",
  Bookmark: "Bookmark",
  Briefcase: "Briefcase",
  Building2: "Building2",
  Cookie: "Cookie",
  FileText: "FileText",
  Handshake: "Handshake",
  HelpCircle: "HelpCircle",
  Home: "Home",
  Library: "Library",
  Link: "Link",
  Mail: "Mail",
  Plus: "Plus",
  PlusCircle: "PlusCircle",
  Search: "Search",
  Settings: "Settings",
  Shield: "Shield",
  Star: "Star",
  TrendingUp: "TrendingUp",
  User: "User",
  Users: "Users",
  Wand2: "Wand2",
  schema: "schema",
  public: "public",
} as const;

const submission_status = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  spam: "spam",
  merged: "merged",
  schema: "schema",
  public: "public",
} as const;

const submission_type = {
  agents: "agents",
  mcp: "mcp",
  rules: "rules",
  commands: "commands",
  hooks: "hooks",
  statuslines: "statuslines",
  skills: "skills",
  schema: "schema",
  public: "public",
} as const;

const subscription_status = {
  active: "active",
  cancelled: "cancelled",
  past_due: "past_due",
  paused: "paused",
  revoked: "revoked",
  schema: "schema",
  public: "public",
} as const;

const trending_metric = {
  views: "views",
  likes: "likes",
  shares: "shares",
  downloads: "downloads",
  all: "all",
  schema: "schema",
  public: "public",
} as const;

const trending_period = {
  today: "today",
  week: "week",
  month: "month",
  year: "year",
  all: "all",
  schema: "schema",
  public: "public",
} as const;

const twitter_card_type = {
  summary_large_image: "summary_large_image",
  summary: "summary",
  app: "app",
  player: "player",
  schema: "schema",
  public: "public",
} as const;

const use_case_type = {
  code_review: "code-review",
  api_development: "api-development",
  frontend_development: "frontend-development",
  data_science: "data-science",
  content_creation: "content-creation",
  devops_infrastructure: "devops-infrastructure",
  general_development: "general-development",
  testing_qa: "testing-qa",
  security_audit: "security-audit",
  schema: "schema",
  public: "public",
} as const;

const user_role = {
  user: "user",
  admin: "admin",
  moderator: "moderator",
  schema: "schema",
  public: "public",
} as const;

const user_tier = {
  free: "free",
  pro: "pro",
  enterprise: "enterprise",
  schema: "schema",
  public: "public",
} as const;

const webhook_delivery_status = {
  running: "running",
  succeeded: "succeeded",
  failed: "failed",
  schema: "schema",
  public: "public",
} as const;

const webhook_direction = {
  inbound: "inbound",
  outbound: "outbound",
  schema: "schema",
  public: "public",
} as const;

const webhook_event_type = {
  changelog_announcement: "changelog_announcement",
  changelog_notification: "changelog_notification",
  content_announcement_create: "content_announcement_create",
  content_announcement_update: "content_announcement_update",
  deployment_succeeded: "deployment.succeeded",
  email_bounced: "email.bounced",
  email_clicked: "email.clicked",
  email_delivery_delayed: "email.delivery_delayed",
  job_deleted: "job_deleted",
  job_expired: "job_expired",
  job_notification_create: "job_notification_create",
  job_notification_update: "job_notification_update",
  job_status_change: "job_status_change",
  job_submission_new: "job_submission_new",
  jobs_expired: "jobs_expired",
  submission_notification: "submission_notification",
  submission_notification_update: "submission_notification_update",
  email_complained: "email.complained",
  content_announcement: "content_announcement",
  error_notification: "error_notification",
  order_paid: "order.paid",
  order_refunded: "order.refunded",
  subscription_canceled: "subscription.canceled",
  subscription_renewal: "subscription.renewal",
  subscription_revoked: "subscription.revoked",
  schema: "schema",
  public: "public",
} as const;

const webhook_source = {
  resend: "resend",
  vercel: "vercel",
  discord: "discord",
  supabase_db: "supabase_db",
  custom: "custom",
  polar: "polar",
  schema: "schema",
  public: "public",
} as const;

const workplace_type = {
  Remote: "Remote",
  On_site: "On site",
  Hybrid: "Hybrid",
  schema: "schema",
  public: "public",
} as const;

// Export everything at the end, after all constants are defined
module.exports = {
  PrismaClient,
  Prisma: PrismaExport,
  aal_level,
  code_challenge_method,
  factor_status,
  factor_type,
  oauth_authorization_status,
  oauth_client_type,
  oauth_registration_type,
  oauth_response_type,
  one_time_token_type,
  announcement_icon,
  announcement_priority,
  announcement_tag,
  announcement_variant,
  app_setting_category,
  category_icon,
  changelog_category,
  changelog_source,
  company_size,
  confetti_variant,
  config_format,
  contact_action_type,
  contact_category,
  contact_command_category,
  contact_command_icon,
  content_category,
  content_field_type,
  content_source,
  copy_type,
  crud_action,
  educational_level,
  email_blocklist_reason,
  email_frequency,
  email_sequence_id,
  email_sequence_status,
  environment,
  experience_level,
  field_scope,
  field_type,
  focus_area_type,
  follow_action,
  form_field_icon,
  form_field_type,
  form_grid_column,
  form_icon_position,
  generation_source,
  grid_column,
  guide_subcategory,
  icon_position,
  integration_type,
  interaction_type,
  job_category,
  job_plan,
  job_run_status,
  job_status,
  job_tier,
  job_type,
  newsletter_interest,
  newsletter_source,
  newsletter_subscription_status,
  newsletter_sync_status,
  notification_priority,
  notification_type,
  oauth_provider,
  open_graph_type,
  payment_product_type,
  payment_transaction_status,
  primary_action_type,
  route_group,
  setting_type,
  sort_direction,
  sort_option,
  sponsorship_tier,
  static_route_icon,
  submission_status,
  submission_type,
  subscription_status,
  trending_metric,
  trending_period,
  twitter_card_type,
  use_case_type,
  user_role,
  user_tier,
  webhook_delivery_status,
  webhook_direction,
  webhook_event_type,
  webhook_source,
  workplace_type,
};


