/**
 * Database Type Overrides
 *
 * This file contains all database type overrides in a single consolidated location.
 *
 * Structure:
 * - AUTO-GENERATED SECTION: Enums, tables, CHECK constraints, RPC return types
 *   (regenerated by: pnpm generate:db-overrides)
 * - MANUAL SECTION: View overrides, function overrides, application types
 *   (preserved by generator)
 */

// ============================================================================
// AUTO-GENERATED SECTION - DO NOT EDIT MANUALLY
// ============================================================================
// Generated by: pnpm generate:db-overrides
// This section is regenerated automatically. Manual edits will be lost.
// ============================================================================

import type { Database as DatabaseGenerated, Json } from './database.types';

// Helper types (kept for backward compatibility but not used - all ENUMs accessed directly)
// type Enums<T extends keyof DatabaseGenerated['public']['Enums']> =
//   DatabaseGenerated['public']['Enums'][T];

export type Tables<T extends keyof DatabaseGenerated['public']['Tables']> =
  DatabaseGenerated['public']['Tables'][T]['Row'];

// ============================================================================
// Enums, Tables, CHECK Constraints
// ============================================================================

// ============================================================================
// Enum Arrays
// ============================================================================

// All ENUM types should be accessed directly via Database['public']['Enums']['enum_name']
// No convenience aliases - use exact naming for consistency

/**
 * Valid values for announcement_priority enum
 */
export const ANNOUNCEMENT_PRIORITY_VALUES = [
  'high',
  'medium',
  'low',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['announcement_priority'][];

/**
 * Valid values for changelog_category enum
 */
export const CHANGELOG_CATEGORY_VALUES = [
  'Added',
  'Changed',
  'Deprecated',
  'Removed',
  'Fixed',
  'Security',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['changelog_category'][];

/**
 * Valid values for confetti_variant enum
 */
export const CONFETTI_VARIANT_VALUES = [
  'success',
  'celebration',
  'milestone',
  'subtle',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['confetti_variant'][];

/**
 * Valid values for contact_action_type enum
 */
export const CONTACT_ACTION_TYPE_VALUES = [
  'internal',
  'external',
  'route',
  'sheet',
  'easter-egg',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['contact_action_type'][];

/**
 * Valid values for experience_level enum
 */
export const EXPERIENCE_LEVEL_VALUES = [
  'beginner',
  'intermediate',
  'advanced',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['experience_level'][];

/**
 * Valid values for focus_area_type enum
 */
export const FOCUS_AREA_TYPE_VALUES = [
  'security',
  'performance',
  'documentation',
  'testing',
  'code-quality',
  'automation',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['focus_area_type'][];

/**
 * Valid values for guide_subcategory enum
 */
export const GUIDE_SUBCATEGORY_VALUES = [
  'tutorials',
  'comparisons',
  'workflows',
  'use-cases',
  'troubleshooting',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['guide_subcategory'][];

/**
 * Valid values for integration_type enum
 */
export const INTEGRATION_TYPE_VALUES = [
  'github',
  'database',
  'cloud-aws',
  'cloud-gcp',
  'cloud-azure',
  'communication',
  'none',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['integration_type'][];

/**
 * Valid values for interaction_type enum
 */
export const INTERACTION_TYPE_VALUES = [
  'view',
  'copy',
  'bookmark',
  'click',
  'time_spent',
  'search',
  'filter',
  'screenshot',
  'share',
  'download',
  'pwa_installed',
  'pwa_launched',
  'newsletter_subscribe',
  'contact_interact',
  'contact_submit',
  'form_started',
  'form_step_completed',
  'form_field_focused',
  'form_template_selected',
  'form_abandoned',
  'form_submitted',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['interaction_type'][];

/**
 * Valid values for newsletter_source enum
 */
export const NEWSLETTER_SOURCE_VALUES = [
  'footer',
  'homepage',
  'modal',
  'content_page',
  'inline',
  'post_copy',
  'resend_import',
  'oauth_signup',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['newsletter_source'][];

/**
 * Valid values for notification_type enum
 */
export const NOTIFICATION_TYPE_VALUES = [
  'announcement',
  'feedback',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['notification_type'][];

/**
 * Valid values for sort_direction enum
 */
export const SORT_DIRECTION_VALUES = [
  'asc',
  'desc',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['sort_direction'][];

/**
 * Valid values for sort_option enum
 */
export const SORT_OPTION_VALUES = [
  'relevance',
  'date',
  'popularity',
  'name',
  'updated',
  'created',
  'views',
  'trending',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['sort_option'][];

/**
 * Valid values for submission_type enum
 */
export const SUBMISSION_TYPE_VALUES = [
  'agents',
  'mcp',
  'rules',
  'commands',
  'hooks',
  'statuslines',
  'skills',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['submission_type'][];

/**
 * Valid values for trending_metric enum
 */
export const TRENDING_METRIC_VALUES = [
  'views',
  'likes',
  'shares',
  'downloads',
  'all',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['trending_metric'][];

/**
 * Valid values for trending_period enum
 */
export const TRENDING_PERIOD_VALUES = [
  'today',
  'week',
  'month',
  'year',
  'all',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['trending_period'][];

/**
 * Valid values for use_case_type enum
 */
export const USE_CASE_TYPE_VALUES = [
  'code-review',
  'api-development',
  'frontend-development',
  'data-science',
  'content-creation',
  'devops-infrastructure',
  'general-development',
  'testing-qa',
  'security-audit',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['use_case_type'][];

/**
 * Valid values for user_tier enum
 */
export const USER_TIER_VALUES = [
  'free',
  'pro',
  'enterprise',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['user_tier'][];

/**
 * Valid values for webhook_direction enum
 */
export const WEBHOOK_DIRECTION_VALUES = [
  'inbound',
  'outbound',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['webhook_direction'][];

/**
 * Valid values for webhook_source enum
 */
export const WEBHOOK_SOURCE_VALUES = [
  'resend',
  'vercel',
  'discord',
  'supabase_db',
  'custom',
  'polar',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['webhook_source'][];

/**
 * Generic enum validation helper
 */
export function isValidEnum<T extends string>(
  value: unknown,
  validValues: readonly T[]
): value is T {
  return typeof value === 'string' && validValues.includes(value as T);
}

// ============================================================================
// Table Overrides
// ============================================================================

export type DatabaseWithTableOverrides = {
  public: {
    Tables: Omit<
      DatabaseGenerated['public']['Tables'],
      | 'category_configs'
      | 'changelog'
      | 'contact_commands'
      | 'content'
      | 'content_generation_tracking'
      | 'content_submissions'
      | 'metadata_templates'
      | 'newsletter_subscriptions'
      | 'structured_data_config'
      | 'announcements'
      | 'contact_submissions'
      | 'content_templates'
      | 'form_field_configs'
      | 'form_field_definitions'
      | 'jobs'
      | 'notifications'
      | 'tier_display_config'
      | 'user_interactions'
      | 'users'
    > & {
      category_configs: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['category_configs']['Row'],
          'metadata_fields' | 'category'
        > & {
          metadata_fields: string[];
          category: DatabaseGenerated['public']['Enums']['content_category'];
        };
        Insert: DatabaseGenerated['public']['Tables']['category_configs']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['category_configs']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['category_configs']['Relationships'];
      };
      changelog: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['changelog']['Row'],
          'contributors' | 'keywords'
        > & {
          contributors: string[];
          keywords: string[];
        };
        Insert: DatabaseGenerated['public']['Tables']['changelog']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['changelog']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['changelog']['Relationships'];
      };
      contact_commands: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['contact_commands']['Row'],
          'aliases' | 'action_type' | 'confetti_variant'
        > & {
          aliases: string[];
          action_type: DatabaseGenerated['public']['Enums']['contact_action_type'];
          confetti_variant: DatabaseGenerated['public']['Enums']['confetti_variant'];
        };
        Insert: DatabaseGenerated['public']['Tables']['contact_commands']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['contact_commands']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['contact_commands']['Relationships'];
      };
      content: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['content']['Row'],
          'features' | 'tags' | 'use_cases' | 'category'
        > & {
          features: string[];
          tags: string[];
          use_cases: string[];
          category: DatabaseGenerated['public']['Enums']['content_category'];
        };
        Insert: DatabaseGenerated['public']['Tables']['content']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['content']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['content']['Relationships'];
      };
      content_generation_tracking: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['content_generation_tracking']['Row'],
          'validation_errors'
        > & {
          validation_errors: string[];
        };
        Insert: DatabaseGenerated['public']['Tables']['content_generation_tracking']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['content_generation_tracking']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['content_generation_tracking']['Relationships'];
      };
      content_submissions: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['content_submissions']['Row'],
          'spam_reasons' | 'tags' | 'status' | 'submission_type'
        > & {
          spam_reasons: string[];
          tags: string[];
          status: DatabaseGenerated['public']['Enums']['submission_status'];
          submission_type: DatabaseGenerated['public']['Enums']['submission_type'];
        };
        Insert: DatabaseGenerated['public']['Tables']['content_submissions']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['content_submissions']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['content_submissions']['Relationships'];
      };
      metadata_templates: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['metadata_templates']['Row'],
          'default_keywords' | 'title_formulas'
        > & {
          default_keywords: string[];
          title_formulas: string[];
        };
        Insert: DatabaseGenerated['public']['Tables']['metadata_templates']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['metadata_templates']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['metadata_templates']['Relationships'];
      };
      newsletter_subscriptions: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['newsletter_subscriptions']['Row'],
          'categories_visited' | 'resend_topics' | 'source'
        > & {
          categories_visited: string[];
          resend_topics: string[];
          source: DatabaseGenerated['public']['Enums']['newsletter_source'];
        };
        Insert: DatabaseGenerated['public']['Tables']['newsletter_subscriptions']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['newsletter_subscriptions']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['newsletter_subscriptions']['Relationships'];
      };
      structured_data_config: {
        Row: Omit<
          DatabaseGenerated['public']['Tables']['structured_data_config']['Row'],
          'default_keywords' | 'default_requirements'
        > & {
          default_keywords: string[];
          default_requirements: string[];
        };
        Insert: DatabaseGenerated['public']['Tables']['structured_data_config']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['structured_data_config']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['structured_data_config']['Relationships'];
      };
      jobs: {
        Row: DatabaseGenerated['public']['Tables']['jobs']['Row'];
        Insert: DatabaseGenerated['public']['Tables']['jobs']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['jobs']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['jobs']['Relationships'];
      };
      notifications: {
        Row: DatabaseGenerated['public']['Tables']['notifications']['Row'];
        Insert: DatabaseGenerated['public']['Tables']['notifications']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['notifications']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['notifications']['Relationships'];
      };
      tier_display_config: {
        Row: DatabaseGenerated['public']['Tables']['tier_display_config']['Row'];
        Insert: DatabaseGenerated['public']['Tables']['tier_display_config']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['tier_display_config']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['tier_display_config']['Relationships'];
      };
      user_interactions: {
        Row: DatabaseGenerated['public']['Tables']['user_interactions']['Row'];
        Insert: DatabaseGenerated['public']['Tables']['user_interactions']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['user_interactions']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['user_interactions']['Relationships'];
      };
      users: {
        Row: DatabaseGenerated['public']['Tables']['users']['Row'];
        Insert: DatabaseGenerated['public']['Tables']['users']['Insert'];
        Update: DatabaseGenerated['public']['Tables']['users']['Update'];
        Relationships: DatabaseGenerated['public']['Tables']['users']['Relationships'];
      };
    };
  };
};

/**
 * Database type with all overrides applied
 * This is the main Database type that should be used throughout the application
 */
export type Database = DatabaseWithTableOverrides & {
  public: DatabaseWithTableOverrides['public'] & {
    Functions: DatabaseGenerated['public']['Functions'];
    Enums: DatabaseGenerated['public']['Enums'];
  };
};

// ============================================================================
// CHECK Constraints (DEPRECATED - Use Database['public']['Enums'] directly)
// ============================================================================
// These are kept for backward compatibility but should be replaced with
// direct imports from database.types.ts: Database['public']['Enums']['job_category']

/**
 * Valid values for job_category enum
 */
export const JOBCATEGORY_VALUES = [
  'engineering',
  'design',
  'product',
  'marketing',
  'sales',
  'support',
  'research',
  'data',
  'operations',
  'leadership',
  'consulting',
  'education',
  'other',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['job_category'][];

// ============================================================================
// RPC Return Types
// ============================================================================
// IMPORTANT: You can manually edit TODO sections in RPC return types.
// The generator will preserve your manual edits when regenerating.

/**
 * add_bookmark RPC return type
 */
export type AddBookmarkReturn = {
  success: boolean;
  bookmark: {
    id: string;
    user_id: string;
    content_type: DatabaseGenerated['public']['Enums']['content_category'];
    content_slug: string;
    notes: string | null;
    created_at: string;
  };
};

/**
 * approve_submission RPC return type
 * Returns submission approval result with content details
 */
export type ApproveSubmissionReturn = {
  success: boolean;
  submission_id: string;
  content_id: string;
  slug: string;
  category: DatabaseGenerated['public']['Enums']['content_category'];
  message: string;
};

/**
 * batch_add_bookmarks RPC return type
 * Returns batch bookmark addition result
 */
export type BatchAddBookmarksReturn = {
  success: boolean;
  added_count?: number;
  errors?: Array<{ item: unknown; error: string }>;
  error?: string;
};

/**
 * batch_insert_user_interactions RPC return type
 * Returns batch user interaction insertion result
 */
export type BatchInsertUserInteractionsReturn = {
  success: boolean;
  inserted_count?: number;
  error?: string;
};

/**
 * build_aggregate_rating_schema RPC return type
 */
export type BuildAggregateRatingSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'AggregateRating';
  ratingValue: number;
  ratingCount: number;
  reviewCount: number;
  bestRating: 5;
  worstRating: 1;
} | null;

/**
 * build_breadcrumb_json_ld RPC return type
 */
export type BuildBreadcrumbJsonLdReturn = {
  '@context': 'https://schema.org';
  '@type': 'BreadcrumbList';
  itemListElement: Array<{
    '@type': 'ListItem';
    position: number;
    item: {
      '@id': string;
      name: string;
    };
  }>;
};

/**
 * build_changelog_json_ld RPC return type
 * TODO: Define the actual return structure
 */
export type BuildChangelogJsonLdReturn = Json; // TODO: Replace with actual structure

/**
 * build_complete_content_schemas RPC return type
 * TODO: Define the actual return structure
 */
export type BuildCompleteContentSchemasReturn = Json; // TODO: Replace with actual structure

/**
 * build_faq_schema RPC return type
 */
export type BuildFaqSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'FAQPage';
  mainEntity: Array<{
    '@type': 'Question';
    name: string;
    acceptedAnswer: {
      '@type': 'Answer';
      text: string;
    };
  }>;
  url: string;
} | null;

/**
 * build_how_to_schema RPC return type
 */
export type BuildHowToSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'HowTo';
  name: string;
  description: string | null;
  step: Array<{
    '@type': 'HowToStep';
    name: string;
    text: string;
    position: number;
  }>;
  supply: Array<{
    '@type': 'HowToSupply';
    name: string;
  }> | null;
  totalTime: string;
  url: string;
} | null;

/**
 * build_item_list_schema RPC return type
 */
export type BuildItemListSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'ItemList';
  '@id': string;
  name: string;
  description: string | null;
  url: string;
  numberOfItems: number;
  itemListElement: Array<{
    '@type': 'ListItem';
    position: number;
    name: string;
    description: string | null;
    url: string;
  }>;
} | null;

/**
 * build_job_discord_embed RPC return type
 * TODO: Define the actual return structure
 */
export type BuildJobDiscordEmbedReturn = Json; // TODO: Replace with actual structure

/**
 * build_job_posting_schema RPC return type
 * TODO: Define the actual return structure
 */
export type BuildJobPostingSchemaReturn = Json; // TODO: Replace with actual structure

/**
 * build_learning_resource_schema RPC return type
 */
export type BuildLearningResourceSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'LearningResource';
  '@id': string;
  name: string;
  description: string | null;
  url: string;
  author: {
    '@type': 'Organization';
    '@id': string;
    name: string;
  };
  datePublished: string;
  educationalLevel: 'Beginner' | 'Intermediate' | 'Advanced';
  timeRequired: string;
  learningResourceType: 'Guide';
  isAccessibleForFree: true;
  inLanguage: 'en-US';
} | null;

/**
 * build_organization_schema RPC return type
 * TODO: Define the actual return structure
 */
export type BuildOrganizationSchemaReturn = Json; // TODO: Replace with actual structure

/**
 * build_person_schema RPC return type
 * TODO: Define the actual return structure
 */
export type BuildPersonSchemaReturn = Json; // TODO: Replace with actual structure

/**
 * build_software_application_schema RPC return type
 */
export type BuildSoftwareApplicationSchemaReturn = {
  '@context': 'https://schema.org';
  '@type': 'SoftwareApplication';
  name: string;
  applicationCategory: string;
  applicationSubCategory: 'AI Development Tool';
  operatingSystem: 'Cross-platform';
  description: string | null;
  url: string;
  author: {
    '@type': 'Person';
    name: string;
  };
  datePublished: string;
  dateModified: string;
  keywords: string[];
  offers: {
    '@type': 'Offer';
    price: '0';
    priceCurrency: 'USD';
  };
  softwareRequirements: string[];
  isAccessibleForFree: true;
  inLanguage: 'en-US';
} | null;

/**
 * build_source_code_schema RPC return type
 */
export type BuildSourceCodeSchemaReturn = Array<{
  '@context': 'https://schema.org';
  '@type': 'SoftwareSourceCode';
  name: string;
  description: string;
  programmingLanguage: string;
  codeRepository: string;
  text: string;
}> | null;

/**
 * build_static_route_json_ld RPC return type
 * TODO: Define the actual return structure
 */
export type BuildStaticRouteJsonLdReturn = Json; // TODO: Replace with actual structure

/**
 * create_job_with_payment RPC return type
 * Returns job creation with payment result
 */
export type CreateJobWithPaymentReturn = {
  success: boolean;
  job_id: string;
  company_id: string;
  payment_amount: number;
  requires_payment: boolean;
  tier: DatabaseGenerated['public']['Enums']['job_tier'];
  plan: DatabaseGenerated['public']['Enums']['job_plan'];
};

/**
 * delete_company RPC return type
 * Returns company deletion result
 */
export type DeleteCompanyReturn = {
  success: boolean;
  company_id: string;
};

/**
 * delete_job RPC return type
 * Returns job deletion result
 */
export type DeleteJobReturn = {
  success: boolean;
  job_id: string;
  message: string;
};

/**
 * filter_jobs RPC return type
 */
export type GetFilterJobsReturn = {
  jobs: Array<Tables<'jobs'>>;
  total_count: number;
} | null;

/**
 * generate_command_installation RPC return type
 * TODO: Define the actual return structure
 */
export type GenerateCommandInstallationReturn = Json; // TODO: Replace with actual structure

/**
 * generate_content_field RPC return type
 * TODO: Define the actual return structure
 */
export type GenerateContentFieldReturn = Json; // TODO: Replace with actual structure

/**
 * generate_hook_installation RPC return type
 * TODO: Define the actual return structure
 */
export type GenerateHookInstallationReturn = Json; // TODO: Replace with actual structure

/**
 * generate_llms_txt_content RPC return type
 * TODO: Define the actual return structure
 */
export type GenerateLlmsTxtContentReturn = Json; // TODO: Replace with actual structure

/**
 * generate_markdown_export RPC return type
 * TODO: Define the actual return structure
 */
export type GenerateMarkdownExportReturn = Json; // TODO: Replace with actual structure

/**
 * generate_metadata_complete RPC return type
 * Returns SEO metadata and optional JSON-LD schemas based on route pattern
 */
export type GenerateMetadataCompleteReturn =
  | {
      title: string;
      description: string;
      keywords: string[];
      openGraphType: 'profile' | 'website';
      twitterCard: 'summary_large_image';
      robots: {
        index: boolean;
        follow: boolean;
      };
      _debug?: {
        pattern: string;
        route: string;
        category?: string;
        slug?: string;
        error?: string;
      };
    }
  | {
      metadata: {
        title: string;
        description: string;
        keywords: string[];
        openGraphType: 'profile' | 'website';
        twitterCard: 'summary_large_image';
        robots: {
          index: boolean;
          follow: boolean;
        };
        _debug?: {
          pattern: string;
          route: string;
          category?: string;
          slug?: string;
          error?: string;
        };
      };
      schemas: Json[];
    };

/**
 * generate_readme_data RPC return type
 * Returns structured data for README.md generation
 */
export type GenerateReadmeDataReturn = {
  categories: Array<{
    category: DatabaseGenerated['public']['Enums']['content_category'];
    title: string;
    description: string;
    icon_name: string;
    url_slug: string;
    items: Array<{
      slug: string;
      title: string;
      description: string;
    }>;
  }>;
  totalCount: number;
  categoryBreakdown: Record<string, number>;
};

/**
 * get_all_structured_data_configs RPC return type
 */
export type GetGetAllStructuredDataConfigsReturn = Record<
  DatabaseGenerated['public']['Enums']['content_category'],
  {
    schemaTypes: {
      application: boolean;
      sourceCode: boolean;
      howTo: boolean;
      creativeWork: boolean;
      faq: boolean;
      breadcrumb: boolean;
      speakable: boolean;
      review: boolean;
      aggregateRating: boolean;
      videoObject: boolean;
      course: boolean;
      jobPosting: boolean;
      collectionPage: boolean;
    };
    categoryDisplayName: string | null;
    applicationSubCategory: string | null;
    defaultKeywords: string[] | null;
    defaultRequirements: string[] | null;
    creativeWorkDescription: string | null;
  }
>;

/**
 * get_api_health RPC return type
 * TODO: Define the actual return structure
 */
export type GetGetApiHealthReturn = Json; // TODO: Replace with actual structure

/**
 * get_app_settings RPC return type
 * TODO: Define the actual return structure
 */
export type GetGetAppSettingsReturn = Json; // TODO: Replace with actual structure

/**
 * get_category_config RPC return type
 */
export type GetGetCategoryConfigReturn =
  | {
      category: DatabaseGenerated['public']['Enums']['content_category'];
      title: string;
      pluralTitle: string;
      description: string | null;
      iconName: string | null;
      colorScheme: string | null;
      showOnHomepage: boolean;
      keywords: string[] | null;
      metaDescription: string | null;
      sections: Json;
      primaryActionType: string | null;
      primaryActionLabel: string | null;
      primaryActionConfig: Json | null;
      searchPlaceholder: string | null;
      emptyStateMessage: string | null;
      urlSlug: string;
      contentLoader: string | null;
      displayConfig: Json | null;
      configFormat: string | null;
      validationConfig: Json | null;
      generationConfig: Json | null;
      schemaName: string | null;
    }
  | Record<
      string,
      {
        category: DatabaseGenerated['public']['Enums']['content_category'];
        title: string;
        pluralTitle: string;
        description: string | null;
        iconName: string | null;
        colorScheme: string | null;
        showOnHomepage: boolean;
        keywords: string[] | null;
        metaDescription: string | null;
        sections: Json;
        primaryActionType: string | null;
        primaryActionLabel: string | null;
        primaryActionConfig: Json | null;
        searchPlaceholder: string | null;
        emptyStateMessage: string | null;
        urlSlug: string;
        contentLoader: string | null;
        displayConfig: Json | null;
        configFormat: string | null;
        validationConfig: Json | null;
        generationConfig: Json | null;
        schemaName: string | null;
      }
    >;

/**
 * get_changelog_with_category_stats RPC return type
 */
export type GetGetChangelogWithCategoryStatsReturn = {
  entries: Array<{
    id: string;
    slug: string;
    title: string;
    description: string | null;
    tldr: string | null;
    content: string | null;
    raw_content: string | null;
    changes: Json;
    metadata: Json | null;
    release_date: string;
    featured: boolean;
    published: boolean;
    keywords: string[] | null;
    created_at: string;
    updated_at: string;
  }>;
  category_counts: {
    All: number;
    Added: number;
    Changed: number;
    Fixed: number;
    Removed: number;
    Deprecated: number;
    Security: number;
  };
  total: number;
  filtered_count: number;
};

/**
 * get_content_templates RPC return type
 */
export type GetGetContentTemplatesReturn = Array<{
  id: string;
  type: string;
  name: string;
  description: string | null;
  category: DatabaseGenerated['public']['Enums']['content_category'] | null;
  tags: string | null;
  templateData: Json;
  [key: string]: unknown;
}>;

/**
 * get_database_fingerprint RPC return type
 */
export type GetGetDatabaseFingerprintReturn = Record<
  string,
  {
    rows: number;
    inserts: number;
    updates: number;
    deletes: number;
    last_vacuum: string;
  }
>;

/**
 * get_due_sequence_emails RPC return type
 * TODO: Define the actual return structure
 */
export type GetGetDueSequenceEmailsReturn = Json; // TODO: Replace with actual structure

/**
 * get_enriched_content RPC return type
 * TODO: Define the actual return structure
 */
export type GetGetEnrichedContentReturn = Json; // TODO: Replace with actual structure

/**
 * get_form_field_config RPC return type
 */
export type GetGetFormFieldConfigReturn = {
  formType: string;
  fields: Array<{
    name: string;
    label: string;
    type: string;
    required: boolean;
    placeholder: string | null;
    helpText: string | null;
    defaultValue: Json | null;
    gridColumn: string;
    iconName: string | null;
    iconPosition: string;
    config: Json | null;
    fieldGroup: string;
    displayOrder: number;
  }>;
} | null;

/**
 * get_form_fields_grouped RPC return type
 */
export type GetGetFormFieldsGroupedReturn = Record<
  string,
  Array<{
    name: string;
    label: string;
    type: string;
    required: boolean;
    placeholder: string | null;
    helpText: string | null;
    defaultValue: Json | null;
    gridColumn: string;
    iconName: string | null;
    iconPosition: string;
    config: Json | null;
  }>
>;

/**
 * get_generation_config RPC return type
 */
export type GetGetGenerationConfigReturn =
  | {
      category: DatabaseGenerated['public']['Enums']['content_category'];
      validationConfig: Json | null;
      generationConfig: Json | null;
    }
  | Record<
      DatabaseGenerated['public']['Enums']['content_category'],
      {
        validationConfig: Json | null;
        generationConfig: Json | null;
      }
    >;

/**
 * get_homepage_content_enriched RPC return type
 */
export type GetGetHomepageContentEnrichedReturn = {
  categoryData: Record<string, HomepageContentItem[]>;
  stats: Record<string, { total: number; featured: number }>;
  weekStart: string;
};

/**
 * get_performance_baseline RPC return type
 */
export type GetGetPerformanceBaselineReturn = {
  snapshot_time: string;
  database: {
    size_mb: number;
    active_connections: number;
    total_connections: number;
    max_connections: number;
    connection_usage_pct: number;
  };
  cache: {
    hit_ratio_pct: number;
    blocks_read: number;
    blocks_hit: number;
    status: 'EXCELLENT' | 'GOOD' | 'FAIR' | 'POOR';
  };
  indexes: {
    total: number;
    unused: number;
    total_scans: number;
    total_size_mb: number;
  };
  tables: {
    total: number;
    live_tuples: number;
    dead_tuples: number;
    avg_bloat_pct: number;
    total_size_mb: number;
    largest: Array<{
      table: string;
      size_mb: number;
      live_tuples: number;
      dead_tuples: number;
    }>;
  };
  queries: {
    total_tracked: number;
    total_calls: number;
    avg_time_ms: number;
    max_time_ms: number;
    total_time_ms: number;
    slowest: Array<{
      query: string;
      calls: number;
      mean_time_ms: number;
      total_time_ms: number;
    }>;
  };
  health: {
    status: string;
    recommendations: Array<string | null>;
  };
};

/**
 * get_quiz_configuration RPC return type
 */
export type GetGetQuizConfigurationReturn = Array<{
  id: string;
  question: string;
  description: string | null;
  required: boolean;
  displayOrder: number;
  options: Array<{
    value: string;
    label: string;
    description: string | null;
    iconName: string | null;
  }>;
}> | null;

/**
 * get_recent_merged RPC return type
 */
export type GetGetRecentMergedReturn = Array<{
  id: string;
  content_name: string;
  content_type: DatabaseGenerated['public']['Enums']['content_category'];
  merged_at: string;
  merged_at_formatted?: string;
  user: {
    name: string;
    slug: string;
  } | null;
}>;

/**
 * get_sponsorship_analytics RPC return type
 */
export type GetGetSponsorshipAnalyticsReturn = {
  sponsorship: Tables<'sponsored_content'>;
  daily_stats: Array<{
    date: string;
    impressions: number;
    clicks: number;
  }>;
  computed_metrics: {
    ctr: number;
    days_active: number;
    avg_impressions_per_day: number;
  };
} | null;

/**
 * get_structured_data_config RPC return type
 */
export type GetGetStructuredDataConfigReturn = {
  category: DatabaseGenerated['public']['Enums']['content_category'];
  schemaTypes: {
    application: boolean;
    sourceCode: boolean;
    howTo: boolean;
    creativeWork: boolean;
    faq: boolean;
    breadcrumb: boolean;
    speakable: boolean;
    review: boolean;
    aggregateRating: boolean;
    videoObject: boolean;
    course: boolean;
    jobPosting: boolean;
    collectionPage: boolean;
  };
  categoryDisplayName: string | null;
  applicationSubCategory: string | null;
  defaultKeywords: string[] | null;
  defaultRequirements: string[] | null;
  creativeWorkDescription: string | null;
} | null;

/**
 * get_submission_stats RPC return type
 */
export type GetGetSubmissionStatsReturn = {
  total: number;
  pending: number;
  merged_this_week: number;
};

/**
 * get_top_contributors RPC return type
 */
export type GetGetTopContributorsReturn = Array<{
  rank: number;
  name: string;
  slug: string;
  mergedCount: number;
}>;

/**
 * get_weekly_digest RPC return type
 * TODO: Define the actual return structure
 */
export type GetGetWeeklyDigestReturn = Json; // TODO: Replace with actual structure

/**
 * manage_collection RPC return type
 * Returns collection management result
 */
export type ManageCollectionReturn = {
  success: boolean;
  collection_id?: string;
  action?: string;
  error?: string;
};

/**
 * manage_company RPC return type
 * TODO: Define the actual return structure
 */
export type ManageCompanyReturn = Json; // TODO: Replace with actual structure

/**
 * manage_review RPC return type
 * Returns review management result
 */
export type ManageReviewReturn = {
  success: boolean;
  review?: Tables<'review_ratings'>;
  review_id?: string;
  error?: string;
};

/**
 * refresh_profile_from_oauth RPC return type
 * Returns profile refresh result
 */
export type RefreshProfileFromOauthReturn = { success: boolean; updated: boolean; error?: string };

/**
 * reject_submission RPC return type
 * Returns submission rejection result
 */
export type RejectSubmissionReturn = {
  success: boolean;
  submission_id: string;
  status: DatabaseGenerated['public']['Enums']['submission_status'];
};

/**
 * remove_bookmark RPC return type
 * Returns bookmark removal result
 */
export type RemoveBookmarkReturn = { success: boolean; error?: string };

/**
 * reorder_collection_items RPC return type
 * Returns collection item reordering result with success/error details
 */
export type ReorderCollectionItemsReturn =
  | {
      success: true;
      updated: number;
      errors: Array<{
        itemId: string;
        error: string;
      }>;
    }
  | {
      success: false;
      error: string;
      updated: 0;
    };

/**
 * submit_content_for_review RPC return type
 * TODO: Define the actual return structure
 */
export type GetSubmitContentForReviewReturn = Json; // TODO: Replace with actual structure

/**
 * subscribe_newsletter RPC return type
 * Returns newsletter subscription result
 */
export type SubscribeNewsletterReturn = {
  success: boolean;
  subscription_id?: string;
  was_resubscribed?: boolean;
  email: string;
  error?: string;
};

/**
 * toggle_follow RPC return type
 * Returns follow toggle result
 */
export type ToggleFollowReturn = { success: boolean; is_following: boolean; error?: string };

/**
 * toggle_job_status RPC return type
 * Returns job status toggle result
 */
export type ToggleJobStatusReturn = {
  success: boolean;
  job_id: string;
  old_status: DatabaseGenerated['public']['Enums']['job_status'];
  new_status: DatabaseGenerated['public']['Enums']['job_status'];
  message: string;
};

/**
 * toggle_review_helpful RPC return type
 * Returns review helpfulness toggle result
 */
export type ToggleReviewHelpfulReturn = {
  success: boolean;
  helpful: boolean;
  content_type: DatabaseGenerated['public']['Enums']['content_category'];
  content_slug: string;
};

/**
 * track_sponsored_event RPC return type
 * Returns sponsored event tracking result
 */
export type TrackSponsoredEventReturn = {
  success: boolean;
  event_id?: string;
  error?: string;
};

/**
 * track_user_interaction RPC return type
 * TODO: Define the actual return structure
 */
export type TrackUserInteractionReturn = Json; // TODO: Replace with actual structure

/**
 * unlink_oauth_provider RPC return type
 * Returns OAuth provider unlinking result
 */
export type UnlinkOauthProviderReturn = {
  success: boolean;
  message?: string;
  provider: string;
  remaining_providers?: number;
  error?: string;
};

/**
 * update_job RPC return type
 * Returns job update result
 */
export type UpdateJobReturn = {
  success: boolean;
  job_id: string;
  message: string;
};

/**
 * update_user_profile RPC return type
 * Returns user profile update result
 */
export type UpdateUserProfileReturn = { success: boolean; error?: string };

// ============================================================================
// MANUAL SECTION - EDITABLE
// ============================================================================
// View overrides, function overrides, application types
// This section is preserved by the generator.
// ============================================================================

// ============================================================================
// View overrides, function overrides, application types
// This section is preserved by the generator.
// ============================================================================
// ============================================================================
// Application Content Types (derived from RPC returns and database tables)
// ============================================================================

// ============================================================================
// MANUAL SECTION - EDITABLE
// ============================================================================
// View overrides, function overrides, application types
// This section is preserved by the generator.
// ============================================================================

// ============================================================================
// View overrides, function overrides, application types
// This section is preserved by the generator.
// ============================================================================
// ============================================================================
// View overrides, function overrides, application types
// This section is preserved by the generator.
// ============================================================================
// ============================================================================
// Application Content Types (derived from RPC returns and database tables)
// ============================================================================
/**
 * Valid values for job_plan enum
 */
export const JOB_PLAN_VALUES = [
  'one-time',
  'subscription',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['job_plan'][];
/**
 * Valid values for job_tier enum
 */
export const JOB_TIER_VALUES = [
  'standard',
  'featured',
] as const satisfies readonly DatabaseGenerated['public']['Enums']['job_tier'][];
/**
 * Copy Type - type of content being copied
 */
export type CopyType = 'code' | 'link' | 'markdown';
/**
 * Valid values for CopyType
 */
export const COPY_TYPE_VALUES = ['code', 'link', 'markdown'] as const satisfies readonly CopyType[];
/**
 * ContentItem - Base content item type derived from content table and RPC returns
 * Used throughout the application for displaying content items
 */
export type ContentItem = Tables<'content'>;
/**
 * HomepageContentItem - Simplified content item for homepage display
 * From get_homepage_content_enriched RPC
 */
export type HomepageContentItem = {
  slug: string;
  title: string;
  description: string;
  author: string;
  tags: string[];
  source: string;
  created_at: string;
  date_added: string;
  category: DatabaseGenerated['public']['Enums']['content_category'];
  view_count: number;
  copy_count: number;
  featured: boolean;
};
/**
 * JobCardJobType - Job type for job cards (subset of full job table)
 * Used when displaying jobs from RPC returns that don't include all fields
 */
export type JobCardJobType = {
  id: string;
  slug: string;
  title: string;
  company: string;
  company_logo: string | null;
  location: string | null;
  description: string | null;
  salary: string | null;
  remote: boolean;
  type: DatabaseGenerated['public']['Enums']['job_type'] | null;
  workplace: DatabaseGenerated['public']['Enums']['workplace_type'];
  experience: DatabaseGenerated['public']['Enums']['experience_level'];
  category: DatabaseGenerated['public']['Enums']['job_category'] | null;
  tags: string[];
  plan: DatabaseGenerated['public']['Enums']['job_plan'];
  tier: DatabaseGenerated['public']['Enums']['job_tier'] | null;
  posted_at: string;
  expires_at: string;
  view_count: number;
  click_count: number;
  link: string | null;
};
/**
 * ReviewItem - Review rating item from reviews table
 */
export type ReviewItem = Tables<'review_ratings'>;
/**
 * SponsorshipAnalytics - Analytics data for sponsored content
 */
export type SponsorshipAnalytics = GetGetSponsorshipAnalyticsReturn;
/**
 * Helper function to check if value is a valid experience_level enum
 */
export function isExperienceLevel(
  value: unknown
): value is DatabaseGenerated['public']['Enums']['experience_level'] {
  return (
    typeof value === 'string' &&
    EXPERIENCE_LEVEL_VALUES.includes(
      value as DatabaseGenerated['public']['Enums']['experience_level']
    )
  );
}
