#!/usr/bin/env node

/**
 * Generate Prismocker Enum Stubs
 *
 * This script parses the Prisma schema and generates enum stub exports
 * for __mocks__/@prisma/client.ts to support automatic ENUM mocking.
 *
 * Usage:
 *   pnpm tsx packages/generators/src/scripts/generate-prismocker-enums.ts
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

interface EnumDefinition {
  name: string;
  values: Array<{ key: string; value: string }>;
}

/**
 * Parse Prisma schema to extract enum definitions
 * Handles @map() directives to get actual database values
 */
function parsePrismaEnums(schemaContent: string): EnumDefinition[] {
  const enums: EnumDefinition[] = [];
  
  // Match enum blocks: enum name { ... }
  const enumRegex = /enum\s+(\w+)\s*\{([^}]+)\}/g;
  let match;
  
  while ((match = enumRegex.exec(schemaContent)) !== null) {
    const enumName = match[1];
    const enumBody = match[2];
    
    if (!enumName || !enumBody) continue; // Skip if match groups are undefined
    
    // Parse enum values (handles @map() directives)
    const valueRegex = /(\w+)(?:\s+@map\(["']([^"']+)["']\))?/g;
    const values: Array<{ key: string; value: string }> = [];
    let valueMatch: RegExpExecArray | null = null;
    
    while ((valueMatch = valueRegex.exec(enumBody)) !== null) {
      // Capture group 1 is always defined when regex matches (it's the required \w+)
      const key = valueMatch[1]!; // Non-null assertion: regex guarantees this exists
      // Capture group 2 is optional (the @map value)
      const value: string = valueMatch[2] ?? key;
      values.push({ key, value });
    }
    
    if (values.length > 0 && enumName) {
      enums.push({ name: enumName, values });
    }
  }
  
  return enums;
}

/**
 * Generate enum stub export code
 */
function generateEnumStub(enumDef: EnumDefinition): string {
  const entries = enumDef.values
    .map(({ key, value }) => `  ${key}: ${JSON.stringify(value)}`)
    .join(',\n');
  
  return `export const ${enumDef.name} = {\n${entries},\n} as const;`;
}

/**
 * Main function
 */
async function main() {
  const projectRoot = process.cwd();
  const schemaPath = join(projectRoot, 'prisma/schema.prisma');
  const mockPath = join(projectRoot, '__mocks__/@prisma/client.ts');
  
  try {
    // Read Prisma schema
    const schemaContent = await readFile(schemaPath, 'utf-8');
    
    // Parse enums
    const enums = parsePrismaEnums(schemaContent);
    
    console.log(`Found ${enums.length} enums in schema`);
    
    // Read existing mock file
    const mockContent = await readFile(mockPath, 'utf-8');
    
    // Find the section where enums are exported
    // Look for the comment "Export Prisma enum stubs..."
    const enumStartMarker = '// Export Prisma enum stubs to prevent Vitest from trying to load the actual @prisma/client module';
    const enumEndMarker = '// NOTE: If you need additional enums';
    
    const startIndex = mockContent.indexOf(enumStartMarker);
    const endIndex = mockContent.indexOf(enumEndMarker);
    
    if (startIndex === -1 || endIndex === -1) {
      throw new Error('Could not find enum section in mock file');
    }
    
    // Generate enum exports
    const enumExports = enums.map(generateEnumStub).join('\n\n');
    
    // Replace enum section
    const beforeEnums = mockContent.substring(0, startIndex);
    const afterEnums = mockContent.substring(endIndex);
    
    const newMockContent = `${beforeEnums}${enumStartMarker}
// These are stub objects that match the structure of Prisma-generated enums
// When code imports \`import { job_status } from '@prisma/client'\`, Vitest will use these stubs
// instead of trying to load the actual module (which requires .prisma/client/default to exist)
//
// These enums are defined in prisma/schema.prisma and generated by Prisma
// The stub values match the enum keys from the schema
// NOTE: This section is auto-generated by packages/generators/src/scripts/generate-prismocker-enums.ts
// Run \`pnpm generate:prismocker-enums\` to regenerate after schema changes

${enumExports}

${afterEnums}`;
    
    // Write updated mock file
    await writeFile(mockPath, newMockContent, 'utf-8');
    
    console.log(`✅ Generated ${enums.length} enum stubs in __mocks__/@prisma/client.ts`);
    console.log(`   Enums: ${enums.map(e => e.name).join(', ')}`);
  } catch (error) {
    console.error('❌ Error generating enum stubs:', error);
    process.exit(1);
  }
}

main();


