/**
 * Prisma-Generated Zod Schema Re-exports
 *
 * Re-exports commonly used enum Zod schemas from Prisma generator.
 * These schemas are generated by prisma-zod-generator and are located in
 * @prisma/client/zod/schemas/enums/
 *
 * NOTE: Prisma enum objects use keys (snake_case) that map to database values (kebab-case).
 * For schemas that need database values, we create Zod enums from Object.values() of the Prisma enum objects.
 */

import { z } from 'zod';
import type {
  use_case_type,
  integration_type,
  focus_area_type,
  job_type,
  job_category,
} from '@prisma/client';
import {
  job_type as JobType,
  job_category as JobCategory,
  workplace_type as WorkplaceType,
} from '@prisma/client';
import {
  job_plan,
  job_tier,
  company_size,
  use_case_type as useCaseTypeEnum,
  integration_type as integrationTypeEnum,
  focus_area_type as focusAreaTypeEnum,
} from '@prisma/client';

// Re-export Prisma-generated Zod schemas (these use enum keys, which may not match database values)
// These are generated by prisma-postgres-types-generator to packages/database-types/src/prisma/zod/schemas/enums/
export { content_categorySchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/content_category.schema';
export { experience_levelSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/experience_level.schema';
export { focus_area_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/focus_area_type.schema';
export { integration_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/integration_type.schema';
export { interaction_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/interaction_type.schema';
export { use_case_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/use_case_type.schema';
export { contact_action_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/contact_action_type.schema';
export { contact_categorySchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/contact_category.schema';
export { submission_statusSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/submission_status.schema';
export { submission_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/submission_type.schema';
export { newsletter_sourceSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/newsletter_source.schema';
export { follow_actionSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/follow_action.schema';
export { user_tierSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/user_tier.schema';
export { notification_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/notification_type.schema';
export { notification_prioritySchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/notification_priority.schema';
export { changelog_categorySchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/changelog_category.schema';
export { job_statusSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/job_status.schema';
export { company_sizeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/company_size.schema';
export { copy_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/copy_type.schema';
export { primary_action_typeSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/primary_action_type.schema';
export { oauth_providerSchema } from '@heyclaude/database-types/prisma/zod/schemas/enums/oauth_provider.schema';

// Create Zod schemas from Prisma enum object VALUES (these match database values)
// These are needed because Prisma enum objects have keys (snake_case) that map to database values (kebab-case)
// Use z.nativeEnum() to properly infer enum types instead of literal union types
export const jobTypeSchema: z.ZodType<job_type> = z.nativeEnum(JobType);
export const jobCategorySchema: z.ZodType<job_category> = z.nativeEnum(JobCategory);
export const jobPlanSchema = z.enum(Object.values(job_plan) as [string, ...string[]]);
export const jobTierSchema = z.enum(Object.values(job_tier) as [string, ...string[]]);
export const workplaceTypeSchema = z.enum(Object.values(WorkplaceType) as [string, ...string[]]);
export const companySizeSchema = z.enum(Object.values(company_size) as [string, ...string[]]);

// Create properly typed enum schemas using z.nativeEnum() with enum objects
// z.nativeEnum() works with the enum objects directly and properly infers the enum type
// This avoids the need for type assertions that z.enum() with Object.values() requires
export const useCaseTypeSchema: z.ZodType<use_case_type> = z.nativeEnum(useCaseTypeEnum);
export const integrationTypeSchema: z.ZodType<integration_type> = z.nativeEnum(integrationTypeEnum);
export const focusAreaTypeSchema: z.ZodType<focus_area_type> = z.nativeEnum(focusAreaTypeEnum);
