/**
 * Guides Index llms.txt Route
 *
 * Provides machine-readable index of all available guides for AI consumption.
 * Lists guides by category with titles, descriptions, and URLs.
 *
 * @route GET /guides/llms.txt
 * @see {@link https://llmstxt.org} - LLMs.txt specification
 */

import { existsSync, readdirSync } from 'fs';
import type { NextRequest } from 'next/server';
import { join } from 'path';
import { APP_CONFIG, CONTENT_PATHS } from '@/src/lib/constants';
import { handleApiError } from '@/src/lib/error-handler';
import { logger } from '@/src/lib/logger';

/**
 * Runtime configuration
 * Use Node.js runtime for better performance with file system access
 */
export const runtime = 'nodejs';

/**
 * ISR revalidation
 * Revalidate every hour (3600 seconds) - guides change infrequently
 */
export const revalidate = 3600;

const GUIDE_CATEGORIES = [
  {
    slug: 'use-cases',
    title: 'Use Cases',
    description: 'Real-world applications and industry-specific implementations',
  },
  {
    slug: 'tutorials',
    title: 'Tutorials',
    description: 'Step-by-step guides for setup and configuration',
  },
  {
    slug: 'workflows',
    title: 'Workflows',
    description: 'Migration guides and workflow optimization',
  },
  {
    slug: 'comparisons',
    title: 'Comparisons',
    description: 'Feature comparisons and tool evaluations',
  },
  {
    slug: 'troubleshooting',
    title: 'Troubleshooting',
    description: 'Common issues and solutions',
  },
] as const;

/**
 * Handle GET request for guides index llms.txt
 *
 * @param request - Next.js request object
 * @returns Plain text response with guides index
 *
 * @remarks
 * This route generates a complete guides index organized by category
 * following the llms.txt specification for AI-friendly consumption.
 */
export async function GET(request: NextRequest): Promise<Response> {
  const requestLogger = logger.forRequest(request);

  try {
    requestLogger.info('Guides llms.txt generation started');

    let guidesIndex = `# Claude Pro Directory Guides

> Comprehensive collection of tutorials, use cases, comparisons, workflows, and troubleshooting guides
> Last updated: ${new Date().toISOString().split('T')[0]}

## Overview

The guides section provides detailed documentation for using Claude and the Claude Pro Directory platform. Content is organized into five main categories covering everything from basic setup to advanced workflows.

`;

    // Generate index for each category
    for (const category of GUIDE_CATEGORIES) {
      const categoryDir = join(CONTENT_PATHS.guides, category.slug);

      guidesIndex += `\n## ${category.title}\n\n${category.description}\n\n`;

      if (existsSync(categoryDir)) {
        try {
          const files = readdirSync(categoryDir).filter((f) => f.endsWith('.mdx'));

          if (files.length > 0) {
            guidesIndex += 'Available guides:\n\n';

            for (const file of files) {
              const slug = file.replace('.mdx', '');
              const title = slug
                .split('-')
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join(' ');

              guidesIndex += `- ${title}\n`;
              guidesIndex += `  URL: ${APP_CONFIG.url}/guides/${category.slug}/${slug}\n`;
              guidesIndex += `  Machine-readable: ${APP_CONFIG.url}/guides/${category.slug}/${slug}/llms.txt\n\n`;
            }
          } else {
            guidesIndex += 'No guides available in this category yet.\n\n';
          }
        } catch {
          guidesIndex += 'Error reading guides in this category.\n\n';
        }
      } else {
        guidesIndex += 'Category directory not found.\n\n';
      }
    }

    guidesIndex += `\n## All Guides

Browse all guides at: ${APP_CONFIG.url}/guides

## Categories Summary

`;

    for (const category of GUIDE_CATEGORIES) {
      guidesIndex += `- ${category.title}: ${APP_CONFIG.url}/guides#${category.slug}\n`;
    }

    guidesIndex += `\n## Features

- **Use Cases**: Industry-specific implementations including healthcare (HIPAA), financial services, and business automation
- **Tutorials**: Step-by-step setup guides for MCP servers, desktop configuration, WSL, and agent development
- **Workflows**: Migration guides from ChatGPT and other AI tools to Claude
- **Comparisons**: Feature comparisons with GitHub Copilot, Cursor, Codeium, CodeWhisperer, and Gemini
- **Troubleshooting**: Solutions for common installation errors, connection issues, environment variables, and performance problems

## Search Guides

Search across all guides: ${APP_CONFIG.url}/?search=query

---

Generated by Claude Pro Directory
${APP_CONFIG.url}
`;

    requestLogger.info('Guides llms.txt generated successfully');

    return new Response(guidesIndex, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=7200',
      },
    });
  } catch (error) {
    const errorInstance = error instanceof Error ? error : new Error(String(error));
    requestLogger.error('Failed to generate guides llms.txt', errorInstance);
    return handleApiError(errorInstance);
  }
}
