/**
 * PostgreSQL Function: approve_submission
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ApproveSubmissionResult } from '../composites/approve_submission_result';
import { approveSubmissionResultSchema } from '../composites/approve_submission_result';

/**
 * Arguments for PostgreSQL function: approve_submission
 */
export type ApproveSubmissionArgs = {
  /** Parameter: p_submission_id (uuid) */
  p_submission_id: string;
  /** Parameter: p_moderator_notes (text, optional) */
  p_moderator_notes?: string;
};

/**
 * Zod schema for approve_submission function arguments
 */
export const approveSubmissionArgsSchema = z.object({
  /** Parameter: p_submission_id */
  p_submission_id: z.string().uuid(),
  /** Parameter: p_moderator_notes */
  p_moderator_notes: z.string().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ApproveSubmissionArgsFromZod = z.infer<typeof approveSubmissionArgsSchema>;

/**
 * Return type for PostgreSQL function: approve_submission
 */
export type ApproveSubmissionReturns = ApproveSubmissionResult;

/**
 * Zod schema for approve_submission function return type
 */
export const approveSubmissionReturnsSchema = approveSubmissionResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type ApproveSubmissionReturnsFromZod = z.infer<typeof approveSubmissionReturnsSchema>;
