/**
 * PostgreSQL Function: backfill_changelog_seo_fields
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: backfill_changelog_seo_fields
 */
export type BackfillChangelogSeoFieldsArgs = {
};

/**
 * Zod schema for backfill_changelog_seo_fields function arguments
 */
export const backfillChangelogSeoFieldsArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BackfillChangelogSeoFieldsArgsFromZod = z.infer<typeof backfillChangelogSeoFieldsArgsSchema>;

/**
 * Return row type for PostgreSQL function: backfill_changelog_seo_fields
 */
export type BackfillChangelogSeoFieldsReturnRow = {
  /** updated_count (int4, nullable) */
  updated_count: number | null;
  /** skipped_count (int4, nullable) */
  skipped_count: number | null;
  /** errors (_text, nullable) */
  errors: string[] | null;
};

/**
 * Zod schema for backfill_changelog_seo_fields return row
 */
export const backfillChangelogSeoFieldsReturnRowSchema = z.object({
  updated_count: z.number().nullable(),
  skipped_count: z.number().nullable(),
  errors: z.array(z.string()).nullable(),
});

/**
 * Return type for PostgreSQL function: backfill_changelog_seo_fields
 */
export type BackfillChangelogSeoFieldsReturns = BackfillChangelogSeoFieldsReturnRow[];

/**
 * Zod schema for backfill_changelog_seo_fields function return type
 */
export const backfillChangelogSeoFieldsReturnsSchema = z.array(backfillChangelogSeoFieldsReturnRowSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type BackfillChangelogSeoFieldsReturnsFromZod = z.infer<typeof backfillChangelogSeoFieldsReturnsSchema>;
