/**
 * PostgreSQL Function: batch_add_bookmarks
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { BatchAddBookmarksResult } from '../composites/batch_add_bookmarks_result';
import type { BookmarkItemInput } from '../composites/bookmark_item_input';
import { batchAddBookmarksResultSchema } from '../composites/batch_add_bookmarks_result';
import { bookmarkItemInputSchema } from '../composites/bookmark_item_input';

/**
 * Arguments for PostgreSQL function: batch_add_bookmarks
 */
export type BatchAddBookmarksArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
  /** Parameter: p_items (_bookmark_item_input) */
  p_items: BookmarkItemInput[];
};

/**
 * Zod schema for batch_add_bookmarks function arguments
 */
export const batchAddBookmarksArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
  /** Parameter: p_items */
  p_items: z.array(bookmarkItemInputSchema),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BatchAddBookmarksArgsFromZod = z.infer<typeof batchAddBookmarksArgsSchema>;

/**
 * Return type for PostgreSQL function: batch_add_bookmarks
 */
export type BatchAddBookmarksReturns = BatchAddBookmarksResult;

/**
 * Zod schema for batch_add_bookmarks function return type
 */
export const batchAddBookmarksReturnsSchema = batchAddBookmarksResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type BatchAddBookmarksReturnsFromZod = z.infer<typeof batchAddBookmarksReturnsSchema>;
