/**
 * PostgreSQL Function: batch_insert_user_interactions
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { BatchInsertUserInteractionsResult } from '../composites/batch_insert_user_interactions_result';
import type { UserInteractionInput } from '../composites/user_interaction_input';
import { batchInsertUserInteractionsResultSchema } from '../composites/batch_insert_user_interactions_result';
import { userInteractionInputSchema } from '../composites/user_interaction_input';

/**
 * Arguments for PostgreSQL function: batch_insert_user_interactions
 */
export type BatchInsertUserInteractionsArgs = {
  /** Parameter: p_interactions (_user_interaction_input) */
  p_interactions: UserInteractionInput[];
};

/**
 * Zod schema for batch_insert_user_interactions function arguments
 */
export const batchInsertUserInteractionsArgsSchema = z.object({
  /** Parameter: p_interactions */
  p_interactions: z.array(userInteractionInputSchema),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BatchInsertUserInteractionsArgsFromZod = z.infer<typeof batchInsertUserInteractionsArgsSchema>;

/**
 * Return type for PostgreSQL function: batch_insert_user_interactions
 */
export type BatchInsertUserInteractionsReturns = BatchInsertUserInteractionsResult;

/**
 * Zod schema for batch_insert_user_interactions function return type
 */
export const batchInsertUserInteractionsReturnsSchema = batchInsertUserInteractionsResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type BatchInsertUserInteractionsReturnsFromZod = z.infer<typeof batchInsertUserInteractionsReturnsSchema>;
