/**
 * PostgreSQL Function: build_how_to_schema
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { HowToSchemaResult } from '../composites/how_to_schema_result';
import { howToSchemaResultSchema } from '../composites/how_to_schema_result';

/**
 * Arguments for PostgreSQL function: build_how_to_schema
 */
export type BuildHowToSchemaArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_slug (text) */
  p_slug: string;
};

/**
 * Zod schema for build_how_to_schema function arguments
 */
export const buildHowToSchemaArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_slug */
  p_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildHowToSchemaArgsFromZod = z.infer<typeof buildHowToSchemaArgsSchema>;

/**
 * Return type for PostgreSQL function: build_how_to_schema
 */
export type BuildHowToSchemaReturns = HowToSchemaResult;

/**
 * Zod schema for build_how_to_schema function return type
 */
export const buildHowToSchemaReturnsSchema = howToSchemaResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildHowToSchemaReturnsFromZod = z.infer<typeof buildHowToSchemaReturnsSchema>;
