/**
 * PostgreSQL Function: build_faq_schema
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { FaqSchemaResult } from '../composites/faq_schema_result';
import { faqSchemaResultSchema } from '../composites/faq_schema_result';

/**
 * Arguments for PostgreSQL function: build_faq_schema
 */
export type BuildFaqSchemaArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_slug (text) */
  p_slug: string;
};

/**
 * Zod schema for build_faq_schema function arguments
 */
export const buildFaqSchemaArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_slug */
  p_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildFaqSchemaArgsFromZod = z.infer<typeof buildFaqSchemaArgsSchema>;

/**
 * Return type for PostgreSQL function: build_faq_schema
 */
export type BuildFaqSchemaReturns = FaqSchemaResult;

/**
 * Zod schema for build_faq_schema function return type
 */
export const buildFaqSchemaReturnsSchema = faqSchemaResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildFaqSchemaReturnsFromZod = z.infer<typeof buildFaqSchemaReturnsSchema>;
