/**
 * PostgreSQL Function: build_person_schema
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: build_person_schema
 */
export type BuildPersonSchemaArgs = {
  /** Parameter: p_slug (text) */
  p_slug: string;
};

/**
 * Zod schema for build_person_schema function arguments
 */
export const buildPersonSchemaArgsSchema = z.object({
  /** Parameter: p_slug */
  p_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildPersonSchemaArgsFromZod = z.infer<typeof buildPersonSchemaArgsSchema>;

/**
 * Return type for PostgreSQL function: build_person_schema
 */
export type BuildPersonSchemaReturns = Record<string, unknown>;

/**
 * Zod schema for build_person_schema function return type
 */
export const buildPersonSchemaReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type BuildPersonSchemaReturnsFromZod = z.infer<typeof buildPersonSchemaReturnsSchema>;
