/**
 * PostgreSQL Function: calculate_content_time_metrics
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: calculate_content_time_metrics
 */
export type CalculateContentTimeMetricsArgs = {
};

/**
 * Zod schema for calculate_content_time_metrics function arguments
 */
export const calculateContentTimeMetricsArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type CalculateContentTimeMetricsArgsFromZod = z.infer<typeof calculateContentTimeMetricsArgsSchema>;

/**
 * Return row type for PostgreSQL function: calculate_content_time_metrics
 */
export type CalculateContentTimeMetricsReturnRow = {
  /** updated_count (int4, nullable) */
  updated_count: number | null;
  /** created_count (int4, nullable) */
  created_count: number | null;
};

/**
 * Zod schema for calculate_content_time_metrics return row
 */
export const calculateContentTimeMetricsReturnRowSchema = z.object({
  updated_count: z.number().nullable(),
  created_count: z.number().nullable(),
});

/**
 * Return type for PostgreSQL function: calculate_content_time_metrics
 */
export type CalculateContentTimeMetricsReturns = CalculateContentTimeMetricsReturnRow[];

/**
 * Zod schema for calculate_content_time_metrics function return type
 */
export const calculateContentTimeMetricsReturnsSchema = z.array(calculateContentTimeMetricsReturnRowSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type CalculateContentTimeMetricsReturnsFromZod = z.infer<typeof calculateContentTimeMetricsReturnsSchema>;
