/**
 * PostgreSQL Function: cancel_email_sequence
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: cancel_email_sequence
 */
export type CancelEmailSequenceArgs = {
  /** Parameter: p_email (text) */
  p_email: string;
};

/**
 * Zod schema for cancel_email_sequence function arguments
 */
export const cancelEmailSequenceArgsSchema = z.object({
  /** Parameter: p_email */
  p_email: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type CancelEmailSequenceArgsFromZod = z.infer<typeof cancelEmailSequenceArgsSchema>;

/**
 * Return type for PostgreSQL function: cancel_email_sequence
 */
export type CancelEmailSequenceReturns = void;
