/**
 * PostgreSQL Function: format_date_short
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: format_date_short
 */
export type FormatDateShortArgs = {
  /** Parameter: input_date (timestamptz) */
  input_date: string;
};

/**
 * Zod schema for format_date_short function arguments
 */
export const formatDateShortArgsSchema = z.object({
  /** Parameter: input_date */
  input_date: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type FormatDateShortArgsFromZod = z.infer<typeof formatDateShortArgsSchema>;

/**
 * Return type for PostgreSQL function: format_date_short
 */
export type FormatDateShortReturns = string;

/**
 * Zod schema for format_date_short function return type
 */
export const formatDateShortReturnsSchema = z.string();

/**
 * Type inference from Zod schema (should match type above)
 */
export type FormatDateShortReturnsFromZod = z.infer<typeof formatDateShortReturnsSchema>;
