/**
 * PostgreSQL Function: generate_changelog_entry_llms_txt
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: generate_changelog_entry_llms_txt
 */
export type GenerateChangelogEntryLlmsTxtArgs = {
  /** Parameter: p_slug (text) */
  p_slug: string;
};

/**
 * Zod schema for generate_changelog_entry_llms_txt function arguments
 */
export const generateChangelogEntryLlmsTxtArgsSchema = z.object({
  /** Parameter: p_slug */
  p_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateChangelogEntryLlmsTxtArgsFromZod = z.infer<typeof generateChangelogEntryLlmsTxtArgsSchema>;

/**
 * Return type for PostgreSQL function: generate_changelog_entry_llms_txt
 */
export type GenerateChangelogEntryLlmsTxtReturns = string;

/**
 * Zod schema for generate_changelog_entry_llms_txt function return type
 */
export const generateChangelogEntryLlmsTxtReturnsSchema = z.string();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateChangelogEntryLlmsTxtReturnsFromZod = z.infer<typeof generateChangelogEntryLlmsTxtReturnsSchema>;
