/**
 * PostgreSQL Function: generate_content_field
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: generate_content_field
 */
export type GenerateContentFieldArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_slug (text) */
  p_slug: string;
  /** Parameter: p_field_type (content_field_type) */
  p_field_type: 'installation' | 'use_cases' | 'troubleshooting' | 'requirements';
};

/**
 * Zod schema for generate_content_field function arguments
 */
export const generateContentFieldArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_slug */
  p_slug: z.string(),
  /** Parameter: p_field_type */
  p_field_type: z.enum(['installation', 'use_cases', 'troubleshooting', 'requirements']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateContentFieldArgsFromZod = z.infer<typeof generateContentFieldArgsSchema>;

/**
 * Return type for PostgreSQL function: generate_content_field
 */
export type GenerateContentFieldReturns = Record<string, unknown>;

/**
 * Zod schema for generate_content_field function return type
 */
export const generateContentFieldReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateContentFieldReturnsFromZod = z.infer<typeof generateContentFieldReturnsSchema>;
