/**
 * PostgreSQL Function: generate_metadata_complete
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { GenerateMetadataCompleteResult } from '../composites/generate_metadata_complete_result';
import { generateMetadataCompleteResultSchema } from '../composites/generate_metadata_complete_result';

/**
 * Arguments for PostgreSQL function: generate_metadata_complete
 */
export type GenerateMetadataCompleteArgs = {
  /** Parameter: p_route (text) */
  p_route: string;
  /** Parameter: p_include (text, optional) */
  p_include?: string;
};

/**
 * Zod schema for generate_metadata_complete function arguments
 */
export const generateMetadataCompleteArgsSchema = z.object({
  /** Parameter: p_route */
  p_route: z.string(),
  /** Parameter: p_include */
  p_include: z.string().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateMetadataCompleteArgsFromZod = z.infer<typeof generateMetadataCompleteArgsSchema>;

/**
 * Return type for PostgreSQL function: generate_metadata_complete
 */
export type GenerateMetadataCompleteReturns = GenerateMetadataCompleteResult;

/**
 * Zod schema for generate_metadata_complete function return type
 */
export const generateMetadataCompleteReturnsSchema = generateMetadataCompleteResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GenerateMetadataCompleteReturnsFromZod = z.infer<typeof generateMetadataCompleteReturnsSchema>;
