/**
 * PostgreSQL Function: get_api_content_full
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_api_content_full
 */
export type GetApiContentFullArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_slug (text) */
  p_slug: string;
  /** Parameter: p_base_url (text, optional) */
  p_base_url: string | undefined | null | undefined;
};

/**
 * Zod schema for get_api_content_full function arguments
 */
export const getApiContentFullArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_slug */
  p_slug: z.string(),
  /** Parameter: p_base_url */
  p_base_url: z.string().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetApiContentFullArgsFromZod = z.infer<typeof getApiContentFullArgsSchema>;

/**
 * Return type for PostgreSQL function: get_api_content_full
 */
export type GetApiContentFullReturns = string;

/**
 * Zod schema for get_api_content_full function return type
 */
export const getApiContentFullReturnsSchema = z.string();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetApiContentFullReturnsFromZod = z.infer<typeof getApiContentFullReturnsSchema>;
