/**
 * PostgreSQL Function: get_content_by_tag
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_content_by_tag
 */
export type GetContentByTagArgs = {
  /** Parameter: p_tag (text) */
  p_tag: string;
  /** Parameter: p_category (content_category, optional) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | undefined | null | undefined;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
  /** Parameter: p_offset (int4, optional) */
  p_offset: number | undefined | null | undefined;
};

/**
 * Zod schema for get_content_by_tag function arguments
 */
export const getContentByTagArgsSchema = z.object({
  /** Parameter: p_tag */
  p_tag: z.string(),
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
  /** Parameter: p_offset */
  p_offset: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentByTagArgsFromZod = z.infer<typeof getContentByTagArgsSchema>;

/**
 * Return type for PostgreSQL function: get_content_by_tag
 */
export type GetContentByTagReturns = Record<string, unknown>[];

/**
 * Zod schema for get_content_by_tag function return type
 */
export const getContentByTagReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentByTagReturnsFromZod = z.infer<typeof getContentByTagReturnsSchema>;
