/**
 * PostgreSQL Function: get_popular_content_formatted
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_popular_content_formatted
 */
export type GetPopularContentFormattedArgs = {
  /** Parameter: p_category (content_category, optional) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | undefined | null | undefined;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
};

/**
 * Zod schema for get_popular_content_formatted function arguments
 */
export const getPopularContentFormattedArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetPopularContentFormattedArgsFromZod = z.infer<typeof getPopularContentFormattedArgsSchema>;

/**
 * Return type for PostgreSQL function: get_popular_content_formatted
 */
export type GetPopularContentFormattedReturns = Record<string, unknown>[];

/**
 * Zod schema for get_popular_content_formatted function return type
 */
export const getPopularContentFormattedReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetPopularContentFormattedReturnsFromZod = z.infer<typeof getPopularContentFormattedReturnsSchema>;
