/**
 * PostgreSQL Function: get_content_templates
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ContentTemplatesResult } from '../composites/content_templates_result';
import { contentTemplatesResultSchema } from '../composites/content_templates_result';

/**
 * Arguments for PostgreSQL function: get_content_templates
 */
export type GetContentTemplatesArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
};

/**
 * Zod schema for get_content_templates function arguments
 */
export const getContentTemplatesArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentTemplatesArgsFromZod = z.infer<typeof getContentTemplatesArgsSchema>;

/**
 * Return type for PostgreSQL function: get_content_templates
 */
export type GetContentTemplatesReturns = ContentTemplatesResult;

/**
 * Zod schema for get_content_templates function return type
 */
export const getContentTemplatesReturnsSchema = contentTemplatesResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentTemplatesReturnsFromZod = z.infer<typeof getContentTemplatesReturnsSchema>;
