/**
 * PostgreSQL Function: get_jobs_list
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { JobsListItem } from '../composites/jobs_list_item';
import { jobsListItemSchema } from '../composites/jobs_list_item';

/**
 * Arguments for PostgreSQL function: get_jobs_list
 */
export type GetJobsListArgs = {
};

/**
 * Zod schema for get_jobs_list function arguments
 */
export const getJobsListArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetJobsListArgsFromZod = z.infer<typeof getJobsListArgsSchema>;

/**
 * Return type for PostgreSQL function: get_jobs_list
 */
export type GetJobsListReturns = JobsListItem;

/**
 * Zod schema for get_jobs_list function return type
 */
export const getJobsListReturnsSchema = jobsListItemSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetJobsListReturnsFromZod = z.infer<typeof getJobsListReturnsSchema>;
