/**
 * PostgreSQL Function: get_category_display_name
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_category_display_name
 */
export type GetCategoryDisplayNameArgs = {
  /** Parameter: p_category (text) */
  p_category: string;
};

/**
 * Zod schema for get_category_display_name function arguments
 */
export const getCategoryDisplayNameArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCategoryDisplayNameArgsFromZod = z.infer<typeof getCategoryDisplayNameArgsSchema>;

/**
 * Return type for PostgreSQL function: get_category_display_name
 */
export type GetCategoryDisplayNameReturns = string;

/**
 * Zod schema for get_category_display_name function return type
 */
export const getCategoryDisplayNameReturnsSchema = z.string();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCategoryDisplayNameReturnsFromZod = z.infer<typeof getCategoryDisplayNameReturnsSchema>;
