/**
 * PostgreSQL Function: get_form_field_config
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { FormFieldConfigResult } from '../composites/form_field_config_result';
import { formFieldConfigResultSchema } from '../composites/form_field_config_result';

/**
 * Arguments for PostgreSQL function: get_form_field_config
 */
export type GetFormFieldConfigArgs = {
  /** Parameter: p_form_type (text) */
  p_form_type: string;
};

/**
 * Zod schema for get_form_field_config function arguments
 */
export const getFormFieldConfigArgsSchema = z.object({
  /** Parameter: p_form_type */
  p_form_type: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetFormFieldConfigArgsFromZod = z.infer<typeof getFormFieldConfigArgsSchema>;

/**
 * Return type for PostgreSQL function: get_form_field_config
 */
export type GetFormFieldConfigReturns = FormFieldConfigResult;

/**
 * Zod schema for get_form_field_config function return type
 */
export const getFormFieldConfigReturnsSchema = formFieldConfigResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetFormFieldConfigReturnsFromZod = z.infer<typeof getFormFieldConfigReturnsSchema>;
