/**
 * PostgreSQL Function: get_week_end
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_week_end
 */
export type GetWeekEndArgs = {
  /** Parameter: week_start (timestamptz) */
  week_start: string;
};

/**
 * Zod schema for get_week_end function arguments
 */
export const getWeekEndArgsSchema = z.object({
  /** Parameter: week_start */
  week_start: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetWeekEndArgsFromZod = z.infer<typeof getWeekEndArgsSchema>;

/**
 * Return type for PostgreSQL function: get_week_end
 */
export type GetWeekEndReturns = unknown;

/**
 * Zod schema for get_week_end function return type
 */
export const getWeekEndReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetWeekEndReturnsFromZod = z.infer<typeof getWeekEndReturnsSchema>;
