/**
 * PostgreSQL Function: get_content_detail_complete
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_content_detail_complete
 */
export type GetContentDetailCompleteArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_slug (text) */
  p_slug: string;
  /** Parameter: p_user_id (uuid, optional) */
  p_user_id?: string;
};

/**
 * Zod schema for get_content_detail_complete function arguments
 */
export const getContentDetailCompleteArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_slug */
  p_slug: z.string(),
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentDetailCompleteArgsFromZod = z.infer<typeof getContentDetailCompleteArgsSchema>;

/**
 * Return type for PostgreSQL function: get_content_detail_complete
 */
export type GetContentDetailCompleteReturns = unknown;

/**
 * Zod schema for get_content_detail_complete function return type
 */
export const getContentDetailCompleteReturnsSchema = z.unknown();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContentDetailCompleteReturnsFromZod = z.infer<typeof getContentDetailCompleteReturnsSchema>;
