/**
 * PostgreSQL Function: get_recent_content
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { Content } from '../composites/content';
import { contentSchema } from '../composites/content';

/**
 * Arguments for PostgreSQL function: get_recent_content
 */
export type GetRecentContentArgs = {
  /** Parameter: p_category (text, optional) */
  p_category?: string;
  /** Parameter: p_limit (int4, optional) */
  p_limit?: number;
  /** Parameter: p_days (int4, optional) */
  p_days?: number;
};

/**
 * Zod schema for get_recent_content function arguments
 */
export const getRecentContentArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.string().nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
  /** Parameter: p_days */
  p_days: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetRecentContentArgsFromZod = z.infer<typeof getRecentContentArgsSchema>;

/**
 * Return type for PostgreSQL function: get_recent_content
 */
export type GetRecentContentReturns = Content[];

/**
 * Zod schema for get_recent_content function return type
 */
export const getRecentContentReturnsSchema = z.array(contentSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetRecentContentReturnsFromZod = z.infer<typeof getRecentContentReturnsSchema>;
