/**
 * PostgreSQL Function: get_user_interaction_summary
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { UserInteractionSummary } from '../composites/user_interaction_summary';
import { userInteractionSummarySchema } from '../composites/user_interaction_summary';

/**
 * Arguments for PostgreSQL function: get_user_interaction_summary
 */
export type GetUserInteractionSummaryArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
};

/**
 * Zod schema for get_user_interaction_summary function arguments
 */
export const getUserInteractionSummaryArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserInteractionSummaryArgsFromZod = z.infer<typeof getUserInteractionSummaryArgsSchema>;

/**
 * Return type for PostgreSQL function: get_user_interaction_summary
 */
export type GetUserInteractionSummaryReturns = UserInteractionSummary;

/**
 * Zod schema for get_user_interaction_summary function return type
 */
export const getUserInteractionSummaryReturnsSchema = userInteractionSummarySchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserInteractionSummaryReturnsFromZod = z.infer<typeof getUserInteractionSummaryReturnsSchema>;
