/**
 * PostgreSQL Function: get_bulk_user_stats_realtime
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_bulk_user_stats_realtime
 */
export type GetBulkUserStatsRealtimeArgs = {
  /** Parameter: user_ids (_uuid) */
  user_ids: string[];
};

/**
 * Zod schema for get_bulk_user_stats_realtime function arguments
 */
export const getBulkUserStatsRealtimeArgsSchema = z.object({
  /** Parameter: user_ids */
  user_ids: z.array(z.string().uuid()),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetBulkUserStatsRealtimeArgsFromZod = z.infer<typeof getBulkUserStatsRealtimeArgsSchema>;

/**
 * Return type for PostgreSQL function: get_bulk_user_stats_realtime
 */
export type GetBulkUserStatsRealtimeReturns = Record<string, unknown>[];

/**
 * Zod schema for get_bulk_user_stats_realtime function return type
 */
export const getBulkUserStatsRealtimeReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetBulkUserStatsRealtimeReturnsFromZod = z.infer<typeof getBulkUserStatsRealtimeReturnsSchema>;
