/**
 * PostgreSQL Function: get_similar_content
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { SimilarContentResult } from '../composites/similar_content_result';
import { similarContentResultSchema } from '../composites/similar_content_result';

/**
 * Arguments for PostgreSQL function: get_similar_content
 */
export type GetSimilarContentArgs = {
  /** Parameter: p_content_type (content_category) */
  p_content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_content_slug (text) */
  p_content_slug: string;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
};

/**
 * Zod schema for get_similar_content function arguments
 */
export const getSimilarContentArgsSchema = z.object({
  /** Parameter: p_content_type */
  p_content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_content_slug */
  p_content_slug: z.string(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetSimilarContentArgsFromZod = z.infer<typeof getSimilarContentArgsSchema>;

/**
 * Return type for PostgreSQL function: get_similar_content
 */
export type GetSimilarContentReturns = SimilarContentResult;

/**
 * Zod schema for get_similar_content function return type
 */
export const getSimilarContentReturnsSchema = similarContentResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetSimilarContentReturnsFromZod = z.infer<typeof getSimilarContentReturnsSchema>;
