/**
 * PostgreSQL Function: get_category_content_list
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_category_content_list
 */
export type GetCategoryContentListArgs = {
  /** Parameter: p_category (content_category) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
};

/**
 * Zod schema for get_category_content_list function arguments
 */
export const getCategoryContentListArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCategoryContentListArgsFromZod = z.infer<typeof getCategoryContentListArgsSchema>;

/**
 * Return type for PostgreSQL function: get_category_content_list
 */
export type GetCategoryContentListReturns = Record<string, unknown>[];

/**
 * Zod schema for get_category_content_list function return type
 */
export const getCategoryContentListReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCategoryContentListReturnsFromZod = z.infer<typeof getCategoryContentListReturnsSchema>;
