/**
 * PostgreSQL Function: get_all_app_settings
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_all_app_settings
 */
export type GetAllAppSettingsArgs = {
};

/**
 * Zod schema for get_all_app_settings function arguments
 */
export const getAllAppSettingsArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetAllAppSettingsArgsFromZod = z.infer<typeof getAllAppSettingsArgsSchema>;

/**
 * Return type for PostgreSQL function: get_all_app_settings
 */
export type GetAllAppSettingsReturns = Record<string, unknown>;

/**
 * Zod schema for get_all_app_settings function return type
 */
export const getAllAppSettingsReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetAllAppSettingsReturnsFromZod = z.infer<typeof getAllAppSettingsReturnsSchema>;
