/**
 * PostgreSQL Function: get_contact_commands
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ContactCommandResult } from '../composites/contact_command_result';
import { contactCommandResultSchema } from '../composites/contact_command_result';

/**
 * Arguments for PostgreSQL function: get_contact_commands
 */
export type GetContactCommandsArgs = {
};

/**
 * Zod schema for get_contact_commands function arguments
 */
export const getContactCommandsArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContactCommandsArgsFromZod = z.infer<typeof getContactCommandsArgsSchema>;

/**
 * Return type for PostgreSQL function: get_contact_commands
 */
export type GetContactCommandsReturns = ContactCommandResult[][];

/**
 * Zod schema for get_contact_commands function return type
 */
export const getContactCommandsReturnsSchema = z.array(z.array(contactCommandResultSchema));

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetContactCommandsReturnsFromZod = z.infer<typeof getContactCommandsReturnsSchema>;
