/**
 * PostgreSQL Function: get_search_suggestions_from_history
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_search_suggestions_from_history
 */
export type GetSearchSuggestionsFromHistoryArgs = {
  /** Parameter: p_query (text) */
  p_query: string;
  /** Parameter: p_limit (int4, optional) */
  p_limit?: number;
};

/**
 * Zod schema for get_search_suggestions_from_history function arguments
 */
export const getSearchSuggestionsFromHistoryArgsSchema = z.object({
  /** Parameter: p_query */
  p_query: z.string(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetSearchSuggestionsFromHistoryArgsFromZod = z.infer<typeof getSearchSuggestionsFromHistoryArgsSchema>;

/**
 * Return row type for PostgreSQL function: get_search_suggestions_from_history
 */
export type GetSearchSuggestionsFromHistoryReturnRow = {
  /** suggestion (text, nullable) */
  suggestion: string | null;
  /** search_count (int8, nullable) */
  search_count: number | null;
};

/**
 * Zod schema for get_search_suggestions_from_history return row
 */
export const getSearchSuggestionsFromHistoryReturnRowSchema = z.object({
  suggestion: z.string().nullable(),
  search_count: z.number().nullable(),
});

/**
 * Return type for PostgreSQL function: get_search_suggestions_from_history
 */
export type GetSearchSuggestionsFromHistoryReturns = GetSearchSuggestionsFromHistoryReturnRow[];

/**
 * Zod schema for get_search_suggestions_from_history function return type
 */
export const getSearchSuggestionsFromHistoryReturnsSchema = z.array(getSearchSuggestionsFromHistoryReturnRowSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetSearchSuggestionsFromHistoryReturnsFromZod = z.infer<typeof getSearchSuggestionsFromHistoryReturnsSchema>;
