/**
 * PostgreSQL Function: get_user_profile
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { UserProfileResult } from '../composites/user_profile_result';
import { userProfileResultSchema } from '../composites/user_profile_result';

/**
 * Arguments for PostgreSQL function: get_user_profile
 */
export type GetUserProfileArgs = {
  /** Parameter: p_user_slug (text) */
  p_user_slug: string;
  /** Parameter: p_viewer_id (uuid, optional) */
  p_viewer_id: string | undefined | null | undefined;
};

/**
 * Zod schema for get_user_profile function arguments
 */
export const getUserProfileArgsSchema = z.object({
  /** Parameter: p_user_slug */
  p_user_slug: z.string(),
  /** Parameter: p_viewer_id */
  p_viewer_id: z.string().uuid().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserProfileArgsFromZod = z.infer<typeof getUserProfileArgsSchema>;

/**
 * Return type for PostgreSQL function: get_user_profile
 */
export type GetUserProfileReturns = UserProfileResult;

/**
 * Zod schema for get_user_profile function return type
 */
export const getUserProfileReturnsSchema = userProfileResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserProfileReturnsFromZod = z.infer<typeof getUserProfileReturnsSchema>;
