/**
 * PostgreSQL Function: get_community_directory
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { CommunityDirectoryResult } from '../composites/community_directory_result';
import { communityDirectoryResultSchema } from '../composites/community_directory_result';

/**
 * Arguments for PostgreSQL function: get_community_directory
 */
export type GetCommunityDirectoryArgs = {
  /** Parameter: p_search_query (text, optional) */
  p_search_query: string | undefined | null | undefined;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
};

/**
 * Zod schema for get_community_directory function arguments
 */
export const getCommunityDirectoryArgsSchema = z.object({
  /** Parameter: p_search_query */
  p_search_query: z.string().nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCommunityDirectoryArgsFromZod = z.infer<typeof getCommunityDirectoryArgsSchema>;

/**
 * Return type for PostgreSQL function: get_community_directory
 */
export type GetCommunityDirectoryReturns = CommunityDirectoryResult;

/**
 * Zod schema for get_community_directory function return type
 */
export const getCommunityDirectoryReturnsSchema = communityDirectoryResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetCommunityDirectoryReturnsFromZod = z.infer<typeof getCommunityDirectoryReturnsSchema>;
