/**
 * PostgreSQL Function: get_my_submissions
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { MySubmissionsItem } from '../composites/my_submissions_item';
import { mySubmissionsItemSchema } from '../composites/my_submissions_item';

/**
 * Arguments for PostgreSQL function: get_my_submissions
 */
export type GetMySubmissionsArgs = {
  /** Parameter: p_limit (int4, optional) */
  p_limit?: number;
  /** Parameter: p_offset (int4, optional) */
  p_offset?: number;
};

/**
 * Zod schema for get_my_submissions function arguments
 */
export const getMySubmissionsArgsSchema = z.object({
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
  /** Parameter: p_offset */
  p_offset: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetMySubmissionsArgsFromZod = z.infer<typeof getMySubmissionsArgsSchema>;

/**
 * Return type for PostgreSQL function: get_my_submissions
 */
export type GetMySubmissionsReturns = MySubmissionsItem[];

/**
 * Zod schema for get_my_submissions function return type
 */
export const getMySubmissionsReturnsSchema = z.array(mySubmissionsItemSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetMySubmissionsReturnsFromZod = z.infer<typeof getMySubmissionsReturnsSchema>;
