/**
 * PostgreSQL Function: get_user_dashboard
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { UserDashboardResult } from '../composites/user_dashboard_result';
import { userDashboardResultSchema } from '../composites/user_dashboard_result';

/**
 * Arguments for PostgreSQL function: get_user_dashboard
 */
export type GetUserDashboardArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
};

/**
 * Zod schema for get_user_dashboard function arguments
 */
export const getUserDashboardArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserDashboardArgsFromZod = z.infer<typeof getUserDashboardArgsSchema>;

/**
 * Return type for PostgreSQL function: get_user_dashboard
 */
export type GetUserDashboardReturns = UserDashboardResult;

/**
 * Zod schema for get_user_dashboard function return type
 */
export const getUserDashboardReturnsSchema = userDashboardResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetUserDashboardReturnsFromZod = z.infer<typeof getUserDashboardReturnsSchema>;
