/**
 * PostgreSQL Function: get_trending_metrics_with_content
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_trending_metrics_with_content
 */
export type GetTrendingMetricsWithContentArgs = {
  /** Parameter: p_category (content_category, optional) */
  p_category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | undefined | null | undefined;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
};

/**
 * Zod schema for get_trending_metrics_with_content function arguments
 */
export const getTrendingMetricsWithContentArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetTrendingMetricsWithContentArgsFromZod = z.infer<typeof getTrendingMetricsWithContentArgsSchema>;

/**
 * Return type for PostgreSQL function: get_trending_metrics_with_content
 */
export type GetTrendingMetricsWithContentReturns = Record<string, unknown>[];

/**
 * Zod schema for get_trending_metrics_with_content function return type
 */
export const getTrendingMetricsWithContentReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetTrendingMetricsWithContentReturnsFromZod = z.infer<typeof getTrendingMetricsWithContentReturnsSchema>;
