/**
 * PostgreSQL Function: get_changelog_overview
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ChangelogOverviewResult } from '../composites/changelog_overview_result';
import { changelogOverviewResultSchema } from '../composites/changelog_overview_result';

/**
 * Arguments for PostgreSQL function: get_changelog_overview
 */
export type GetChangelogOverviewArgs = {
  /** Parameter: p_category (text, optional) */
  p_category: string | undefined | null | undefined;
  /** Parameter: p_published_only (bool, optional) */
  p_published_only: boolean | undefined | null | undefined;
  /** Parameter: p_featured_only (bool, optional) */
  p_featured_only: boolean | undefined | null | undefined;
  /** Parameter: p_limit (int4, optional) */
  p_limit: number | undefined | null | undefined;
  /** Parameter: p_offset (int4, optional) */
  p_offset: number | undefined | null | undefined;
};

/**
 * Zod schema for get_changelog_overview function arguments
 */
export const getChangelogOverviewArgsSchema = z.object({
  /** Parameter: p_category */
  p_category: z.string().nullable().optional(),
  /** Parameter: p_published_only */
  p_published_only: z.boolean().nullable().optional(),
  /** Parameter: p_featured_only */
  p_featured_only: z.boolean().nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
  /** Parameter: p_offset */
  p_offset: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetChangelogOverviewArgsFromZod = z.infer<typeof getChangelogOverviewArgsSchema>;

/**
 * Return type for PostgreSQL function: get_changelog_overview
 */
export type GetChangelogOverviewReturns = ChangelogOverviewResult;

/**
 * Zod schema for get_changelog_overview function return type
 */
export const getChangelogOverviewReturnsSchema = changelogOverviewResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetChangelogOverviewReturnsFromZod = z.infer<typeof getChangelogOverviewReturnsSchema>;
