/**
 * PostgreSQL Function: get_mcpb_storage_path
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: get_mcpb_storage_path
 */
export type GetMcpbStoragePathArgs = {
  /** Parameter: p_slug (text) */
  p_slug: string;
};

/**
 * Zod schema for get_mcpb_storage_path function arguments
 */
export const getMcpbStoragePathArgsSchema = z.object({
  /** Parameter: p_slug */
  p_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetMcpbStoragePathArgsFromZod = z.infer<typeof getMcpbStoragePathArgsSchema>;

/**
 * Return type for PostgreSQL function: get_mcpb_storage_path
 */
export type GetMcpbStoragePathReturns = Record<string, unknown>[];

/**
 * Zod schema for get_mcpb_storage_path function return type
 */
export const getMcpbStoragePathReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type GetMcpbStoragePathReturnsFromZod = z.infer<typeof getMcpbStoragePathReturnsSchema>;
