/**
 * PostgreSQL Function: handle_webhook_vercel_deployment
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: handle_webhook_vercel_deployment
 */
export type HandleWebhookVercelDeploymentArgs = {
  /** Parameter: p_webhook_id (uuid) */
  p_webhook_id: string;
  /** Parameter: p_event_data (jsonb) */
  p_event_data: Record<string, unknown>;
};

/**
 * Zod schema for handle_webhook_vercel_deployment function arguments
 */
export const handleWebhookVercelDeploymentArgsSchema = z.object({
  /** Parameter: p_webhook_id */
  p_webhook_id: z.string().uuid(),
  /** Parameter: p_event_data */
  p_event_data: z.any(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type HandleWebhookVercelDeploymentArgsFromZod = z.infer<typeof handleWebhookVercelDeploymentArgsSchema>;

/**
 * Return type for PostgreSQL function: handle_webhook_vercel_deployment
 */
export type HandleWebhookVercelDeploymentReturns = void;
