/**
 * PostgreSQL Function: handle_polar_subscription_renewal
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: handle_polar_subscription_renewal
 */
export type HandlePolarSubscriptionRenewalArgs = {
  /** Parameter: webhook_id (uuid) */
  webhook_id: string;
  /** Parameter: webhook_data (jsonb) */
  webhook_data: Record<string, unknown>;
};

/**
 * Zod schema for handle_polar_subscription_renewal function arguments
 */
export const handlePolarSubscriptionRenewalArgsSchema = z.object({
  /** Parameter: webhook_id */
  webhook_id: z.string().uuid(),
  /** Parameter: webhook_data */
  webhook_data: z.any(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type HandlePolarSubscriptionRenewalArgsFromZod = z.infer<typeof handlePolarSubscriptionRenewalArgsSchema>;

/**
 * Return type for PostgreSQL function: handle_polar_subscription_renewal
 */
export type HandlePolarSubscriptionRenewalReturns = void;
