/**
 * PostgreSQL Function: handle_polar_order_refunded
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: handle_polar_order_refunded
 */
export type HandlePolarOrderRefundedArgs = {
  /** Parameter: webhook_id (uuid) */
  webhook_id: string;
  /** Parameter: webhook_data (jsonb) */
  webhook_data: Record<string, unknown>;
};

/**
 * Zod schema for handle_polar_order_refunded function arguments
 */
export const handlePolarOrderRefundedArgsSchema = z.object({
  /** Parameter: webhook_id */
  webhook_id: z.string().uuid(),
  /** Parameter: webhook_data */
  webhook_data: z.any(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type HandlePolarOrderRefundedArgsFromZod = z.infer<typeof handlePolarOrderRefundedArgsSchema>;

/**
 * Return type for PostgreSQL function: handle_polar_order_refunded
 */
export type HandlePolarOrderRefundedReturns = void;
