/**
 * PostgreSQL Function: is_admin
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: is_admin
 */
export type IsAdminArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
};

/**
 * Zod schema for is_admin function arguments
 */
export const isAdminArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsAdminArgsFromZod = z.infer<typeof isAdminArgsSchema>;

/**
 * Return type for PostgreSQL function: is_admin
 */
export type IsAdminReturns = unknown;

/**
 * Zod schema for is_admin function return type
 */
export const isAdminReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsAdminReturnsFromZod = z.infer<typeof isAdminReturnsSchema>;
