/**
 * PostgreSQL Function: is_bookmarked
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: is_bookmarked
 */
export type IsBookmarkedArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
  /** Parameter: p_content_type (content_category) */
  p_content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_content_slug (text) */
  p_content_slug: string;
};

/**
 * Zod schema for is_bookmarked function arguments
 */
export const isBookmarkedArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
  /** Parameter: p_content_type */
  p_content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_content_slug */
  p_content_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsBookmarkedArgsFromZod = z.infer<typeof isBookmarkedArgsSchema>;

/**
 * Return type for PostgreSQL function: is_bookmarked
 */
export type IsBookmarkedReturns = unknown;

/**
 * Zod schema for is_bookmarked function return type
 */
export const isBookmarkedReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsBookmarkedReturnsFromZod = z.infer<typeof isBookmarkedReturnsSchema>;
