/**
 * PostgreSQL Function: is_in_past
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: is_in_past
 */
export type IsInPastArgs = {
  /** Parameter: input_date (timestamptz) */
  input_date: string;
};

/**
 * Zod schema for is_in_past function arguments
 */
export const isInPastArgsSchema = z.object({
  /** Parameter: input_date */
  input_date: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsInPastArgsFromZod = z.infer<typeof isInPastArgsSchema>;

/**
 * Return type for PostgreSQL function: is_in_past
 */
export type IsInPastReturns = unknown;

/**
 * Zod schema for is_in_past function return type
 */
export const isInPastReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type IsInPastReturnsFromZod = z.infer<typeof isInPastReturnsSchema>;
