/**
 * PostgreSQL Function: refresh_metadata_templates_cache_on_change
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: refresh_metadata_templates_cache_on_change
 */
export type RefreshMetadataTemplatesCacheOnChangeArgs = {
};

/**
 * Zod schema for refresh_metadata_templates_cache_on_change function arguments
 */
export const refreshMetadataTemplatesCacheOnChangeArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type RefreshMetadataTemplatesCacheOnChangeArgsFromZod = z.infer<typeof refreshMetadataTemplatesCacheOnChangeArgsSchema>;

/**
 * Return type for PostgreSQL function: refresh_metadata_templates_cache_on_change
 */
export type RefreshMetadataTemplatesCacheOnChangeReturns = unknown;

/**
 * Zod schema for refresh_metadata_templates_cache_on_change function return type
 */
export const refreshMetadataTemplatesCacheOnChangeReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type RefreshMetadataTemplatesCacheOnChangeReturnsFromZod = z.infer<typeof refreshMetadataTemplatesCacheOnChangeReturnsSchema>;
