/**
 * PostgreSQL Function: refresh_trending_metrics_view
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: refresh_trending_metrics_view
 */
export type RefreshTrendingMetricsViewArgs = {
};

/**
 * Zod schema for refresh_trending_metrics_view function arguments
 */
export const refreshTrendingMetricsViewArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type RefreshTrendingMetricsViewArgsFromZod = z.infer<typeof refreshTrendingMetricsViewArgsSchema>;

/**
 * Return type for PostgreSQL function: refresh_trending_metrics_view
 */
export type RefreshTrendingMetricsViewReturns = void;
