/**
 * PostgreSQL Function: remove_bookmark
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { RemoveBookmarkResult } from '../composites/remove_bookmark_result';
import { removeBookmarkResultSchema } from '../composites/remove_bookmark_result';

/**
 * Arguments for PostgreSQL function: remove_bookmark
 */
export type RemoveBookmarkArgs = {
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
  /** Parameter: p_content_type (content_category) */
  p_content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_content_slug (text) */
  p_content_slug: string;
};

/**
 * Zod schema for remove_bookmark function arguments
 */
export const removeBookmarkArgsSchema = z.object({
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
  /** Parameter: p_content_type */
  p_content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_content_slug */
  p_content_slug: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type RemoveBookmarkArgsFromZod = z.infer<typeof removeBookmarkArgsSchema>;

/**
 * Return type for PostgreSQL function: remove_bookmark
 */
export type RemoveBookmarkReturns = RemoveBookmarkResult;

/**
 * Zod schema for remove_bookmark function return type
 */
export const removeBookmarkReturnsSchema = removeBookmarkResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type RemoveBookmarkReturnsFromZod = z.infer<typeof removeBookmarkReturnsSchema>;
