/**
 * PostgreSQL Function: schedule_next_sequence_step
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: schedule_next_sequence_step
 */
export type ScheduleNextSequenceStepArgs = {
  /** Parameter: p_email (text) */
  p_email: string;
  /** Parameter: p_current_step (int4) */
  p_current_step: number;
};

/**
 * Zod schema for schedule_next_sequence_step function arguments
 */
export const scheduleNextSequenceStepArgsSchema = z.object({
  /** Parameter: p_email */
  p_email: z.string(),
  /** Parameter: p_current_step */
  p_current_step: z.number(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ScheduleNextSequenceStepArgsFromZod = z.infer<typeof scheduleNextSequenceStepArgsSchema>;

/**
 * Return type for PostgreSQL function: schedule_next_sequence_step
 */
export type ScheduleNextSequenceStepReturns = void;
