/**
 * PostgreSQL Function: search_by_popularity
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: search_by_popularity
 */
export type SearchByPopularityArgs = {
  /** Parameter: p_query (text, optional) */
  p_query?: string;
  /** Parameter: p_categories (_content_category, optional) */
  p_categories?: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog'[];
  /** Parameter: p_tags (_text, optional) */
  p_tags?: string[];
  /** Parameter: p_authors (_text, optional) */
  p_authors?: string[];
  /** Parameter: p_limit (int4, optional) */
  p_limit?: number;
  /** Parameter: p_offset (int4, optional) */
  p_offset?: number;
};

/**
 * Zod schema for search_by_popularity function arguments
 */
export const searchByPopularityArgsSchema = z.object({
  /** Parameter: p_query */
  p_query: z.string().nullable().optional(),
  /** Parameter: p_categories */
  p_categories: z.array(z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog'])).nullable().optional(),
  /** Parameter: p_tags */
  p_tags: z.array(z.string()).nullable().optional(),
  /** Parameter: p_authors */
  p_authors: z.array(z.string()).nullable().optional(),
  /** Parameter: p_limit */
  p_limit: z.number().nullable().optional(),
  /** Parameter: p_offset */
  p_offset: z.number().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SearchByPopularityArgsFromZod = z.infer<typeof searchByPopularityArgsSchema>;

/**
 * Return row type for PostgreSQL function: search_by_popularity
 */
export type SearchByPopularityReturnRow = {
  /** id (uuid, nullable) */
  id: string | null;
  /** slug (text, nullable) */
  slug: string | null;
  /** title (text, nullable) */
  title: string | null;
  /** description (text, nullable) */
  description: string | null;
  /** category (content_category, nullable) */
  category: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog' | null;
  /** author (text, nullable) */
  author: string | null;
  /** author_profile_url (text, nullable) */
  author_profile_url: string | null;
  /** date_added (date, nullable) */
  date_added: string | null;
  /** tags (_text, nullable) */
  tags: string[] | null;
  /** created_at (timestamptz, nullable) */
  created_at: string | null;
  /** updated_at (timestamptz, nullable) */
  updated_at: string | null;
  /** features (_text, nullable) */
  features: string[] | null;
  /** use_cases (_text, nullable) */
  use_cases: string[] | null;
  /** examples (jsonb, nullable) */
  examples: Record<string, unknown> | null;
  /** view_count (int8, nullable) */
  view_count: number | null;
  /** copy_count (int8, nullable) */
  copy_count: number | null;
  /** bookmark_count (int8, nullable) */
  bookmark_count: number | null;
  /** popularity_score (float4, nullable) */
  popularity_score: number | null;
};

/**
 * Zod schema for search_by_popularity return row
 */
export const searchByPopularityReturnRowSchema = z.object({
  id: z.string().uuid().nullable(),
  slug: z.string().nullable(),
  title: z.string().nullable(),
  description: z.string().nullable(),
  category: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']).nullable(),
  author: z.string().nullable(),
  author_profile_url: z.string().nullable(),
  date_added: z.string().nullable(),
  tags: z.array(z.string()).nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  features: z.array(z.string()).nullable(),
  use_cases: z.array(z.string()).nullable(),
  examples: z.any().nullable(),
  view_count: z.number().nullable(),
  copy_count: z.number().nullable(),
  bookmark_count: z.number().nullable(),
  popularity_score: z.number().nullable(),
});

/**
 * Return type for PostgreSQL function: search_by_popularity
 */
export type SearchByPopularityReturns = SearchByPopularityReturnRow[];

/**
 * Zod schema for search_by_popularity function return type
 */
export const searchByPopularityReturnsSchema = z.array(searchByPopularityReturnRowSchema);

/**
 * Type inference from Zod schema (should match type above)
 */
export type SearchByPopularityReturnsFromZod = z.infer<typeof searchByPopularityReturnsSchema>;
