/**
 * PostgreSQL Function: search_mv
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: search_mv
 */
export type SearchMvArgs = {
};

/**
 * Zod schema for search_mv function arguments
 */
export const searchMvArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SearchMvArgsFromZod = z.infer<typeof searchMvArgsSchema>;

/**
 * Return type for PostgreSQL function: search_mv
 */
export type SearchMvReturns = void;
