/**
 * PostgreSQL Function: should_generate_package
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: should_generate_package
 */
export type ShouldGeneratePackageArgs = {
  /** Parameter: category_name (text) */
  category_name: string;
};

/**
 * Zod schema for should_generate_package function arguments
 */
export const shouldGeneratePackageArgsSchema = z.object({
  /** Parameter: category_name */
  category_name: z.string(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ShouldGeneratePackageArgsFromZod = z.infer<typeof shouldGeneratePackageArgsSchema>;

/**
 * Return type for PostgreSQL function: should_generate_package
 */
export type ShouldGeneratePackageReturns = unknown;

/**
 * Zod schema for should_generate_package function return type
 */
export const shouldGeneratePackageReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type ShouldGeneratePackageReturnsFromZod = z.infer<typeof shouldGeneratePackageReturnsSchema>;
