/**
 * PostgreSQL Function: sync_changelog_entry
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: sync_changelog_entry
 */
export type SyncChangelogEntryArgs = {
  /** Parameter: p_version (text) */
  p_version: string;
  /** Parameter: p_date (text) */
  p_date: string;
  /** Parameter: p_content (text) */
  p_content: string;
  /** Parameter: p_tldr (text, optional) */
  p_tldr: string | undefined | null | undefined;
  /** Parameter: p_what_changed (text, optional) */
  p_what_changed: string | undefined | null | undefined;
  /** Parameter: p_raw_content (text, optional) */
  p_raw_content: string | undefined | null | undefined;
  /** Parameter: p_sections (jsonb, optional) */
  p_sections: Record<string, unknown> | undefined | null | undefined;
  /** Parameter: p_metadata (jsonb, optional) */
  p_metadata: Record<string, unknown> | undefined | null | undefined;
};

/**
 * Zod schema for sync_changelog_entry function arguments
 */
export const syncChangelogEntryArgsSchema = z.object({
  /** Parameter: p_version */
  p_version: z.string(),
  /** Parameter: p_date */
  p_date: z.string(),
  /** Parameter: p_content */
  p_content: z.string(),
  /** Parameter: p_tldr */
  p_tldr: z.string().nullable().optional(),
  /** Parameter: p_what_changed */
  p_what_changed: z.string().nullable().optional(),
  /** Parameter: p_raw_content */
  p_raw_content: z.string().nullable().optional(),
  /** Parameter: p_sections */
  p_sections: z.any().nullable().optional(),
  /** Parameter: p_metadata */
  p_metadata: z.any().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type SyncChangelogEntryArgsFromZod = z.infer<typeof syncChangelogEntryArgsSchema>;

/**
 * Return type for PostgreSQL function: sync_changelog_entry
 */
export type SyncChangelogEntryReturns = Record<string, unknown>[];

/**
 * Zod schema for sync_changelog_entry function return type
 */
export const syncChangelogEntryReturnsSchema = z.array(z.any());

/**
 * Type inference from Zod schema (should match type above)
 */
export type SyncChangelogEntryReturnsFromZod = z.infer<typeof syncChangelogEntryReturnsSchema>;
