/**
 * PostgreSQL Function: toggle_job_status
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ToggleJobStatusResult } from '../composites/toggle_job_status_result';
import { toggleJobStatusResultSchema } from '../composites/toggle_job_status_result';

/**
 * Arguments for PostgreSQL function: toggle_job_status
 */
export type ToggleJobStatusArgs = {
  /** Parameter: p_job_id (uuid) */
  p_job_id: string;
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
  /** Parameter: p_new_status (job_status) */
  p_new_status: 'draft' | 'pending_payment' | 'pending_review' | 'active' | 'expired' | 'rejected' | 'deleted';
};

/**
 * Zod schema for toggle_job_status function arguments
 */
export const toggleJobStatusArgsSchema = z.object({
  /** Parameter: p_job_id */
  p_job_id: z.string().uuid(),
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
  /** Parameter: p_new_status */
  p_new_status: z.enum(['draft', 'pending_payment', 'pending_review', 'active', 'expired', 'rejected', 'deleted']),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleJobStatusArgsFromZod = z.infer<typeof toggleJobStatusArgsSchema>;

/**
 * Return type for PostgreSQL function: toggle_job_status
 */
export type ToggleJobStatusReturns = ToggleJobStatusResult;

/**
 * Zod schema for toggle_job_status function return type
 */
export const toggleJobStatusReturnsSchema = toggleJobStatusResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleJobStatusReturnsFromZod = z.infer<typeof toggleJobStatusReturnsSchema>;
