/**
 * PostgreSQL Function: toggle_review_helpful
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ToggleReviewHelpfulResult } from '../composites/toggle_review_helpful_result';
import { toggleReviewHelpfulResultSchema } from '../composites/toggle_review_helpful_result';

/**
 * Arguments for PostgreSQL function: toggle_review_helpful
 */
export type ToggleReviewHelpfulArgs = {
  /** Parameter: p_review_id (uuid) */
  p_review_id: string;
  /** Parameter: p_user_id (uuid) */
  p_user_id: string;
  /** Parameter: p_helpful (bool) */
  p_helpful: boolean;
};

/**
 * Zod schema for toggle_review_helpful function arguments
 */
export const toggleReviewHelpfulArgsSchema = z.object({
  /** Parameter: p_review_id */
  p_review_id: z.string().uuid(),
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid(),
  /** Parameter: p_helpful */
  p_helpful: z.boolean(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleReviewHelpfulArgsFromZod = z.infer<typeof toggleReviewHelpfulArgsSchema>;

/**
 * Return type for PostgreSQL function: toggle_review_helpful
 */
export type ToggleReviewHelpfulReturns = ToggleReviewHelpfulResult;

/**
 * Zod schema for toggle_review_helpful function return type
 */
export const toggleReviewHelpfulReturnsSchema = toggleReviewHelpfulResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleReviewHelpfulReturnsFromZod = z.infer<typeof toggleReviewHelpfulReturnsSchema>;
