/**
 * PostgreSQL Function: toggle_content_vote
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

import type { ToggleContentVoteResult } from '../composites/toggle_content_vote_result';
import { toggleContentVoteResultSchema } from '../composites/toggle_content_vote_result';

/**
 * Arguments for PostgreSQL function: toggle_content_vote
 */
export type ToggleContentVoteArgs = {
  /** Parameter: p_content_slug (text) */
  p_content_slug: string;
  /** Parameter: p_content_type (content_category) */
  p_content_type: 'agents' | 'mcp' | 'rules' | 'commands' | 'hooks' | 'statuslines' | 'skills' | 'collections' | 'guides' | 'jobs' | 'changelog';
  /** Parameter: p_user_id (uuid, optional) */
  p_user_id?: string;
  /** Parameter: p_session_id (text, optional) */
  p_session_id?: string;
};

/**
 * Zod schema for toggle_content_vote function arguments
 */
export const toggleContentVoteArgsSchema = z.object({
  /** Parameter: p_content_slug */
  p_content_slug: z.string(),
  /** Parameter: p_content_type */
  p_content_type: z.enum(['agents', 'mcp', 'rules', 'commands', 'hooks', 'statuslines', 'skills', 'collections', 'guides', 'jobs', 'changelog']),
  /** Parameter: p_user_id */
  p_user_id: z.string().uuid().nullable().optional(),
  /** Parameter: p_session_id */
  p_session_id: z.string().nullable().optional(),
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleContentVoteArgsFromZod = z.infer<typeof toggleContentVoteArgsSchema>;

/**
 * Return type for PostgreSQL function: toggle_content_vote
 */
export type ToggleContentVoteReturns = ToggleContentVoteResult;

/**
 * Zod schema for toggle_content_vote function return type
 */
export const toggleContentVoteReturnsSchema = toggleContentVoteResultSchema;

/**
 * Type inference from Zod schema (should match type above)
 */
export type ToggleContentVoteReturnsFromZod = z.infer<typeof toggleContentVoteReturnsSchema>;
