/**
 * PostgreSQL Function: trigger_welcome_email_on_newsletter_signup
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: trigger_welcome_email_on_newsletter_signup
 */
export type TriggerWelcomeEmailOnNewsletterSignupArgs = {
};

/**
 * Zod schema for trigger_welcome_email_on_newsletter_signup function arguments
 */
export const triggerWelcomeEmailOnNewsletterSignupArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type TriggerWelcomeEmailOnNewsletterSignupArgsFromZod = z.infer<typeof triggerWelcomeEmailOnNewsletterSignupArgsSchema>;

/**
 * Return type for PostgreSQL function: trigger_welcome_email_on_newsletter_signup
 */
export type TriggerWelcomeEmailOnNewsletterSignupReturns = unknown;

/**
 * Zod schema for trigger_welcome_email_on_newsletter_signup function return type
 */
export const triggerWelcomeEmailOnNewsletterSignupReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type TriggerWelcomeEmailOnNewsletterSignupReturnsFromZod = z.infer<typeof triggerWelcomeEmailOnNewsletterSignupReturnsSchema>;
