/**
 * PostgreSQL Function: update_updated_at_column
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_updated_at_column
 */
export type UpdateUpdatedAtColumnArgs = {
};

/**
 * Zod schema for update_updated_at_column function arguments
 */
export const updateUpdatedAtColumnArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUpdatedAtColumnArgsFromZod = z.infer<typeof updateUpdatedAtColumnArgsSchema>;

/**
 * Return type for PostgreSQL function: update_updated_at_column
 */
export type UpdateUpdatedAtColumnReturns = unknown;

/**
 * Zod schema for update_updated_at_column function return type
 */
export const updateUpdatedAtColumnReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUpdatedAtColumnReturnsFromZod = z.infer<typeof updateUpdatedAtColumnReturnsSchema>;
