/**
 * PostgreSQL Function: update_app_setting_version
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_app_setting_version
 */
export type UpdateAppSettingVersionArgs = {
};

/**
 * Zod schema for update_app_setting_version function arguments
 */
export const updateAppSettingVersionArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateAppSettingVersionArgsFromZod = z.infer<typeof updateAppSettingVersionArgsSchema>;

/**
 * Return type for PostgreSQL function: update_app_setting_version
 */
export type UpdateAppSettingVersionReturns = unknown;

/**
 * Zod schema for update_app_setting_version function return type
 */
export const updateAppSettingVersionReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateAppSettingVersionReturnsFromZod = z.infer<typeof updateAppSettingVersionReturnsSchema>;
