/**
 * PostgreSQL Function: update_user_bookmark_count
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_user_bookmark_count
 */
export type UpdateUserBookmarkCountArgs = {
};

/**
 * Zod schema for update_user_bookmark_count function arguments
 */
export const updateUserBookmarkCountArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUserBookmarkCountArgsFromZod = z.infer<typeof updateUserBookmarkCountArgsSchema>;

/**
 * Return type for PostgreSQL function: update_user_bookmark_count
 */
export type UpdateUserBookmarkCountReturns = unknown;

/**
 * Zod schema for update_user_bookmark_count function return type
 */
export const updateUserBookmarkCountReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUserBookmarkCountReturnsFromZod = z.infer<typeof updateUserBookmarkCountReturnsSchema>;
