/**
 * PostgreSQL Function: update_user_collection_view_count
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_user_collection_view_count
 */
export type UpdateUserCollectionViewCountArgs = {
};

/**
 * Zod schema for update_user_collection_view_count function arguments
 */
export const updateUserCollectionViewCountArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUserCollectionViewCountArgsFromZod = z.infer<typeof updateUserCollectionViewCountArgsSchema>;

/**
 * Return type for PostgreSQL function: update_user_collection_view_count
 */
export type UpdateUserCollectionViewCountReturns = unknown;

/**
 * Zod schema for update_user_collection_view_count function return type
 */
export const updateUserCollectionViewCountReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateUserCollectionViewCountReturnsFromZod = z.infer<typeof updateUserCollectionViewCountReturnsSchema>;
