/**
 * PostgreSQL Function: update_content_review_stats
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_content_review_stats
 */
export type UpdateContentReviewStatsArgs = {
};

/**
 * Zod schema for update_content_review_stats function arguments
 */
export const updateContentReviewStatsArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateContentReviewStatsArgsFromZod = z.infer<typeof updateContentReviewStatsArgsSchema>;

/**
 * Return type for PostgreSQL function: update_content_review_stats
 */
export type UpdateContentReviewStatsReturns = unknown;

/**
 * Zod schema for update_content_review_stats function return type
 */
export const updateContentReviewStatsReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateContentReviewStatsReturnsFromZod = z.infer<typeof updateContentReviewStatsReturnsSchema>;
