/**
 * PostgreSQL Function: update_content_copy_count
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_content_copy_count
 */
export type UpdateContentCopyCountArgs = {
};

/**
 * Zod schema for update_content_copy_count function arguments
 */
export const updateContentCopyCountArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateContentCopyCountArgsFromZod = z.infer<typeof updateContentCopyCountArgsSchema>;

/**
 * Return type for PostgreSQL function: update_content_copy_count
 */
export type UpdateContentCopyCountReturns = unknown;

/**
 * Zod schema for update_content_copy_count function return type
 */
export const updateContentCopyCountReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateContentCopyCountReturnsFromZod = z.infer<typeof updateContentCopyCountReturnsSchema>;
