/**
 * PostgreSQL Function: update_email_engagement
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: update_email_engagement
 */
export type UpdateEmailEngagementArgs = {
};

/**
 * Zod schema for update_email_engagement function arguments
 */
export const updateEmailEngagementArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateEmailEngagementArgsFromZod = z.infer<typeof updateEmailEngagementArgsSchema>;

/**
 * Return type for PostgreSQL function: update_email_engagement
 */
export type UpdateEmailEngagementReturns = unknown;

/**
 * Zod schema for update_email_engagement function return type
 */
export const updateEmailEngagementReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type UpdateEmailEngagementReturnsFromZod = z.infer<typeof updateEmailEngagementReturnsSchema>;
