/**
 * PostgreSQL Function: validate_interests_array
 * 
 * 🔒 AUTO-GENERATED - DO NOT EDIT
 * Generated by prisma-postgres-types-generator
 */

import { z } from 'zod';

/**
 * Arguments for PostgreSQL function: validate_interests_array
 */
export type ValidateInterestsArrayArgs = {
};

/**
 * Zod schema for validate_interests_array function arguments
 */
export const validateInterestsArrayArgsSchema = z.object({
});

/**
 * Type inference from Zod schema (should match type above)
 */
export type ValidateInterestsArrayArgsFromZod = z.infer<typeof validateInterestsArrayArgsSchema>;

/**
 * Return type for PostgreSQL function: validate_interests_array
 */
export type ValidateInterestsArrayReturns = unknown;

/**
 * Zod schema for validate_interests_array function return type
 */
export const validateInterestsArrayReturnsSchema = z.any();

/**
 * Type inference from Zod schema (should match type above)
 */
export type ValidateInterestsArrayReturnsFromZod = z.infer<typeof validateInterestsArrayReturnsSchema>;
