-- Migration: Remove mark_resend_sync_complete RPC function
-- Version: 20251218120677
-- Applied via: Supabase MCP
-- Date: 2025-12-18
--
-- Description: Remove mark_resend_sync_complete RPC function - not found in codebase
--
-- This function marked a Resend sync operation as complete.
-- Function signature: mark_resend_sync_complete(...)
--
-- Verification:
-- - Not found in packages/data-layer/src/services/ (no service method calls)
-- - Not found in packages/web-runtime/src/data/ (no data fetching calls)
-- - Not found in packages/web-runtime/src/inngest/ (no Inngest function usage)
-- - Not found in apps/edge/ (no edge function usage)
--
-- Safe to remove: No codebase references found
DROP FUNCTION IF EXISTS public.mark_resend_sync_complete (uuid, text, boolean, text);
