-- Migration: Remove get_database_fingerprint RPC function
-- Version: 20251218120671
-- Applied via: Supabase MCP
-- Date: 2025-12-18
--
-- Description: Remove get_database_fingerprint RPC function - not found in codebase
--
-- This function returned database fingerprint information (table stats, row counts, etc.).
-- Function signature: get_database_fingerprint()
-- Returns: SETOF database_fingerprint_item
--
-- Verification:
-- - Not found in packages/data-layer/src/services/ (no service method calls)
-- - Not found in packages/web-runtime/src/data/ (no data fetching calls)
-- - Not found in packages/web-runtime/src/actions/ (no action calls)
-- - Not found in apps/web/src/app/ (no page usage)
-- - Not found in apps/edge/ (no edge function usage)
--
-- Note: This appears to be a diagnostic/admin function that may have been used for monitoring
--
-- Safe to remove: No codebase references found

DROP FUNCTION IF EXISTS public.get_database_fingerprint();
