-- Migration: Remove get_pending_submissions RPC function
-- Version: 20251218120663
-- Applied via: Supabase MCP
-- Date: 2025-12-18
--
-- Description: Remove get_pending_submissions RPC function - not found in codebase
--
-- This function returned pending content submissions (admin-only).
-- Function signature: get_pending_submissions(p_limit integer DEFAULT 50, p_offset integer DEFAULT 0, p_filter_type text DEFAULT NULL)
-- Returns: SETOF pending_submissions_item
-- Requires: Admin role (checked via is_admin())
--
-- Verification:
-- - Not found in packages/data-layer/src/services/ (no service method calls)
-- - Not found in packages/web-runtime/src/data/ (no data fetching calls)
-- - Not found in packages/web-runtime/src/actions/ (no action calls)
-- - Not found in apps/web/src/app/ (no page usage)
--
-- Safe to remove: No codebase references found
DROP FUNCTION IF EXISTS public.get_pending_submissions (integer, integer, text);
