-- Migration: Remove unused get_user_dashboard RPC
-- Version: 20251218120009
-- Applied via: Supabase MCP (or manual application)
-- Date: 2025-12-18
--
-- Description: Remove get_user_dashboard RPC function - Converted to Prisma
-- AccountService.getUserDashboard now uses Prisma directly (line 260), RPC no longer called.
--
-- Function signature: get_user_dashboard(p_user_id uuid)
-- Related: AccountService.getUserDashboard uses Prisma queries instead
DROP FUNCTION IF EXISTS public.get_user_dashboard (uuid);
