-- Migration: Remove unused get_user_activity_summary RPC
-- Version: 20251218120011
-- Applied via: Supabase MCP (or manual application)
-- Date: 2025-12-18
--
-- Description: Remove get_user_activity_summary RPC function - Converted to Prisma
-- AccountService.getUserActivitySummary now uses Prisma directly (line 1212), RPC no longer called.
--
-- Function signature: get_user_activity_summary(p_user_id uuid)
-- Related: AccountService.getUserActivitySummary uses Prisma queries instead
DROP FUNCTION IF EXISTS public.get_user_activity_summary (uuid);
