-- Migration: Remove get_user_content_vote RPC function
-- Version: 20251218120659
-- Applied via: Supabase MCP
-- Date: 2025-12-18
--
-- Description: Remove get_user_content_vote RPC function - not found in codebase
--
-- This function checked if a user or session has voted "I use this" on a content item.
-- Function signature: get_user_content_vote(p_content_slug text, p_content_type content_category, p_user_id uuid DEFAULT NULL, p_session_id text DEFAULT NULL)
-- Returns: boolean
--
-- Verification:
-- - Not found in packages/web-runtime/src/data/ (no data fetching calls)
-- - Not found in packages/web-runtime/src/actions/ (no action calls)
-- - Not found in apps/web/src/app/ (no page usage)
-- - Not found in apps/edge/ (no edge function usage)
--
-- Note: toggle_content_vote RPC is still used and should NOT be removed
--
-- Safe to remove: No codebase references found

DROP FUNCTION IF EXISTS public.get_user_content_vote(text, public.content_category, uuid, text);
