-- Migration: Remove search_by_popularity RPC function
-- Version: 20251218120680
-- Applied via: Supabase MCP
-- Date: 2025-12-18
--
-- Description: Remove search_by_popularity RPC function - not found in codebase
--
-- This function searched content by popularity.
-- Function signature: search_by_popularity(...)
--
-- Verification:
-- - Not found in packages/data-layer/src/services/search.ts (no search service calls)
-- - Not found in packages/web-runtime/src/data/ (no data fetching calls)
-- - Not found in packages/web-runtime/src/actions/ (no action calls)
-- - Not found in apps/web/src/app/api/search/ (no API route usage)
--
-- Note: Search functionality uses search_unified or other search RPCs
--
-- Safe to remove: No codebase references found

DROP FUNCTION IF EXISTS public.search_by_popularity(text, public.content_category[], text[], text[], integer, integer);
