-- Migration: Remove unused get_user_companies RPC
-- Version: 20251218120007
-- Applied via: Supabase MCP (or manual application)
-- Date: 2025-12-18
--
-- Description: Remove get_user_companies RPC function - Converted to Prisma
-- AccountService.getUserCompanies now uses Prisma directly (line 763), RPC no longer called.
--
-- Function signature: get_user_companies(p_user_id uuid)
-- Related: AccountService.getUserCompanies uses Prisma queries instead
DROP FUNCTION IF EXISTS public.get_user_companies (uuid);
