/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/build/generate-category-config.ts
 * Source: PostgreSQL category_configs table via get_category_configs_with_features RPC
 *
 * This file is generated at build time to eliminate runtime database queries.
 * To update: pnpm generate:categories
 */

import type { z } from 'zod';
import {
  BookOpen,
  Briefcase,
  Code,
  FileText,
  Layers,
  type LucideIcon,
  Server,
  Sparkles,
  Terminal,
  Webhook,
} from '@/src/lib/icons';
import {
  publicContentRowSchema,
  publicJobsRowSchema,
} from '@/src/lib/schemas/generated/db-schemas';
import type { CategoryId, ContentType, UnifiedCategoryConfig } from './category-config';

const ICON_MAP: Record<string, LucideIcon> = {
  Sparkles,
  Terminal,
  Webhook,
  BookOpen,
  Server,
  Layers,
  Briefcase,
  FileText,
  Code,
};

const SCHEMA_MAP: Partial<Record<CategoryId, z.ZodType<ContentType>>> = {
  agents: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  mcp: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  commands: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  rules: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  hooks: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  statuslines: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  skills: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  collections: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  guides: publicContentRowSchema as unknown as z.ZodType<ContentType>,
  jobs: publicJobsRowSchema as unknown as z.ZodType<ContentType>,
};

/**
 * Static category configurations (generated at build time)
 * ZERO runtime database queries - 100% faster than unstable_cache
 */
export const CATEGORY_CONFIGS: Record<
  CategoryId,
  UnifiedCategoryConfig<ContentType, CategoryId>
> = {
  mcp: {
    id: 'mcp' as const,
    title: 'MCP Server',
    pluralTitle: 'MCP Servers',
    description:
      "Model Context Protocol servers that extend Claude's capabilities with external tools and data sources.",
    icon: ICON_MAP['Server'] || FileText,
    colorScheme: 'orange-500',
    showOnHomepage: true,
    keywords:
      'MCP servers, Model Context Protocol, Claude Desktop, external tools, API integration',
    metaDescription:
      'MCP servers for Claude Desktop in October 2025. Extend Claude with file systems, databases, APIs, and custom tools via Model Context Protocol.',
    schema: SCHEMA_MAP['mcp'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search MCP servers...',
      badges: [
        {
          icon: 'code',
          text: (count: number) =>
            '{count} MCP Servers Available'.replace('{count}', String(count)),
        },
        { text: 'Verified Integrations' },
        { text: 'Production Ready' },
      ],
    },
    detailPage: {
      displayConfig: true,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: true,
      security: true,
      troubleshooting: true,
      examples: true,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'View Configuration',
      type: 'scroll',
    },
    urlSlug: 'mcp',
    contentLoader: 'mcp',
  },
  jobs: {
    id: 'jobs' as const,
    title: 'Job',
    pluralTitle: 'Jobs',
    description:
      'Job listings for Claude-related positions, AI engineering roles, and opportunities to work with AI technology.',
    icon: ICON_MAP['Briefcase'] || FileText,
    colorScheme: 'emerald-500',
    showOnHomepage: false,
    keywords: 'Claude jobs, AI jobs, engineering jobs, remote AI positions',
    metaDescription:
      'Job opportunities in Claude and AI in October 2025. Find roles working with Claude, AI engineering positions, and remote opportunities.',
    schema: SCHEMA_MAP['jobs'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 50,
      enableCache: true,
      cacheTTL: 86400000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: false,
      maxItemsPerResponse: 500,
    },
    listPage: {
      searchPlaceholder: 'Search jobs...',
      badges: [
        {
          icon: 'briefcase',
          text: (count: number) => '{count} Jobs Available'.replace('{count}', String(count)),
        },
        { text: 'Remote Work' },
        { text: 'AI Opportunities' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: false,
      installation: false,
      use_cases: false,
      configuration: false,
      security: false,
      troubleshooting: false,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'View Job',
      type: 'scroll',
    },
    urlSlug: 'jobs',
    contentLoader: 'jobs',
  },
  hooks: {
    id: 'hooks' as const,
    title: 'Hook',
    pluralTitle: 'Hooks',
    description: 'Event-driven automation hooks that trigger during Claude Code operations.',
    icon: ICON_MAP['Webhook'] || FileText,
    colorScheme: 'green-500',
    showOnHomepage: true,
    keywords: 'Claude hooks, event hooks, automation, Claude Code hooks, git hooks',
    metaDescription:
      'Event-driven hooks for Claude Code in October 2025. Automate workflows with pre-commit, post-merge, and custom event triggers.',
    schema: SCHEMA_MAP['hooks'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search hooks...',
      badges: [
        {
          icon: 'webhook',
          text: (count: number) => '{count} Hooks Available'.replace('{count}', String(count)),
        },
        { text: 'Event-Driven' },
        { text: 'Workflow Automation' },
      ],
    },
    detailPage: {
      displayConfig: true,
      configFormat: 'hook' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: true,
      security: false,
      troubleshooting: true,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'View on GitHub',
      type: 'github_link',
    },
    urlSlug: 'hooks',
    contentLoader: 'hooks',
  },
  rules: {
    id: 'rules' as const,
    title: 'Rule',
    pluralTitle: 'Rules',
    description: "Custom rules to guide Claude's behavior and responses in your projects.",
    icon: ICON_MAP['BookOpen'] || FileText,
    colorScheme: 'red-500',
    showOnHomepage: true,
    keywords: 'Claude rules, custom rules, behavior rules, project rules, .cursorrules',
    metaDescription:
      'Custom rules for Claude in October 2025. Define coding standards, architectural guidelines, and project-specific behavior for consistent AI assistance.',
    schema: SCHEMA_MAP['rules'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search rules...',
      badges: [
        {
          icon: 'book-open',
          text: (count: number) => '{count} Rules Available'.replace('{count}', String(count)),
        },
        { text: 'Behavior Customization' },
        { text: 'Context Control' },
      ],
    },
    detailPage: {
      displayConfig: true,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: false,
      installation: false,
      use_cases: true,
      configuration: true,
      security: false,
      troubleshooting: false,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Use Rule',
      type: 'notification',
    },
    urlSlug: 'rules',
    contentLoader: 'rules',
  },
  agents: {
    id: 'agents' as const,
    title: 'AI Agent',
    pluralTitle: 'AI Agents',
    description:
      "Browse specialized AI agents designed for specific tasks and workflows using Claude's capabilities.",
    icon: ICON_MAP['Sparkles'] || FileText,
    colorScheme: 'purple-500',
    showOnHomepage: true,
    keywords: 'Claude agents, AI agents, specialized assistants, workflow automation, Claude AI',
    metaDescription:
      'Specialized Claude AI agents for October 2025. Community-contributed coding, writing, research, and automation configurations ready for Claude Desktop and Code.',
    schema: SCHEMA_MAP['agents'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search AI agents...',
      badges: [
        {
          icon: 'sparkles',
          text: (count: number) => '{count} Agents Available'.replace('{count}', String(count)),
        },
        { text: 'Task Optimized' },
        { text: 'Ready to Deploy' },
      ],
    },
    detailPage: {
      displayConfig: true,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: true,
      security: false,
      troubleshooting: false,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Deploy Agent',
      type: 'notification',
    },
    urlSlug: 'agents',
    contentLoader: 'agents',
  },
  guides: {
    id: 'guides' as const,
    title: 'Guide',
    pluralTitle: 'Guides',
    description:
      'Comprehensive guides, tutorials, comparisons, and workflows for Claude. SEO-optimized content covering best practices, use cases, and troubleshooting.',
    icon: ICON_MAP['FileText'] || FileText,
    colorScheme: 'yellow-500',
    showOnHomepage: false,
    keywords: 'Claude guides, tutorials, how-to guides, best practices, workflows',
    metaDescription:
      'Comprehensive guides for Claude in October 2025. Tutorials, comparisons, workflows, and troubleshooting for Claude Desktop and Code.',
    schema: SCHEMA_MAP['guides'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search guides...',
      badges: [
        {
          icon: 'book-open',
          text: (count: number) => '{count} Guides Available'.replace('{count}', String(count)),
        },
        { text: 'Step-by-Step' },
        { text: 'Best Practices' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: false,
      installation: false,
      use_cases: true,
      configuration: false,
      security: false,
      troubleshooting: false,
      examples: true,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Read Guide',
      type: 'scroll',
    },
    urlSlug: 'guides',
    contentLoader: 'guides',
  },
  skills: {
    id: 'skills' as const,
    title: 'Skill',
    pluralTitle: 'Skills',
    description:
      'Task-focused capability guides for Claude (PDF, DOCX, PPTX, XLSX, and more) with requirements and runnable examples.',
    icon: ICON_MAP['Sparkles'] || FileText,
    colorScheme: 'pink-500',
    showOnHomepage: true,
    keywords: 'Claude skills, AI capabilities, task guides, skill packages, Claude Desktop skills',
    metaDescription:
      'Claude skills for October 2025. Downloadable capability packages with requirements, examples, and instructions for specific tasks.',
    schema: SCHEMA_MAP['skills'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search skills...',
      badges: [
        { text: (count: number) => '{count} Skills Available'.replace('{count}', String(count)) },
        { text: 'Enhanced Capabilities' },
        { text: 'Tool Extensions' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: false,
      security: false,
      troubleshooting: true,
      examples: true,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Download Skill',
      type: 'download',
    },
    urlSlug: 'skills',
    contentLoader: 'skills',
  },
  commands: {
    id: 'commands' as const,
    title: 'Command',
    pluralTitle: 'Commands',
    description:
      'Custom slash commands to enhance your Claude Code workflow with reusable prompts and actions.',
    icon: ICON_MAP['Terminal'] || FileText,
    colorScheme: 'blue-500',
    showOnHomepage: true,
    keywords: 'Claude commands, slash commands, custom commands, Claude Code, CLI',
    metaDescription:
      'Custom slash commands for Claude Code in October 2025. Community-created prompt templates, automation commands, and workflow shortcuts.',
    schema: SCHEMA_MAP['commands'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search commands...',
      badges: [
        {
          icon: 'terminal',
          text: (count: number) => '{count} Commands Available'.replace('{count}', String(count)),
        },
        { text: 'Quick Actions' },
        { text: 'Instant Setup' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: false,
      security: false,
      troubleshooting: true,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Copy Command',
      type: 'copy_command',
    },
    urlSlug: 'commands',
    contentLoader: 'commands',
  },
  changelog: {
    id: 'changelog' as const,
    title: 'Changelog Entry',
    pluralTitle: 'Changelog',
    description:
      'Product updates, new features, bug fixes, and improvements to the ClaudePro Directory.',
    icon: ICON_MAP['FileText'] || FileText,
    colorScheme: 'gray-500',
    showOnHomepage: false,
    keywords: 'changelog, updates, release notes, new features, bug fixes',
    metaDescription:
      'ClaudePro Directory changelog for October 2025. Track new features, improvements, and bug fixes.',
    schema:
      SCHEMA_MAP['changelog'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 100,
      enableCache: true,
      cacheTTL: 3600000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: false,
      maxItemsPerResponse: 100,
    },
    listPage: {
      searchPlaceholder: 'Search changelog...',
      badges: [
        { text: (count: number) => '{count} Updates'.replace('{count}', String(count)) },
        { text: 'Latest Changes' },
        { text: 'Version History' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: false,
      installation: false,
      use_cases: false,
      configuration: false,
      security: false,
      troubleshooting: false,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Read Update',
      type: 'scroll',
    },
    urlSlug: 'changelog',
    contentLoader: 'changelog_entries',
  },
  collections: {
    id: 'collections' as const,
    title: 'Collection',
    pluralTitle: 'Collections',
    description:
      'Curated bundles of related content items organized by theme, use case, or workflow for easy discovery.',
    icon: ICON_MAP['Layers'] || FileText,
    colorScheme: 'indigo-500',
    showOnHomepage: true,
    keywords: 'Claude collections, curated content, workflow bundles, themed collections',
    metaDescription:
      'Curated Claude collections for October 2025. Pre-assembled bundles of agents, commands, and tools for specific use cases and workflows.',
    schema:
      SCHEMA_MAP['collections'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search collections...',
      badges: [
        {
          icon: 'layers',
          text: (count: number) =>
            '{count} Collections Available'.replace('{count}', String(count)),
        },
        { text: 'Curated Workflows' },
        { text: 'Multi-Component' },
      ],
    },
    detailPage: {
      displayConfig: false,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: false,
      installation: false,
      use_cases: true,
      configuration: false,
      security: false,
      troubleshooting: false,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'View Collection',
      type: 'scroll',
    },
    urlSlug: 'collections',
    contentLoader: 'collections',
  },
  statuslines: {
    id: 'statuslines' as const,
    title: 'Statusline',
    pluralTitle: 'Statuslines',
    description:
      'Customizable status line configurations for Claude Code CLI with real-time session information.',
    icon: ICON_MAP['Terminal'] || FileText,
    colorScheme: 'cyan-500',
    showOnHomepage: true,
    keywords: 'Claude statusline, CLI statusline, terminal status, Claude Code customization',
    metaDescription:
      'Statusline scripts for Claude Code CLI in October 2025. Display git status, project info, and custom metrics in your terminal.',
    schema:
      SCHEMA_MAP['statuslines'] ?? (publicContentRowSchema as unknown as z.ZodType<ContentType>),
    typeName: 'Database["public"]["Tables"]["content"]["Row"]',
    generateFullContent: true,
    metadataFields: [
      'slug',
      'title',
      'description',
      'author',
      'tags',
      'category',
      'date_added',
      'source',
    ],
    buildConfig: {
      batchSize: 10,
      enableCache: true,
      cacheTTL: 300000,
    },
    apiConfig: {
      generateStaticAPI: true,
      includeTrending: true,
      maxItemsPerResponse: 1000,
    },
    listPage: {
      searchPlaceholder: 'Search statuslines...',
      badges: [
        {
          text: (count: number) =>
            '{count} Statuslines Available'.replace('{count}', String(count)),
        },
        { text: 'UI Customization' },
        { text: 'Real-time Status' },
      ],
    },
    detailPage: {
      displayConfig: true,
      configFormat: 'json' as 'json' | 'multi' | 'hook',
    },
    sections: {
      features: true,
      installation: true,
      use_cases: true,
      configuration: true,
      security: false,
      troubleshooting: true,
      examples: false,
    },
    metadata: {
      showGitHubLink: true,
    },
    primaryAction: {
      label: 'Copy Script',
      type: 'copy_script',
    },
    urlSlug: 'statuslines',
    contentLoader: 'statuslines',
  },
};

/**
 * All category IDs (static array)
 */
export const ALL_CATEGORY_IDS = [
  'mcp',
  'jobs',
  'hooks',
  'rules',
  'agents',
  'guides',
  'skills',
  'commands',
  'changelog',
  'collections',
  'statuslines',
] as const;

/**
 * Homepage category IDs (filtered at build time)
 */
export const HOMEPAGE_CATEGORY_IDS = [
  'mcp',
  'hooks',
  'rules',
  'agents',
  'skills',
  'commands',
  'collections',
  'statuslines',
] as const;

/**
 * Cacheable category IDs (excludes jobs and changelog)
 */
export const CACHEABLE_CATEGORY_IDS = [
  'mcp',
  'hooks',
  'rules',
  'agents',
  'guides',
  'skills',
  'commands',
  'collections',
  'statuslines',
] as const;
