import Script from 'next/script';
import type { UnifiedStructuredDataProps } from '@/src/lib/structured-data/schema-types';
import { serializeJsonLd } from '@/src/lib/utils/jsonld.utils';

/**
 * Unified Structured Data - Database-First Architecture
 * Uses json_ld column from PostgreSQL content table (100% database-driven)
 */
export async function UnifiedStructuredData({ item }: UnifiedStructuredDataProps) {
  // Use database-stored JSON-LD directly (populated by generate_json_ld_for_content RPC)
  const jsonLd = 'json_ld' in item ? item.json_ld : null;

  if (!jsonLd || typeof jsonLd !== 'object') {
    // Fallback: no JSON-LD available
    return null;
  }

  // Render database JSON-LD as Script tag
  return (
    <Script
      key={`${item.category}-${item.slug}-jsonld`}
      id={`structured-data-${item.category}-${item.slug}`}
      type="application/ld+json"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: JSON-LD from database is generated by trusted RPC function
      dangerouslySetInnerHTML={{
        __html: serializeJsonLd(jsonLd),
      }}
      strategy="afterInteractive"
    />
  );
}
