/**
 * Generate TypeScript types and Zod schemas for PostgreSQL composite types
 */

import type { CompositeTypeAttribute } from '../toolkit/introspection.ts';
import { mapPostgresTypeToZod } from '../toolkit/zod-mapper.ts';
import type { GeneratorConfig, GeneratorOutput } from './types.ts';
import {
  mapPostgresTypeToTypeScript,
  toCamelCase,
  toPascalCase,
  toSafeIdentifier,
  type TypeMappingContext,
} from './type-mapper.ts';

/**
 * Track which composite types are referenced (for imports)
 */
interface CompositeDependencies {
  /** Composite types that need to be imported */
  imports: Set<string>;
}

/**
 * Generate TypeScript types and Zod schemas for all composite types
 *
 * Generates files in dependency order to ensure nested composites are available.
 */
export async function generateCompositeTypes(
  compositeTypes: Record<string, CompositeTypeAttribute[]>,
  enums: Record<string, string[]>,
  config: GeneratorConfig
): Promise<GeneratorOutput> {
  const files: Record<string, string> = {};
  const exports: string[] = [];

  // Filter out excluded composite types
  // Note: Composite types should already be filtered before being passed here,
  // but we do a final check to ensure excluded types aren't generated
  // Patterns support exact matches and wildcards (*)
  let filteredComposites = compositeTypes;
  if (config.excludeCompositeTypes) {
    filteredComposites = Object.fromEntries(
      Object.entries(compositeTypes).filter(([name]) => {
        const matches = config.excludeCompositeTypes!.some((pattern) => {
          // If pattern contains *, treat as wildcard pattern
          if (pattern.includes('*')) {
            const regex = new RegExp('^' + pattern.replace(/\*/g, '.*') + '$');
            return regex.test(name);
          }
          // Otherwise, use exact match (not substring match)
          // This prevents "content" from matching "search_content_optimized_result"
          return name === pattern;
        });
        return !matches; // Exclude if matches pattern
      })
    );
  }

  const context: TypeMappingContext = {
    enums,
    compositeTypes: Object.keys(filteredComposites),
  };

  // Generate in dependency order (simple composites first, then nested ones)
  const sortedComposites = sortCompositesByDependency(filteredComposites);

  for (const compositeName of sortedComposites) {
    const attributes = compositeTypes[compositeName];
    if (!attributes) continue;

    const safeName = toSafeIdentifier(compositeName);
    const dependencies = findCompositeDependencies(attributes, filteredComposites);
    const content = generateCompositeFile(
      compositeName,
      attributes,
      filteredComposites,
      enums,
      context,
      config,
      dependencies
    );
    files[safeName] = content;
    exports.push(safeName);
  }

  return { files, exports };
}

/**
 * Sort composites by dependency order (simple first, nested last)
 */
function sortCompositesByDependency(
  compositeTypes: Record<string, CompositeTypeAttribute[]>
): string[] {
  const visited = new Set<string>();
  const sorted: string[] = [];

  function visit(name: string) {
    if (visited.has(name)) return;
    visited.add(name);

    const attrs = compositeTypes[name];
    if (!attrs) return;

    // Visit dependencies first
    for (const attr of attrs) {
      if (compositeTypes[attr.udtName]) {
        visit(attr.udtName);
      }
    }

    sorted.push(name);
  }

  for (const name of Object.keys(compositeTypes)) {
    visit(name);
  }

  return sorted;
}

/**
 * Find composite type dependencies
 */
function findCompositeDependencies(
  attributes: CompositeTypeAttribute[],
  allCompositeTypes: Record<string, CompositeTypeAttribute[]>
): CompositeDependencies {
  const imports = new Set<string>();

  for (const attr of attributes) {
    // Check if attribute is a composite type
    if (allCompositeTypes[attr.udtName]) {
      imports.add(attr.udtName);
    }
    // Check if attribute is an array of composite type (prefixed with _)
    else if (attr.udtName.startsWith('_')) {
      const baseType = attr.udtName.slice(1);
      if (allCompositeTypes[baseType]) {
        imports.add(baseType);
      }
    }
  }

  return { imports };
}

/**
 * Generate TypeScript and Zod code for a single composite type
 */
function generateCompositeFile(
  compositeName: string,
  attributes: CompositeTypeAttribute[],
  allCompositeTypes: Record<string, CompositeTypeAttribute[]>,
  enums: Record<string, string[]>,
  context: TypeMappingContext,
  config: GeneratorConfig,
  dependencies: CompositeDependencies
): string {
  const safeName = toSafeIdentifier(compositeName);
  const typeName = toPascalCase(safeName);
  const schemaName = `${toCamelCase(safeName)}Schema`;

  const lines: string[] = [
    '/**',
    ` * PostgreSQL Composite Type: ${compositeName}`,
    ' * ',
    ' * 🔒 AUTO-GENERATED - DO NOT EDIT',
    ' * Generated by prisma-postgres-types-generator',
    ' */',
    '',
  ];

  // Import Zod if generating schemas
  if (config.generateZod) {
    // Import zod - use direct import since generated files will be used in packages that have zod
    lines.push("import { z } from 'zod';", '');

    // Import nested composite types and schemas
    if (dependencies.imports.size > 0) {
      for (const depName of Array.from(dependencies.imports).sort()) {
        const depSafeName = toSafeIdentifier(depName);
        const depTypeName = toPascalCase(depSafeName);
        const depSchemaName = `${toCamelCase(depSafeName)}Schema`;
        lines.push(`import type { ${depTypeName} } from './${depSafeName}';`);
        if (config.generateZod) {
          lines.push(`import { ${depSchemaName} } from './${depSafeName}';`);
        }
      }
      lines.push('');
    }
  }

  // Generate TypeScript type
  if (config.generateTypes) {
    lines.push('/**', ` * PostgreSQL composite type: ${compositeName}`, ' */');
    lines.push(`export type ${typeName} = {`);

    for (const attr of attributes) {
      const tsType = mapPostgresTypeToTypeScript(attr.udtName, attr.nullable, false, context);

      // Handle nested composite types and arrays of composites
      // Note: mapPostgresTypeToTypeScript already handles composites and arrays,
      // but we need to override for proper type references
      // IMPORTANT: We need to preserve nullable handling when overriding
      let finalType = tsType;

      // Check if attribute is an array of composite
      if (attr.udtName.startsWith('_')) {
        const baseType = attr.udtName.slice(1);
        if (allCompositeTypes[baseType]) {
          // Array of composite - reference the generated type
          const baseTypeName = toPascalCase(toSafeIdentifier(baseType));
          finalType = `${baseTypeName}[]`;
          // Preserve nullable if it was in the original type
          if (attr.nullable && !finalType.includes('| null')) {
            finalType = `${finalType} | null`;
          }
        }
      } else if (allCompositeTypes[attr.udtName]) {
        // Nested composite - reference the generated type
        finalType = toPascalCase(toSafeIdentifier(attr.udtName));
        // Preserve nullable if it was in the original type
        if (attr.nullable && !finalType.includes('| null')) {
          finalType = `${finalType} | null`;
        }
      }

      // Add JSDoc with type information
      const description = `Attribute: ${attr.name} (${attr.udtName}${attr.nullable ? ', nullable' : ''})`;
      lines.push(`  /** ${description} */`);
      lines.push(`  ${toSafeIdentifier(attr.name)}: ${finalType};`);
    }

    lines.push('};', '');
  }

  // Generate Zod schema
  if (config.generateZod) {
    lines.push('/**', ` * Zod schema for ${compositeName} composite type`, ' */');
    lines.push(`export const ${schemaName} = z.object({`);

    for (const attr of attributes) {
      const zodType = generateZodTypeForAttribute(attr, allCompositeTypes, enums);
      const description = `Attribute: ${attr.name}`;
      lines.push(`  /** ${description} */`);
      lines.push(`  ${toSafeIdentifier(attr.name)}: ${zodType},`);
    }

    lines.push('});', '');

    // Type inference from Zod
    if (config.generateTypes) {
      // Type was already defined above, add alias from Zod for validation
      lines.push('/**', ' * Type inference from Zod schema (should match type above)', ' */');
      lines.push(`export type ${typeName}FromZod = z.infer<typeof ${schemaName}>;`);
    } else {
      // Only Zod generated, create the type from Zod
      lines.push('/**', ' * Type inference from Zod schema', ' */');
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate Zod type string for a composite type attribute
 */
function generateZodTypeForAttribute(
  attr: CompositeTypeAttribute,
  allCompositeTypes: Record<string, CompositeTypeAttribute[]>,
  enums: Record<string, string[]>
): string {
  // Check if this is an array of composite type
  if (attr.udtName.startsWith('_')) {
    const baseType = attr.udtName.slice(1);
    if (allCompositeTypes[baseType]) {
      // Array of composite - reference the generated schema
      const nestedSafeName = toSafeIdentifier(baseType);
      const nestedSchemaName = `${toCamelCase(nestedSafeName)}Schema`;
      let zodType = `z.array(${nestedSchemaName})`;

      if (attr.nullable) {
        zodType = `${zodType}.nullable()`;
      }

      return zodType;
    }
  }

  // Check if this is a nested composite type
  if (allCompositeTypes[attr.udtName]) {
    // Nested composite - reference the generated schema
    const nestedSafeName = toSafeIdentifier(attr.udtName);
    const nestedSchemaName = `${toCamelCase(nestedSafeName)}Schema`;
    let zodType = nestedSchemaName;

    if (attr.nullable) {
      zodType = `${zodType}.nullable()`;
    }

    return zodType;
  }

  // Use existing zod-mapper utility for scalar types
  const zodType = mapPostgresTypeToZod(
    {
      udtName: attr.udtName,
      nullable: attr.nullable,
      hasDefault: false,
      type: 'unknown',
    },
    enums
  );

  return zodType;
}
