name: Bundle Analysis

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*.{ts,tsx,js,jsx}'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.mjs'
      - 'tailwind.config.ts'
    paths-ignore:
      - 'content/**/*.json'
      - 'templates/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  # Build PR branch using reusable workflow
  build-pr:
    name: Build PR Branch
    uses: ./.github/workflows/build-reusable.yml
    with:
      cache-key-suffix: 'bundle-pr'
      upload-artifact: true

  # Build base branch using reusable workflow
  build-base:
    name: Build Base Branch
    uses: ./.github/workflows/build-reusable.yml
    with:
      cache-key-suffix: 'bundle-base'
      upload-artifact: true
      checkout-ref: ${{ github.base_ref }}

  # Analyze and compare bundle sizes
  analyze:
    name: Analyze & Compare
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-pr, build-base]

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-node-deps
        with:
          skip-build-content: 'true'

      - name: Download PR build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-pr.outputs.artifact-name }}
          path: .next-pr

      - name: Move PR build to analysis location
        run: |
          rm -rf .next
          mv .next-pr/.next .next
          echo "✅ PR build restored for analysis"

      - name: Analyze PR bundle
        run: npx -y nextjs-bundle-analysis@0.8.0
        env:
          BUNDLE_ANALYSIS_COMMENT: true

      - name: Upload PR bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-pr
          path: .next/analyze/__bundle_analysis.json
          retention-days: 7

      - name: Checkout base branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }}
          clean: false

      - name: Download base build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-base.outputs.artifact-name }}
          path: .next-base

      - name: Move base build to analysis location
        run: |
          rm -rf .next
          mv .next-base/.next .next
          echo "✅ Base build restored for analysis"

      - name: Analyze base bundle
        run: npx -y nextjs-bundle-analysis@0.8.0

      - name: Upload base bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-base
          path: .next/analyze/__bundle_analysis.json
          retention-days: 7

      - name: Compare bundle sizes
        uses: hashicorp/nextjs-bundle-analysis@v0.5.0
        with:
          base-branch: ${{ github.base_ref }}
          pr-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
