name: Daily Maintenance Cron

# Runs daily at 3 AM UTC
# Replaces Vercel cron to reduce platform dependency
on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  daily-maintenance:
    name: Run Daily Maintenance Tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Fail if takes longer than 10 minutes

    steps:
      - name: Trigger maintenance endpoint
        run: |
          echo "🔧 Triggering daily maintenance endpoint..."
          
          RESPONSE=$(curl -s -w "\n%{http_code}" -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "User-Agent: GitHub-Actions-Cron/1.0" \
            "${{ secrets.SITE_URL }}/api/cron/daily-maintenance")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          echo "Response Body: $BODY"
          
          if [ "$HTTP_CODE" != "200" ]; then
            echo "❌ Daily maintenance failed with HTTP $HTTP_CODE"
            exit 1
          fi
          
          echo "✅ Daily maintenance completed successfully"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Daily maintenance cron failed!"
          echo "Check the logs above for details."
          # Add Slack/Discord notification here if needed
