name: SEO Validation

on:
  pull_request:
    paths:
      - 'content/**/*.mdx'
      - 'content/**/*.json'
      - 'src/app/**/page.tsx'
      - 'src/lib/seo/**'
      - 'scripts/validate-*.ts'
  push:
    branches: [main]
    paths:
      - 'content/**/*.mdx'
      - 'content/**/*.json'

jobs:
  validate-seo:
    name: SEO Standards Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate SEO standards
        id: validate-seo
        run: |
          npm run validate:seo > seo-report.txt 2>&1 || echo "SEO_FAILED=true" >> $GITHUB_OUTPUT
          cat seo-report.txt
        continue-on-error: true

      - name: Validate title lengths
        id: validate-titles
        run: |
          npm run validate:titles:quick > titles-report.txt 2>&1 || echo "TITLES_FAILED=true" >> $GITHUB_OUTPUT
          cat titles-report.txt
        continue-on-error: true

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const seoReport = fs.readFileSync('seo-report.txt', 'utf8');
            const titlesReport = fs.readFileSync('titles-report.txt', 'utf8');

            const seoFailed = '${{ steps.validate-seo.outputs.SEO_FAILED }}' === 'true';
            const titlesFailed = '${{ steps.validate-titles.outputs.TITLES_FAILED }}' === 'true';

            const status = (!seoFailed && !titlesFailed) ? '✅ PASSED' : '❌ FAILED';

            const body = [
              '## SEO Validation ' + status,
              '',
              '### SEO Standards',
              seoFailed ? '❌ Failed' : '✅ Passed',
              '```',
              seoReport.slice(-2000),
              '```',
              '',
              '### Title Lengths',
              titlesFailed ? '❌ Failed' : '✅ Passed',
              '```',
              titlesReport.slice(-1000),
              '```',
              '',
              (seoFailed || titlesFailed) ? '**Please fix SEO issues before merging.**' : ''
            ].join('\n');

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail if validation failed
        if: steps.validate-seo.outputs.SEO_FAILED == 'true' || steps.validate-titles.outputs.TITLES_FAILED == 'true'
        run: exit 1
